export const EXPERIENCE_TIPS: Record<string, string[]> = {
  "topwater-gt": [
    "Cast beyond breaking structure and work a large popper (150–230 g) with hard, sweeping rod strokes to create a loud splashing commotion — GTs respond to aggression, not subtlety.",
    "Keep your rod tip low and pointed at the lure during the retrieve; this gives maximum hook-up leverage when a GT crashes the surface at full speed.",
    "Work the current seams and wash zones on an incoming tide — GTs use the white water to ambush baitfish flushed off the reef.",
    "Use a short, heavy fluorocarbon leader (80–100 lb, max 1 m) and a split ring rated to 400 lb — GT strikes are violent and equipment failure happens at the terminal end.",
    "After the bite window drops (usually two hours each side of high tide), switch to stickbaits fished subsurface with a walk-the-dog action to pick up fish holding deeper on the edges.",
  ],
  "marlin-trolling": [
    "Troll between 8 and 12 knots and vary speed slightly — a consistent mid-range speed of 9–10 knots suits both skirted lures and rigged baits and covers the most ground efficiently.",
    "Run a 5-lure spread: two short corner lures, two long outrigger lures, and a straight-back teaser. The teaser draws fish up to the strike zone without competing for hook-ups.",
    "Always confirm the 'double line' knot strength before setting the spread; the final few wraps on the reel experience the most shock load during a head-shake from a heavy fish.",
    "Watch your sounder for the 26 °C isotherm or blue–green colour change in the water — marlin concentrate at temperature and colour breaks, not just depth.",
    "During a long fight, reduce drag once the fish starts sounding and ease it back only as the fish surfaces — over-pressuring a tired marlin near the boat is when tackle and leaders snap.",
  ],
  "yellowfin-offshore": [
    "Feathers and cedar plugs in pink/red/black work best when trolling blind; switch to bibbed lures or rigged skipbaits once you see birds or surface activity.",
    "When tuna are balling bait underneath birds, stop the boat, cut the engine, and cast metal slices or poppers into the melee — a running engine will push the school down.",
    "Chum with a block of frozen pilchards or cubed tuna; once fish are in the berley trail, free-spool a live yakka or pilchard back into the slick for a natural presentation.",
    "Set drag at roughly 30% of breaking strain when trolling for YFT — they run hard and deep and you need enough line on the reel to survive the initial burst.",
    "At depth, slow-pitch butterfly jigs in 150–300 g sizes fished on a parabolic rod will pick up fish that ignored surface presentations — wahoo and mahi-mahi often join in.",
  ],
  "kingfish-jigging": [
    "Read the current before you lower a jig — drift so the jig is working across current, not with it. Kingfish hold on the down-current edge of structure and ambush anything swung past.",
    "Speed jigging (fast, rhythmic lifts) triggers reaction strikes from active fish; slow-pitch (allowing the jig to flutter on the fall) outperforms when fish are lethargic or in cold water.",
    "Use at least 80 lb fluorocarbon leader of 1–1.5 m — YTK have extremely abrasive mouths and will saw through lighter leader on boulders and pylons.",
    "Target the bite window around current changes; kingfish move from deep structure to shallower reef edges to feed aggressively during water movement, then become lethargic at slack.",
    "Keep your jig weight heavy enough to stay nearly vertical under the boat — if the jig drifts behind you in the current, you lose contact and miss the strike; go heavier, not lighter.",
  ],
  "light-tackle-pelagics": [
    "Be on the water at first light — longtail tuna and Spanish mackerel feed on surface bait schools in low light and the action typically dies by 9 am on calm days.",
    "Cast hard-bodied bibless lures or metal slices into breaking fish, let them sink 1–2 seconds, then wind fast with the rod tip high to create a fleeing-bait action.",
    "Use a 30–40 cm wire trace (single-strand or 49-strand) for Spanish mackerel — their razor teeth will cut through any mono or fluoro leader on the first run.",
    "On calm days, look for nervous bait patches (surface rippling without wind) and birds hovering low — these indicate fish pushing bait from below.",
    "If fish go off the surface bite, switch to a small chrome or pink metal jig and work it mid-water with fast lifts — longtail tuna in particular will keep chasing even when not visibly feeding.",
  ],
  "deep-dropping": [
    "Point your rod tip straight down while drifting — maintaining near-vertical line angle is critical so you can feel bites through 200–400 m of line with a spool full of braid.",
    "Rig multiple circle hooks (5/0–8/0) on a multi-dropper rig with chemical glow sticks — deep species rely on low-light attractants far more than colour at depth.",
    "An electric reel makes the 400 m+ wind-backs manageable; manually cranking a heavy multi-hook rig with multiple fish attached is exhausting and damages the fish.",
    "Blue-eye trevalla and hapuku live close to hard bottom structure at 200–500 m — use the sounder to mark the precise depth where the reef kicks up and sit just above it.",
    "Use large squid or octopus baits in preference to fish fillets — they stay on the hook better in strong deep-water currents and are harder for small nuisance fish to strip.",
  ],
  "coral-trout-reef": [
    "Fish the first two hours of the run-in tide — coral trout move off the bottom onto reef edges and coral heads to ambush baitfish as water rises and improves clarity.",
    "Drop a whole dead pilchard, squid, or small fish bait to the base of a coral bommie and hold the rod firmly — coral trout hit hard and immediately bolt back into the coral to bust you off.",
    "Use a 60–80 lb fluorocarbon leader of at least 1.5 m and a robust paternoster or running sinker rig — the coral trout's habitat is rocky, abrasive, and unforgiving on light gear.",
    "Don't spend more than five minutes on any one spot if there are no bites — coral trout are opportunistic but localised; covering ground finds more fish than waiting.",
    "Red Emperor and coral trout share similar habitat; switching to a lightly weighted live bait (small hussar or fusilier) will selectively interest bigger Emperor specimens.",
  ],
  "snapper-bottom-bashing": [
    "Berley is the single biggest edge in snapper fishing — a slow-dissolving block of mixed pilchards, bread, and tuna oil creates a scent trail that draws fish from a wide area.",
    "Use a running sinker rig on 30–40 lb fluorocarbon leader: the sinker sits on the bottom while the bait (whole or half pilchard, squid strip, or prawn) floats naturally in the berley trail.",
    "Night fishing on a new or full moon produces the largest snapper — fish come off the bottom to feed more aggressively in the dark and their guard is lowered.",
    "Match your sinker weight to the current — you want just enough to hold the bottom without dragging. If you're blowing out, wind back slowly and re-present rather than going heavier.",
    "Whole fresh squid on a suicide hook is hard to beat as a big-snapper bait; freeze-dried or fresh baits outperform frozen alternatives and stay on the hook through multiple strikes.",
  ],
  "slow-pitch-jigging": [
    "Use a dedicated slow-pitch rod (PE 1.5–3) that loads during the stroke and unloads on the fall — the rod spring, not the angler's effort, imparts the flutter action to the jig.",
    "Match jig weight to depth: roughly 1 g per metre is a starting guide. At 150 m use 150 g; increase until the jig drops nearly vertically beneath the boat.",
    "The strike usually comes on the fall after the stroke, not at the top of the lift — stay alert and maintain semi-taut line during the descent so you can feel the tick of a take.",
    "Rotate jig colours and shapes after 15–20 minutes without a strike; blue-eye trevalla respond well to pink and purple; snapper and nannygai often prefer red/orange or silver.",
    "Anchor or drift slowly — if you're drifting fast in current, your jig is planing behind the boat and not working correctly. Adjust weight or use a drogue to slow drift speed.",
  ],
  "wa-demersal-reef": [
    "Western Australia's demersal closures vary by zone and season — check the current DPIRD rules for bag limits, size limits, and closed seasons before your trip.",
    "Dhufish respond well to fresh or frozen squid presented on a paternoster rig in 20–80 m. Fish the reef edge where hard bottom transitions to sand for the highest density.",
    "Baldchin groper are most active in shallower water (15–40 m) around limestone and coral reef — use a whole pilchard or small live bait and present it slightly off the bottom.",
    "Position the boat upcurrent from the reef structure and drift baits back into the zone — anchoring directly over reef disturbs fish; drifting presents baits more naturally.",
    "The burley-trail approach works for WA demersals just as it does for eastern snapper — minced pilchard mixed with tuna oil weighted in a mesh bag and hung below the boat concentrates fish.",
  ],
  "barramundi-estuary": [
    "Fish the last two hours of a run-out tide around mangrove drains and creek mouths — barra sit in the fast water waiting for prawns and baitfish to be flushed through.",
    "Cast to within 30 cm of mangrove roots and retrieve the lure tight to structure — barramundi sit in the shadows of prop roots and won't move far to chase a lure in open water.",
    "Work surface lures (pencil poppers, walk-the-dog sticks) at dusk and dawn when barra are actively feeding on the surface; switch to sub-surface jerkbaits or vibes during the day.",
    "Mangrove jack occupy the same habitat as barra — use heavier leader (60–80 lb) and run-and-gun tactics to get fish out of cover before they wrap you around a root.",
    "Seasonally, barra move to deeper holes in cold water (below 24 °C) and become lethargic; slow presentations of lures or live bait near structure outperform fast retrieves in winter.",
  ],
  "flathead-soft-plastics": [
    "Flathead are ambush predators; they lie motionless on sandy or muddy bottoms waiting for prey to approach — let your soft plastic sink to the bottom and drag it slowly, pausing often.",
    "The drag-and-hop retrieve works best: lift the rod tip to drag the plastic along the bottom, let it settle, then hop again. Flathead usually strike when the lure falls.",
    "Fish shallow sand flats on an incoming tide during low-light periods (dawn and dusk) — flathead move from deeper channels onto the flats to feed as water covers them.",
    "Scented soft plastics (Squidgy, Z-Man, or Gulp) significantly outperform unscented plastics for flathead; fish hold the bait longer, giving you time to feel and set the hook.",
    "Use a 20–30 lb fluorocarbon leader — flathead have rough mouths and sharp gill plates that abrade lighter leaders, especially when you're lifting a large lizard from the bottom.",
  ],
  "bream-estuary": [
    "Bream are notoriously leader-shy in clear water — drop to 6–8 lb fluorocarbon leader and use the smallest hook that will hold your bait. Presentation beats power.",
    "Fish the edges of oyster leases, rock walls, and jetty pylons — bream graze for crustaceans and molluscs attached to hard structures and rarely sit in open water.",
    "Use fresh or live nippers (bass yabbies), prawns, or bloodworms on a size 6–8 suicide hook with a running sinker; these natural baits consistently outperform plastics for whiting and bream.",
    "Match the drift speed on an outgoing tide — set up above an oyster lease and let the current carry your bait through the zone at natural speed rather than casting and retrieving.",
    "Don't overlook dawn sessions on a low light incoming tide — large bream push into very shallow (knee-deep) water to feed on the flat and are extremely catchable on lightly weighted plastics.",
  ],
  "mulloway-night": [
    "The new moon is your best mulloway calendar — low light triggers bolder feeding behaviour in large fish that are wary and nocturnal by nature.",
    "Use large live bait (yellowfin bream, mullet, or tailor) hooked lightly through the back, near a rock wall, jetty, or river channel where tidal flow funnels baitfish.",
    "Set a sensitive rod rest, open the bail arm, and leave a small amount of line free — mulloway are cautious and will drop a bait immediately if they feel resistance before swallowing.",
    "The two hours around a tide change (particularly the run-out at night) are prime mulloway windows; they move from deep midstream holes onto the edges of channels to intercept prey.",
    "Use 60–80 lb fluorocarbon leader of 1.5–2 m — large mulloway have rough mouths and will shake violently against rock structures; light leader will not survive this.",
  ],
  "squid-evening": [
    "The peak window for squid is dusk through the first two hours of night, particularly around jetty lights and weed beds in 1–5 m of water.",
    "Work EGI jigs on a slow sink-and-twitch presentation: cast, let the jig sink on a slack line, then two quick rod flicks followed by another sink. Avoid fast continuous retrieves.",
    "Match jig size to water depth: small jigs (2.0–2.5) for shallow clear water, larger jigs (3.0–4.0) for darker or deeper water. Natural translucent colours work in clear conditions.",
    "Squid are sensitive to line movement — use a long, light fluorocarbon leader (4–6 lb, 1.5–2 m) and avoid tight lines during the sink phase so the jig falls naturally.",
    "Look for dark ink stains on jetty decking — this signals squid feeding activity in the area. Don't move away from a productive zone; re-cast to the same depth and structure.",
  ],
  "beach-casting-surf": [
    "Focus on gutters — the deeper water channels that run parallel to shore between two sand bars. Tailor, salmon, and mulloway congregate in these features, especially at dawn and after storms.",
    "After a storm has churned up the water and washed worms and crabs out of the sand, the surf fishing is often outstanding — discoloured water is productive, not a hindrance.",
    "Use a running sinker rig with a star sinker (to grip sand in current) and whole or pilchard flesh bait for mulloway; ganged hooks with a whole pilchard are the go for tailor and salmon.",
    "Cast beyond the break — tailor and salmon often patrol the back edge of the breaker zone. A long surf rod (3.6–4 m) and braided main line maximise casting distance from the beach.",
    "Tailor and salmon school, so when you get one, stay put and work the gutter until the school moves on. Salmon in particular run in tight groups and the bite window can be short.",
  ],
  "trout-fly-fishing": [
    "Hatch-matching is the foundation of trout fly fishing — observe what insects are hatching or falling onto the water before selecting your fly. Look under rocks for nymphs.",
    "For upstream nymphing, cast above a likely holding lie (behind rocks, undercut banks, pool tails) and let the nymph drift naturally with the current on a tight-but-relaxed line.",
    "The evening rise is the most productive dry-fly period — trout sip insects emerging from the surface film. Move quietly, approach from downstream, and cast upstream and across.",
    "Trout in heavily fished streams are line-shy — use the lightest tippet that the fish and structure allow (4X–6X) and keep your leader fully degreased so it sinks through the surface film.",
    "In cold water (below 10 °C), trout become lethargic and drop into deep slow pools. Switch to a slow-sinking or weighted nymph and fish it very slowly near the bottom.",
  ],
  "murray-cod-lure": [
    "Murray cod are structure lovers — position your cast to land a large lure (surface lure or deep-diving hard body) within 50 cm of an undercut bank, fallen timber, or bridge pylon.",
    "Surface lures fished at night or dusk produce the most aggressive strikes; cod will travel several metres to attack a large noisy surface lure in low-light conditions.",
    "In cold water (below 15 °C), cod slow down dramatically — switch from large fast-moving lures to a slow-rolled 5-inch paddle-tail swimbait retrieved at half speed with pauses.",
    "Use a strong, abrasion-resistant leader (40–60 lb fluorocarbon or equivalent mono) — cod engulf lures and their hard tooth plates and gill rakers are extremely abrasive on gear.",
    "Large golden perch occupy the same habitat as cod — scale up to 100 mm+ lures to select for cod over perch if you're specifically targeting trophy-sized fish.",
  ],
  "bass-impoundment": [
    "During the warmer months (spring–autumn), Australian bass and golden perch school at mid-water depth beneath surface-visible bait — find them with your sounder and drop a blade vibe to the depth of the school.",
    "Dawn topwater fishing on impoundments in summer is highly effective — bass push to the shallow timber edges at first light and smash surface lures before retreating to deeper water as the sun rises.",
    "Cold fronts push bass into deeper water and make them unresponsive to fast presentations; slow down and fish blade vibes or weighted grubs right on the bottom near submerged timber.",
    "Target the backs of creek arms in the impoundment after rain — fresh water inflow concentrates baitfish and bass congregate at the inflow zones to intercept flushed prey.",
    "Golden perch prefer slightly deeper water than bass and respond particularly well to blade vibes and small bibless lures fished at mid-depth over submerged structure.",
  ],
  "nz-blue-cod": [
    "Blue cod are territorial and highly aggressive — drop a bait or jig directly onto a rocky pinnacle or reef, and strikes often come within seconds. If no bite in two minutes, move on.",
    "Fresh squid or a live-bait combination jig/bait combo outperforms dead baits in the cold, clear water of southern New Zealand. Keepnet your first blue cod and use it as bait for tarakihi.",
    "Blue cod congregate on shallow rocky reefs (10–50 m) around the South Island's sounds and coasts — accurate anchoring or drift positioning over the pinnacle is more important than tackle.",
    "In Fiordland and the Sounds, combine bait fishing with a 50–80 g slow-pitch or butterfly jig to cover the water column — cod and tarakihi both hit jigs enthusiastically in cold water.",
    "Watch New Zealand's blue cod size limits and bag limits closely — regulations vary by region and are strictly enforced. Measure every fish before placing it in the bin.",
  ],
  "nz-snapper": [
    "Dawn is the prime snapper window in most New Zealand harbours and bays — fish are active in shallow water before light increases and they retreat to deeper structure.",
    "Create a berley cloud by filling a mesh bag with minced pilchards, bread crumbs, and tuna oil and hanging it off the back of the boat; free-line a fresh bait back into the slick.",
    "Flasher rigs (paternoster with mylar flies above the baited hook) add visual attraction in tidal current and significantly improve catch rates over a plain hook-and-bait approach.",
    "New Zealand snapper are deep, reliable fighters — use 15–20 lb fluorocarbon leader and at minimum a 4000-size reel with a smooth drag. Large fish (3+ kg) are common in the Hauraki Gulf.",
    "On the incoming tide, snapper push onto shallow reefs and rocky edges; on the outflow they retreat. Move with the tide rather than staying anchored in a spot that goes dead on the change.",
  ],
};
