export const EXPERIENCE_TIPS: Record<string, string[]> = {
  "topwater-gt": [
    "Cast beyond breaking structure and work a large popper (150–230 g) with hard, sweeping rod strokes to create a loud splashing commotion — GTs respond to aggression, not subtlety.",
    "Keep your rod tip low and pointed at the lure during the retrieve; this gives maximum hook-up leverage when a GT crashes the surface at full speed.",
    "Work the current seams and wash zones on an incoming tide — GTs use the white water to ambush baitfish flushed off the reef.",
    "Use a short, heavy fluorocarbon leader (80–100 lb, max 1 m) and a split ring rated to 400 lb — GT strikes are violent and equipment failure happens at the terminal end.",
    "After the bite window drops (usually two hours each side of high tide), switch to stickbaits fished subsurface with a walk-the-dog action to pick up fish holding deeper on the edges.",
  ],
  "marlin-trolling": [
    "Troll between 8 and 12 knots and vary speed slightly — a consistent mid-range speed of 9–10 knots suits both skirted lures and rigged baits and covers the most ground efficiently.",
    "Run a 5-lure spread: two short corner lures, two long outrigger lures, and a straight-back teaser. The teaser draws fish up to the strike zone without competing for hook-ups.",
    "Always confirm the 'double line' knot strength before setting the spread; the final few wraps on the reel experience the most shock load during a head-shake from a heavy fish.",
    "Watch your sounder for the 26 °C isotherm or blue–green colour change in the water — marlin concentrate at temperature and colour breaks, not just depth.",
    "During a long fight, reduce drag once the fish starts sounding and ease it back only as the fish surfaces — over-pressuring a tired marlin near the boat is when tackle and leaders snap.",
  ],
  "yellowfin-offshore": [
    "Feathers and cedar plugs in pink/red/black work best when trolling blind; switch to bibbed lures or rigged skipbaits once you see birds or surface activity.",
    "When tuna are balling bait underneath birds, stop the boat, cut the engine, and cast metal slices or poppers into the melee — a running engine will push the school down.",
    "Chum with a block of frozen pilchards or cubed tuna; once fish are in the berley trail, free-spool a live yakka or pilchard back into the slick for a natural presentation.",
    "Set drag at roughly 30% of breaking strain when trolling for YFT — they run hard and deep and you need enough line on the reel to survive the initial burst.",
    "At depth, slow-pitch butterfly jigs in 150–300 g sizes fished on a parabolic rod will pick up fish that ignored surface presentations — wahoo and mahi-mahi often join in.",
  ],
  "kingfish-jigging": [
    "Read the current before you lower a jig — drift so the jig is working across current, not with it. Kingfish hold on the down-current edge of structure and ambush anything swung past.",
    "Speed jigging (fast, rhythmic lifts) triggers reaction strikes from active fish; slow-pitch (allowing the jig to flutter on the fall) outperforms when fish are lethargic or in cold water.",
    "Use at least 80 lb fluorocarbon leader of 1–1.5 m — YTK have extremely abrasive mouths and will saw through lighter leader on boulders and pylons.",
    "Target the bite window around current changes; kingfish move from deep structure to shallower reef edges to feed aggressively during water movement, then become lethargic at slack.",
    "Keep your jig weight heavy enough to stay nearly vertical under the boat — if the jig drifts behind you in the current, you lose contact and miss the strike; go heavier, not lighter.",
  ],
  "light-tackle-pelagics": [
    "Be on the water at first light — longtail tuna and Spanish mackerel feed on surface bait schools in low light and the action typically dies by 9 am on calm days.",
    "Cast hard-bodied bibless lures or metal slices into breaking fish, let them sink 1–2 seconds, then wind fast with the rod tip high to create a fleeing-bait action.",
    "Use a 30–40 cm wire trace (single-strand or 49-strand) for Spanish mackerel — their razor teeth will cut through any mono or fluoro leader on the first run.",
    "On calm days, look for nervous bait patches (surface rippling without wind) and birds hovering low — these indicate fish pushing bait from below.",
    "If fish go off the surface bite, switch to a small chrome or pink metal jig and work it mid-water with fast lifts — longtail tuna in particular will keep chasing even when not visibly feeding.",
  ],
  "deep-dropping": [
    "Point your rod tip straight down while drifting — maintaining near-vertical line angle is critical so you can feel bites through 200–400 m of line with a spool full of braid.",
    "Rig multiple circle hooks (5/0–8/0) on a multi-dropper rig with chemical glow sticks — deep species rely on low-light attractants far more than colour at depth.",
    "An electric reel makes the 400 m+ wind-backs manageable; manually cranking a heavy multi-hook rig with multiple fish attached is exhausting and damages the fish.",
    "Blue-eye trevalla and hapuku live close to hard bottom structure at 200–500 m — use the sounder to mark the precise depth where the reef kicks up and sit just above it.",
    "Use large squid or octopus baits in preference to fish fillets — they stay on the hook better in strong deep-water currents and are harder for small nuisance fish to strip.",
  ],
  "coral-trout-reef": [
    "Fish the first two hours of the run-in tide — coral trout move off the bottom onto reef edges and coral heads to ambush baitfish as water rises and improves clarity.",
    "Drop a whole dead pilchard, squid, or small fish bait to the base of a coral bommie and hold the rod firmly — coral trout hit hard and immediately bolt back into the coral to bust you off.",
    "Use a 60–80 lb fluorocarbon leader of at least 1.5 m and a robust paternoster or running sinker rig — the coral trout's habitat is rocky, abrasive, and unforgiving on light gear.",
    "Don't spend more than five minutes on any one spot if there are no bites — coral trout are opportunistic but localised; covering ground finds more fish than waiting.",
    "Red Emperor and coral trout share similar habitat; switching to a lightly weighted live bait (small hussar or fusilier) will selectively interest bigger Emperor specimens.",
  ],
  "snapper-bottom-bashing": [
    "Berley is the single biggest edge in snapper fishing — a slow-dissolving block of mixed pilchards, bread, and tuna oil creates a scent trail that draws fish from a wide area.",
    "Use a running sinker rig on 30–40 lb fluorocarbon leader: the sinker sits on the bottom while the bait (whole or half pilchard, squid strip, or prawn) floats naturally in the berley trail.",
    "Night fishing on a new or full moon produces the largest snapper — fish come off the bottom to feed more aggressively in the dark and their guard is lowered.",
    "Match your sinker weight to the current — you want just enough to hold the bottom without dragging. If you're blowing out, wind back slowly and re-present rather than going heavier.",
    "Whole fresh squid on a suicide hook is hard to beat as a big-snapper bait; freeze-dried or fresh baits outperform frozen alternatives and stay on the hook through multiple strikes.",
  ],
  "slow-pitch-jigging": [
    "Use a dedicated slow-pitch rod (PE 1.5–3) that loads during the stroke and unloads on the fall — the rod spring, not the angler's effort, imparts the flutter action to the jig.",
    "Match jig weight to depth: roughly 1 g per metre is a starting guide. At 150 m use 150 g; increase until the jig drops nearly vertically beneath the boat.",
    "The strike usually comes on the fall after the stroke, not at the top of the lift — stay alert and maintain semi-taut line during the descent so you can feel the tick of a take.",
    "Rotate jig colours and shapes after 15–20 minutes without a strike; blue-eye trevalla respond well to pink and purple; snapper and nannygai often prefer red/orange or silver.",
    "Anchor or drift slowly — if you're drifting fast in current, your jig is planing behind the boat and not working correctly. Adjust weight or use a drogue to slow drift speed.",
  ],
  "wa-demersal-reef": [
    "Western Australia's demersal closures vary by zone and season — check the current DPIRD rules for bag limits, size limits, and closed seasons before your trip.",
    "Dhufish respond well to fresh or frozen squid presented on a paternoster rig in 20–80 m. Fish the reef edge where hard bottom transitions to sand for the highest density.",
    "Baldchin groper are most active in shallower water (15–40 m) around limestone and coral reef — use a whole pilchard or small live bait and present it slightly off the bottom.",
    "Position the boat upcurrent from the reef structure and drift baits back into the zone — anchoring directly over reef disturbs fish; drifting presents baits more naturally.",
    "The burley-trail approach works for WA demersals just as it does for eastern snapper — minced pilchard mixed with tuna oil weighted in a mesh bag and hung below the boat concentrates fish.",
  ],
  "barramundi-estuary": [
    "Fish the last two hours of a run-out tide around mangrove drains and creek mouths — barra sit in the fast water waiting for prawns and baitfish to be flushed through.",
    "Cast to within 30 cm of mangrove roots and retrieve the lure tight to structure — barramundi sit in the shadows of prop roots and won't move far to chase a lure in open water.",
    "Work surface lures (pencil poppers, walk-the-dog sticks) at dusk and dawn when barra are actively feeding on the surface; switch to sub-surface jerkbaits or vibes during the day.",
    "Mangrove jack occupy the same habitat as barra — use heavier leader (60–80 lb) and run-and-gun tactics to get fish out of cover before they wrap you around a root.",
    "Seasonally, barra move to deeper holes in cold water (below 24 °C) and become lethargic; slow presentations of lures or live bait near structure outperform fast retrieves in winter.",
  ],
  "flathead-soft-plastics": [
    "Flathead are ambush predators; they lie motionless on sandy or muddy bottoms waiting for prey to approach — let your soft plastic sink to the bottom and drag it slowly, pausing often.",
    "The drag-and-hop retrieve works best: lift the rod tip to drag the plastic along the bottom, let it settle, then hop again. Flathead usually strike when the lure falls.",
    "Fish shallow sand flats on an incoming tide during low-light periods (dawn and dusk) — flathead move from deeper channels onto the flats to feed as water covers them.",
    "Scented soft plastics (Squidgy, Z-Man, or Gulp) significantly outperform unscented plastics for flathead; fish hold the bait longer, giving you time to feel and set the hook.",
    "Use a 20–30 lb fluorocarbon leader — flathead have rough mouths and sharp gill plates that abrade lighter leaders, especially when you're lifting a large lizard from the bottom.",
  ],
  "bream-estuary": [
    "Bream are notoriously leader-shy in clear water — drop to 6–8 lb fluorocarbon leader and use the smallest hook that will hold your bait. Presentation beats power.",
    "Fish the edges of oyster leases, rock walls, and jetty pylons — bream graze for crustaceans and molluscs attached to hard structures and rarely sit in open water.",
    "Use fresh or live nippers (bass yabbies), prawns, or bloodworms on a size 6–8 suicide hook with a running sinker; these natural baits consistently outperform plastics for whiting and bream.",
    "Match the drift speed on an outgoing tide — set up above an oyster lease and let the current carry your bait through the zone at natural speed rather than casting and retrieving.",
    "Don't overlook dawn sessions on a low light incoming tide — large bream push into very shallow (knee-deep) water to feed on the flat and are extremely catchable on lightly weighted plastics.",
  ],
  "mulloway-night": [
    "The new moon is your best mulloway calendar — low light triggers bolder feeding behaviour in large fish that are wary and nocturnal by nature.",
    "Use large live bait (yellowfin bream, mullet, or tailor) hooked lightly through the back, near a rock wall, jetty, or river channel where tidal flow funnels baitfish.",
    "Set a sensitive rod rest, open the bail arm, and leave a small amount of line free — mulloway are cautious and will drop a bait immediately if they feel resistance before swallowing.",
    "The two hours around a tide change (particularly the run-out at night) are prime mulloway windows; they move from deep midstream holes onto the edges of channels to intercept prey.",
    "Use 60–80 lb fluorocarbon leader of 1.5–2 m — large mulloway have rough mouths and will shake violently against rock structures; light leader will not survive this.",
  ],
  "squid-evening": [
    "The peak window for squid is dusk through the first two hours of night, particularly around jetty lights and weed beds in 1–5 m of water.",
    "Work EGI jigs on a slow sink-and-twitch presentation: cast, let the jig sink on a slack line, then two quick rod flicks followed by another sink. Avoid fast continuous retrieves.",
    "Match jig size to water depth: small jigs (2.0–2.5) for shallow clear water, larger jigs (3.0–4.0) for darker or deeper water. Natural translucent colours work in clear conditions.",
    "Squid are sensitive to line movement — use a long, light fluorocarbon leader (4–6 lb, 1.5–2 m) and avoid tight lines during the sink phase so the jig falls naturally.",
    "Look for dark ink stains on jetty decking — this signals squid feeding activity in the area. Don't move away from a productive zone; re-cast to the same depth and structure.",
  ],
  "beach-casting-surf": [
    "Focus on gutters — the deeper water channels that run parallel to shore between two sand bars. Tailor, salmon, and mulloway congregate in these features, especially at dawn and after storms.",
    "After a storm has churned up the water and washed worms and crabs out of the sand, the surf fishing is often outstanding — discoloured water is productive, not a hindrance.",
    "Use a running sinker rig with a star sinker (to grip sand in current) and whole or pilchard flesh bait for mulloway; ganged hooks with a whole pilchard are the go for tailor and salmon.",
    "Cast beyond the break — tailor and salmon often patrol the back edge of the breaker zone. A long surf rod (3.6–4 m) and braided main line maximise casting distance from the beach.",
    "Tailor and salmon school, so when you get one, stay put and work the gutter until the school moves on. Salmon in particular run in tight groups and the bite window can be short.",
  ],
  "trout-fly-fishing": [
    "Hatch-matching is the foundation of trout fly fishing — observe what insects are hatching or falling onto the water before selecting your fly. Look under rocks for nymphs.",
    "For upstream nymphing, cast above a likely holding lie (behind rocks, undercut banks, pool tails) and let the nymph drift naturally with the current on a tight-but-relaxed line.",
    "The evening rise is the most productive dry-fly period — trout sip insects emerging from the surface film. Move quietly, approach from downstream, and cast upstream and across.",
    "Trout in heavily fished streams are line-shy — use the lightest tippet that the fish and structure allow (4X–6X) and keep your leader fully degreased so it sinks through the surface film.",
    "In cold water (below 10 °C), trout become lethargic and drop into deep slow pools. Switch to a slow-sinking or weighted nymph and fish it very slowly near the bottom.",
  ],
  "murray-cod-lure": [
    "Murray cod are structure lovers — position your cast to land a large lure (surface lure or deep-diving hard body) within 50 cm of an undercut bank, fallen timber, or bridge pylon.",
    "Surface lures fished at night or dusk produce the most aggressive strikes; cod will travel several metres to attack a large noisy surface lure in low-light conditions.",
    "In cold water (below 15 °C), cod slow down dramatically — switch from large fast-moving lures to a slow-rolled 5-inch paddle-tail swimbait retrieved at half speed with pauses.",
    "Use a strong, abrasion-resistant leader (40–60 lb fluorocarbon or equivalent mono) — cod engulf lures and their hard tooth plates and gill rakers are extremely abrasive on gear.",
    "Large golden perch occupy the same habitat as cod — scale up to 100 mm+ lures to select for cod over perch if you're specifically targeting trophy-sized fish.",
  ],
  "bass-impoundment": [
    "During the warmer months (spring–autumn), Australian bass and golden perch school at mid-water depth beneath surface-visible bait — find them with your sounder and drop a blade vibe to the depth of the school.",
    "Dawn topwater fishing on impoundments in summer is highly effective — bass push to the shallow timber edges at first light and smash surface lures before retreating to deeper water as the sun rises.",
    "Cold fronts push bass into deeper water and make them unresponsive to fast presentations; slow down and fish blade vibes or weighted grubs right on the bottom near submerged timber.",
    "Target the backs of creek arms in the impoundment after rain — fresh water inflow concentrates baitfish and bass congregate at the inflow zones to intercept flushed prey.",
    "Golden perch prefer slightly deeper water than bass and respond particularly well to blade vibes and small bibless lures fished at mid-depth over submerged structure.",
  ],
  "nz-blue-cod": [
    "Blue cod are territorial and highly aggressive — drop a bait or jig directly onto a rocky pinnacle or reef, and strikes often come within seconds. If no bite in two minutes, move on.",
    "Fresh squid or a live-bait combination jig/bait combo outperforms dead baits in the cold, clear water of southern New Zealand. Keepnet your first blue cod and use it as bait for tarakihi.",
    "Blue cod congregate on shallow rocky reefs (10–50 m) around the South Island's sounds and coasts — accurate anchoring or drift positioning over the pinnacle is more important than tackle.",
    "In Fiordland and the Sounds, combine bait fishing with a 50–80 g slow-pitch or butterfly jig to cover the water column — cod and tarakihi both hit jigs enthusiastically in cold water.",
    "Watch New Zealand's blue cod size limits and bag limits closely — regulations vary by region and are strictly enforced. Measure every fish before placing it in the bin.",
  ],
  "nz-snapper": [
    "Dawn is the prime snapper window in most New Zealand harbours and bays — fish are active in shallow water before light increases and they retreat to deeper structure.",
    "Create a berley cloud by filling a mesh bag with minced pilchards, bread crumbs, and tuna oil and hanging it off the back of the boat; free-line a fresh bait back into the slick.",
    "Flasher rigs (paternoster with mylar flies above the baited hook) add visual attraction in tidal current and significantly improve catch rates over a plain hook-and-bait approach.",
    "New Zealand snapper are deep, reliable fighters — use 15–20 lb fluorocarbon leader and at minimum a 4000-size reel with a smooth drag. Large fish (3+ kg) are common in the Hauraki Gulf.",
    "On the incoming tide, snapper push onto shallow reefs and rocky edges; on the outflow they retreat. Move with the tide rather than staying anchored in a spot that goes dead on the change.",
  ],
  "bonefish-flats": [
    "Approach bonefish tailing on the flats by wading or poling the boat extremely slowly and quietly — a single loud splash or thump on the hull will flush every fish within 50 metres.",
    "Lead a cruising fish by casting 2–3 metres ahead of its path; the fly or lure should land softly and sink just enough to intercept the fish at eye level as it moves forward.",
    "Use a 9 ft leader tapering to 10–12 lb fluorocarbon tippet — bonefish have excellent eyesight and a heavy tippet on a clear flat will spook fish before they reach the fly.",
    "The 'one strip, pause, two strips' retrieve mimics a fleeing crab or shrimp and is the most reliable pattern; if a fish follows but doesn't eat, stop the fly completely and let it sink.",
    "Fish the incoming tide as it covers the flat — bonefish move onto newly flooded ground to feed and are at their most aggressive in the first hour of rising water over the sand.",
  ],
  "southern-bluefin-tuna": [
    "SBT in southern Australian waters are most reliably found on the 200 m drop-off and over deep seamounts — troll feathers and skirted lures at 7–9 knots until you locate the school, then stop and chunk.",
    "Once the boat is stopped and fish are responding to a frozen berley slick of chunked tuna and pilchards, switch to live slimy mackerel or yellowtail free-lined back in the current for the best bite.",
    "SBT are extremely drag-setting sensitive — pre-set your drags at exactly 25–30% of breaking strain before the bite and do NOT touch the lever during the fight. Burned-out clutches end trips.",
    "Wear a harness for fish over 30 kg; pumping a 60 kg+ SBT by hand without one will exhaust you in 10 minutes. Use the boat to back down on large fish and recover line efficiently.",
    "In cold water (Bass Strait, SA), SBT hold deep — slow trolling a skirted lure on a downrigger to 40–60 m often outproduces surface trolling when the fish are sounding on sounder marks.",
  ],
  "wahoo-speed-trolling": [
    "Troll high-speed skirts, konaheads, or jet-headed lures at 14–18 knots — wahoo are specifically triggered by fast-moving prey and will ignore lures worked at standard trolling speeds.",
    "Rig every lure with a short single-strand wire trace (49-strand or cable, 60–80 lb, 30 cm) — wahoo teeth will cut through any mono or fluoro leader on the first pass regardless of breaking strain.",
    "Target FADs, current edges, and seamounts — wahoo congregate around structure that concentrates baitfish and can be located by watching for surface commotion or birds diving on a fast-moving school.",
    "Keep the lure spread tight (no more than 20 m back) at high speed — at 15+ knots a lure placed 40 m back is creating excessive surface turbulence and will be ignored while the short rigger lure gets struck.",
    "After a wahoo strike, avoid back-winding — simply hold the rod firm and let the drag do the work. Their initial run at full speed is short; the fish tires quickly and the fight is largely over in under five minutes.",
  ],
  "cobia-casting": [
    "Cobia are curious fish that follow large marine animals — scan around manta rays, whale sharks, turtles, and even large schools of bait for cobia cruising alongside. A lure dropped in front of a following cobia is almost always eaten.",
    "Large soft plastic jigs (5–8 inch paddle tails or Zman Swimmerz) in white or chartreuse rigged on a 1/2 oz to 1 oz jig head are the most versatile cobia lure — work them at mid-depth with a slow lift-and-drop presentation.",
    "Cobia around channel markers and FADs can be sight-cast with a surface popper or stickbait — work the lure aggressively on top to draw the fish up from the shadow of the structure.",
    "Use 40–60 lb fluorocarbon leader of 1–1.5 m — cobia have rough mouths and powerful runs, and they will make for any nearby structure or the anchor rope when hooked.",
    "When cobia are following a hooked fish (a common behaviour), have a rod rigged and ready to cast immediately. The following fish can be cast to at boatside before it dives back down.",
  ],
  "samson-fish-jigging": [
    "Samson fish and amberjack are brutally powerful — use PE 4–6 braid, a 150–200 lb fluorocarbon leader, and a heavy jigging rod rated to 300 g. Light tackle will not survive the first run into the reef.",
    "Speed jig by winding as fast as you can — samson fish in particular respond to very fast, erratic presentations. Work a 150–250 g assist-rigged knife jig from bottom to mid-water on repeated fast lifts.",
    "Position the boat uptide of the pinnacle and drift the jig through the strike zone — the uptide side of a rocky peak is where samson fish ambush baitfish carried over the top by current.",
    "If speed jigging produces no result, switch to a slow-pitch butterfly jig worked on the fall — larger fish sometimes prefer the flutter action, especially when the current slackens at tide change.",
    "Set your drag extremely tight before the lure hits the bottom — you have about one second after a samson fish strikes before it reaches the reef. A loose drag means a bust-off every time.",
  ],
  "spangled-emperor-bashing": [
    "Spangled emperor are primarily a dawn and dusk feeder — plan your drift to have baits in the water as the sky turns pink and fish up until the sun gets high, then return for the evening session.",
    "Use a whole fresh squid head or a small live fusiler/yellowtail as your primary bait — spangled emperor are selective and whole natural baits on a light running sinker rig outperform cut baits.",
    "Work reefs in 10–40 m over coral bommies and rubble patches — spangled emperor stay close to structure during the day and move onto surrounding sand and rubble to feed at low light.",
    "After catching and keeping a fish, drop it straight back — spangled emperor school and where you catch one, there will be more. Stay on a productive drift and make multiple passes over the same ground.",
    "On tropical tides, focus on the last of the run-out — the concentrated current over the reef edge funnels baitfish and emperor take up feeding stations at the edges of the flow.",
  ],
  "southern-reef-mixed": [
    "Target depths of 80–150 m over hard rocky bottom in southern waters — striped trumpeter prefer cold, rocky structure and are rarely found over sand or soft substrate.",
    "Fresh squid (whole or cut into long strips) is the universal bait for southern reef species — it stays on the hook better than fish flesh in strong currents and the scent column reaches fish at distance.",
    "Use a two-hook paternoster rig with 60 lb fluorocarbon snoods — this allows you to present two different baits simultaneously and increases the chance of a double hook-up, which is common over productive ground.",
    "Striped trumpeter are powerful pullers and have hard mouths — strike firmly once, then apply constant pressure. They don't make long runs but pump hard against the bottom, so use a stiff rod to keep them moving up.",
    "Drift slowly over the reef rather than anchoring — this covers more ground, prevents too much line angle in current, and allows the bait to be presented naturally at different depths as you move.",
  ],
  "ningaloo-reef": [
    "Ningaloo's outer reef produces the best reef fishing — book a charter that accesses the deeper outer reef edges (20–60 m) rather than the shallow lagoon, which has strict catch limits.",
    "Coral trout at Ningaloo are found on the coral heads and bommies in 10–30 m; use a whole pilchard or small live bait dropped to the base of coral structure and hold firm when you feel the tap.",
    "Check Western Australian demersal fishing rules carefully before fishing Ningaloo — there are closed seasons, reef-specific bag limits, and GPS-boundary closures that apply to this area.",
    "Rankin cod are a WA reef speciality and prefer slightly deeper, rocky structure at 30–80 m; they respond well to a slow-falling soft plastic fished on a heavy jig head along the reef edge.",
    "Crystal-clear water at Ningaloo means fish can see your boat — use a longer leader (1.5–2 m) of at least 40 lb fluoro and keep noise and vibration to a minimum when fishing shallow ground.",
  ],
  "nz-hapuku-deep": [
    "Target rocky pinnacles and cliff faces that rise steeply from deep water (150–400 m) — hapuku sit tight to vertical structure and a bait drifted away from the face will be ignored.",
    "Fresh or lightly frozen squid is the go-to hapuku bait; cut it into large strips (10–15 cm) or fish a whole small squid on a large circle hook (8/0–10/0) with minimal additional weight.",
    "Use an electric reel for depths below 200 m — manually winding up a heavy multi-hook rig from 300 m multiple times in a session will exhaust you and limit the number of drops you can make.",
    "John Dory and blue cod regularly share the same rocky structure at shallower depths (30–80 m) — start shallow and work deeper until you locate the hapuku layer, fishing blue cod as you go.",
    "Set your rod in a holder during the soak and watch for the line to tick or pull sideways — hapuku rarely make aggressive strikes. A firm sweep of the rod is all that is needed to set a circle hook.",
  ],
  "gummy-shark-fishing": [
    "Gummy shark are most active on a run-out tide at night — set up at least an hour before the tide change to allow your berley trail to establish and fish to move in from down-current.",
    "Fresh squid tube (not frozen), whole pilchard, or fresh tuna flesh are the top gummy baits; fresh makes a significant difference over frozen or salted baits in the cold, clear water of Port Phillip Bay and Westernport.",
    "Use a 7/0–9/0 circle hook on 60–80 lb nylon or fluorocarbon leader with a running ball sinker — gummy sharks have tough, plate-like teeth and will saw through wire-free fluoro on a long fight.",
    "Gummies move into very shallow water (1.5–3 m) to feed in tidal bays; don't assume you need deep water. Some of the best Victoria fishing is in less than 2 m over clean sand in enclosed bays.",
    "When a gummy runs with the bait, reel down to the fish before sweeping the rod rather than striking immediately — they pick up baits and move off slowly, and a premature strike pulls the hook from their soft grip.",
  ],
  "kingfish-livebait": [
    "The best live baits for kingfish are slimy mackerel (yellowtail), squid, and large yakkas — catch your own fresh livies on the day using small sabiki rigs over schools of baitfish before heading to the reef.",
    "Hook a livebait through the nose with a 5/0–7/0 hook and allow it to swim freely on a controlled-depth drift above the reef — kingfish almost always hit on the way down when the bait is panicking.",
    "Set the drag lighter than you think is necessary — kingfish on livebait run faster and harder than when jig-hooked, and a tight drag on the first run will result in a bust-off or pulled hook on 8 out of 10 fish.",
    "When livies are scarce, a whole freshly caught squid hooked through the mantle and allowed to drift on a slow retrieve is the next best thing and often produces bigger fish than live fish baits.",
    "Anchor or slow-drift over the top of a known reef mark at first light and drop the livebait straight down — kingfish patrol the top of pinnacles in the early morning and a bait presented at the right depth will be taken immediately.",
  ],
  "rock-fishing": [
    "Always wear a life jacket on any exposed platform — rock fishing is one of the highest-risk recreational activities in Australia and the consequences of a rogue wave are severe. Check the swell forecast and never turn your back on the ocean.",
    "Black drummer (also called luderick or greenfish) feed almost exclusively on green algae — fish a long float rig with fresh green cabbage weed (harvested from rocks in the area) on a small hook in the surging white water.",
    "The key to drummer is finding the correct depth on the float — adjust so the weed is just off the bottom in the surge zone. Too deep and it snags, too shallow and the fish ignore it.",
    "Australian salmon and tailor hit metal lures cast into breaking white water — stand on an elevated, safe platform and cast a chrome or blue pilchard-pattern slug into the gutter and retrieve at medium speed through the foam.",
    "Rock fishing spots produce best when a medium ocean swell is running — not glassy calm (fish move offshore) and not huge surf (too dangerous and fish move to deeper water). A 1.5–2 m swell with light wind is the ideal.",
  ],
  "milkfish-fly": [
    "Milkfish feed on surface algae and plankton in foam lines and current scum — locate feeding fish by looking for large, slow-moving tails and dorsal fins cutting through foam on the surface of the tide line.",
    "The fly must land in the scum directly in front of the fish and must look exactly like the surrounding foam particles — tiny (size 6–8) sparse white or cream flies tied on short-shank hooks to mimic algal mats work best.",
    "Milkfish have extremely soft mouths; use a light tippet (10–12 lb) and a rod that loads deeply to absorb shock, and set the hook with a slow, steady strip-strike rather than a lifting rod strike.",
    "After the hook-up, do not palm the reel — milkfish initial runs exceed 200 m. Clear all loose fly line from the deck and get on the reel immediately, letting the fish run against the disc drag.",
    "Christmas Island's milkfish are best targeted on an incoming tide when fish stack up on the current edges — guide services know the specific scum-line locations, and first-timers should book a guide for at least the first day.",
  ],
  "black-jewfish-estuary": [
    "Large black jewfish (up to 1 m+ in tropical waters) are primarily nocturnal — fish a run-out tide in complete darkness for the best results, positioning near the exit of a tidal creek or mangrove drain.",
    "Large live mullet (25–35 cm) hooked lightly through the back behind the dorsal fin and allowed to swim freely in the current on a running sinker rig is the single most effective approach for trophy black jewfish.",
    "Black jewfish produce a loud 'drumming' sound that can be heard through the hull — if you can hear drumming, fish are actively feeding in the area. Drop a bait immediately and hold on.",
    "Fish near deep bends in rivers and tidal channels where the current sweeps baitfish into a slow back-eddy — large jewfish hold in the slack water and intercept prey brought past by the current.",
    "Use 80–100 lb fluorocarbon leader on a 10/0 circle hook — these fish have large, abrasive mouths and make powerful runs toward timber and mangrove roots. Lighter gear will not survive a quality fish in structure.",
  ],
  "threadfin-salmon": [
    "Threadfin salmon are a tidal-current feeder — fish the last two hours of the run-out tide when dirty, prawn-laden water pours out of creek mouths and channels into the main river.",
    "Large paddle-tail soft plastics (5–7 inch) in natural prawn or mullet colours rigged on a 1/2 oz to 3/4 oz jig head are the most effective threadfin lure; work them slowly through the tidal outflow at mid-depth.",
    "Threadfin salmon have an exceptionally delicate touch — when you feel a 'tap-tap' pause and allow the fish a second before winding down and sweeping. They engulf baits sideways and premature strikes pull lures out of their mouth.",
    "Threadfin share tidal drains with barramundi — use 60–80 lb fluorocarbon leader so that you are equally prepared for either species. Both will make runs for mangrove roots on the strike.",
    "After rain and freshwater runoff, threadfin stack up near estuarine mixing zones where fresh and salt water meet — the fresh water pushes prawns downstream and the fish are waiting at the boundary.",
  ],
  "king-george-whiting-sa": [
    "King George whiting feed primarily on nippers (bass yabbies), pippis, and bluebait over clean sandy ground with seagrass coverage — match the local bait and your catch rate will improve dramatically.",
    "Pump nippers from low-tide sandbanks with a yabby pump in the area you plan to fish — fresh, locally caught nippers are consistently the most effective KGW bait in SA waters.",
    "Use a size 4–6 long-shank hook on a 6–8 lb fluorocarbon leader with a running ball sinker — KGW have small mouths and are extremely leader-shy in the clear water of SA's gulfs.",
    "Fish the first two hours of the incoming tide over shallow (1–4 m) seagrass beds — KGW move onto the flats to feed as water covers them and are most active during this period.",
    "Coffin Bay and the Yorke Peninsula are SA's premier KGW destinations; hire a local guide or charter for the first trip if you're unfamiliar with the areas, as finding the right sand over seagrass combinations is the key to consistent catches.",
  ],
  "mangrove-jack-lure": [
    "The strike zone for mangrove jack is the final 30 cm of the retrieve — fish hold under overhangs and between roots and only move a very short distance to intercept. Cast past the target and bring the lure through the zone, not to it.",
    "Use a fast, aggressive walk-the-dog retrieve with a stickbait on the surface during the top of the tide — jack will explode from beneath overhanging mangroves to engulf surface lures, providing unforgettable strikes.",
    "After a missed strike on a surface lure, immediately switch to a sub-surface hard body or vibe and work it past the same piece of structure — a fired-up jack will hit again within seconds on the follow-up cast.",
    "Use 40–60 lb fluorocarbon leader of no more than 50 cm — longer leaders impede casting accuracy under overhangs, and with mangrove jack, accuracy matters far more than leader length.",
    "Fish the run-in tide at night in the warmer months (October–April) for the best jack activity — they move up into shallow tidal drains under darkness and are most aggressive on the flooding tide over mangrove root systems.",
  ],
  "saratoga-topwater": [
    "Saratoga are visual ambush hunters — work a walk-the-dog surface lure or a large frog pattern lure along the edges of lily pads, weed beds, and overhanging vegetation at a slow, deliberate pace.",
    "The strike is violent and often comes when the lure pauses — allow the surface lure to sit for two full seconds after every two or three twitches. This hesitation frequently triggers the bite.",
    "Saratoga in shallow impoundments (Tinaroo, Borumba, Monduran) are sight-fished on calm mornings — polarised glasses allow you to spot the large, bronze-scaled fish cruising just below the surface and cast precisely to them.",
    "Use a medium-heavy rod with a baitcaster reel and 20–30 lb braid — saratoga make spectacular leaps after being hooked and a low-stretch braid keeps the hooks buried through the acrobatics.",
    "Timing is critical — dawn sessions in summer (October–March) produce the most surface activity before the sun gets high and saratoga retreat to deeper, shadier structure beneath timber and overhangs.",
  ],
  "redfin-impoundment": [
    "Locate redfin with your sounder by looking for dense balls of baitfish (often yellowtail scad) suspended over submerged timber or rocky points — redfin school tightly beneath the bait cloud.",
    "Drop a Tassie Devil lure, small blade vibe, or 2–3 inch paddle-tail plastic to the exact depth of the school and use a steady wind retrieve with no pauses — redfin are aggressive biters that respond to constant movement.",
    "In cold water (winter and early spring), redfin slow down and hold deeper; slow down your retrieve and allow the lure to sink fully between retrieves for two to three seconds before winding again.",
    "Redfin are a schooling species — when you catch one, cast immediately back to the same spot. The school typically stays put through multiple casts and you can catch a dozen fish from the same position.",
    "Use a light spinning outfit (2–4 kg rod, 2000–2500 reel, 6–8 lb braid) for maximum fun — redfin are not large but on appropriately scaled tackle they fight spiritedly and their aggressive double-hook takes are addictive.",
  ],
};
