export type Environment =
  | "offshore_boat"
  | "inshore_boat"
  | "estuary_boat"
  | "land_based"
  | "freshwater_boat"
  | "freshwater_shore";

export type TechniqueStyle =
  | "trolling"
  | "heavy"
  | "medium"
  | "light"
  | "finesse"
  | "fly";

export interface SpeciesGearSetup {
  slug: string;
  name: string;
  category: string;
  environments: Environment[];
  techniques: TechniqueStyle[];
  rod: string;
  reel: string;
  mainline: string;
  leader: string;
  lures?: string;
  hooks?: string;
  notes?: string;
}

export const ENVIRONMENT_LABELS: Record<Environment, string> = {
  offshore_boat: "Offshore Boat",
  inshore_boat: "Inshore Boat",
  estuary_boat: "Estuary Boat",
  land_based: "Land-Based",
  freshwater_boat: "Freshwater Boat",
  freshwater_shore: "Freshwater Shore",
};

export const ENVIRONMENT_EMOJI: Record<Environment, string> = {
  offshore_boat: "⛵",
  inshore_boat: "🚤",
  estuary_boat: "🛶",
  land_based: "🪨",
  freshwater_boat: "⛵",
  freshwater_shore: "🌿",
};

export const TECHNIQUE_LABELS: Record<TechniqueStyle, string> = {
  trolling: "Trolling",
  heavy: "Heavy",
  medium: "Medium",
  light: "Light",
  finesse: "Finesse",
  fly: "Fly",
};

export const TECHNIQUE_COLORS: Record<TechniqueStyle, string> = {
  trolling: "bg-purple-100 text-purple-700",
  heavy: "bg-red-100 text-red-700",
  medium: "bg-amber-100 text-amber-700",
  light: "bg-sky-100 text-sky-700",
  finesse: "bg-emerald-100 text-emerald-700",
  fly: "bg-teal-100 text-teal-700",
};

export const SPECIES_GEAR: SpeciesGearSetup[] = [
  // ── Pelagic ──────────────────────────────────────────────────────────────────
  {
    slug: "black-marlin",
    name: "Black Marlin",
    category: "pelagic",
    environments: ["offshore_boat"],
    techniques: ["trolling", "heavy"],
    rod: "80–130lb class heavy trolling rod (Shimano Tiagra, Penn Squall), stand-up or chair",
    reel: "Penn International 50VSW / Shimano Tiagra 50W",
    mainline: "80–130lb monofilament or 100lb braid",
    leader: "400lb single-strand wire or 600lb monofilament",
    lures: "Skirted trolling lures 9–14 inch (Pakula, Black Bart, RJ Lures) — black/red, purple/black, pink/white",
    notes: "IGFA 80lb class the gold standard; fighting chair essential for large fish",
  },
  {
    slug: "blue-marlin",
    name: "Blue Marlin",
    category: "pelagic",
    environments: ["offshore_boat"],
    techniques: ["trolling", "heavy"],
    rod: "50–80lb class trolling rod, 5.5–6ft",
    reel: "Penn International 30VS / Shimano Tiagra 30",
    mainline: "50–80lb monofilament or 80lb braid",
    leader: "200–400lb monofilament or single-strand wire",
    lures: "Skirted lures 6–12 inch, large bibbed minnows (Halco, Nomad DTX)",
  },
  {
    slug: "sailfish",
    name: "Sailfish",
    category: "pelagic",
    environments: ["offshore_boat"],
    techniques: ["trolling", "medium"],
    rod: "20–30lb class spin or light overhead, 6–7ft",
    reel: "Shimano Stella 8000 / Daiwa Saltiga 4500",
    mainline: "20–30lb braid (PE2–3)",
    leader: "60–80lb fluorocarbon",
    lures: "Small skirted lures 4–7 inch, live bait (garfish, mullet), small bibbed minnows",
  },
  {
    slug: "yellowfin-tuna",
    name: "Yellowfin Tuna",
    category: "pelagic",
    environments: ["offshore_boat"],
    techniques: ["trolling", "heavy", "medium"],
    rod: "30–80lb class trolling or 20–40lb spin, 6–7ft",
    reel: "Penn International 20T for trolling; Shimano Stella 8000–14000 for spinning",
    mainline: "50–80lb braid (PE4–6)",
    leader: "60–100lb fluorocarbon",
    lures: "Skirted lures 6–10 inch, metal jigs 80–250g, poppers 80–150g, bibbed minnows",
  },
  {
    slug: "longtail-tuna",
    name: "Longtail Tuna",
    category: "pelagic",
    environments: ["inshore_boat", "offshore_boat"],
    techniques: ["medium", "light"],
    rod: "20–30lb spinning, 7ft",
    reel: "Shimano Stella / Stradic 5000–8000",
    mainline: "20–30lb braid (PE2)",
    leader: "30–50lb fluorocarbon",
    lures: "Metal slugs 20–60g, cup-face poppers 40–80g, bibbed minnows 80–110mm",
  },
  {
    slug: "spanish-mackerel",
    name: "Spanish Mackerel",
    category: "pelagic",
    environments: ["inshore_boat", "offshore_boat"],
    techniques: ["trolling", "medium"],
    rod: "20–40lb spin or overhead, 6–7ft",
    reel: "Shimano Stradic 5000–8000 or Penn Squall 30",
    mainline: "20–40lb braid",
    leader: "49-strand 30kg wire (preferred) or 60–80lb fluorocarbon",
    lures: "Trolled hard bodies 10–15cm, Nomad DTX, chrome lures, live bait (yakkas)",
    notes: "Wire trace essential — mackerel razor teeth cut through mono instantly",
  },
  {
    slug: "wahoo",
    name: "Wahoo",
    category: "pelagic",
    environments: ["offshore_boat"],
    techniques: ["trolling", "medium"],
    rod: "30–50lb trolling or heavy spin, 6ft",
    reel: "Penn Squall 30 / Shimano Tyrnos 20",
    mainline: "40–60lb braid",
    leader: "100–150lb fluorocarbon or single-strand wire",
    lures: "High-speed konas, small skirted lures (6–9 inch), Rapala trolling minnows — bright/chrome",
    notes: "Troll at 10–14 knots; wire leader essential to stop bite-offs",
  },
  {
    slug: "mahi-mahi",
    name: "Mahi-Mahi",
    category: "pelagic",
    environments: ["offshore_boat"],
    techniques: ["medium", "light"],
    rod: "15–30lb spinning, 7ft",
    reel: "Shimano Stella / Stradic 4000–6000",
    mainline: "20–30lb braid (PE2)",
    leader: "30–50lb fluorocarbon",
    lures: "Small skirted lures, squid skirts, metal jigs 20–60g, cube poppers 60–80g",
    notes: "Keep school at the boat by leaving one hooked fish in the water",
  },
  {
    slug: "southern-bluefin-tuna",
    name: "Southern Bluefin Tuna",
    category: "pelagic",
    environments: ["offshore_boat"],
    techniques: ["trolling", "heavy", "medium"],
    rod: "30–80lb class trolling or spinning, 5.5–7ft",
    reel: "Penn International 20T / Shimano Tiagra 20 for trolling; Stella 14000 for jigging",
    mainline: "50–80lb braid (PE4–6)",
    leader: "80–130lb fluorocarbon",
    lures: "Trolled minnows 18–25cm, skirted lures, metal jigs 150–300g",
    notes: "Cold-water blues; Portland (VIC) and St Helens (TAS) hot spots",
  },

  // ── Inshore ───────────────────────────────────────────────────────────────────
  {
    slug: "yellowtail-kingfish",
    name: "Yellowtail Kingfish",
    category: "inshore",
    environments: ["inshore_boat", "land_based"],
    techniques: ["heavy", "medium"],
    rod: "40–80lb popper/jig rod (Evo, Ripple Fisher), 7–8ft; or 30–50lb jigging rod",
    reel: "Shimano Stella / Saltiga 10000–14000; Ocea Jigger 2000HG for jigging",
    mainline: "60–80lb braid (PE5–6)",
    leader: "60–100lb fluorocarbon, 1.5–3m",
    lures: "Cup-face poppers 100–150g, stickbaits 120–180g, slow-pitch jigs 80–200g, live yakkas",
    notes: "Set drag hard from first run — kings will dive into reef structure",
  },
  {
    slug: "giant-trevally",
    name: "Giant Trevally",
    category: "inshore",
    environments: ["inshore_boat", "land_based"],
    techniques: ["heavy"],
    rod: "Heavy popper rod 80–130lb (Evo GT series, Carpenter Lunaquest), 7–8ft",
    reel: "Shimano Saltiga / Daiwa Saltiga 8000–10000",
    mainline: "80–100lb braid (PE6–8)",
    leader: "100–150lb fluorocarbon",
    lures: "Cup-face poppers 120–200g (GT Raider, Halco), stickbaits 150–250g",
    notes: "Maximum drag pressure from the strike; GTs sprint for coral heads immediately",
  },
  {
    slug: "cobia",
    name: "Cobia",
    category: "inshore",
    environments: ["inshore_boat"],
    techniques: ["medium"],
    rod: "20–40lb spinning or baitcaster, 7ft medium-heavy",
    reel: "Shimano Stradic / Calcutta 4000–6000",
    mainline: "30–40lb braid",
    leader: "40–60lb fluorocarbon",
    lures: "Large soft plastics 5–7 inch, metal jigs 60–120g, live bait on 5/0–7/0 circle hooks",
  },
  {
    slug: "tailor",
    name: "Tailor",
    category: "inshore",
    environments: ["land_based", "inshore_boat"],
    techniques: ["light", "medium"],
    rod: "10–15lb spinning rod, 7–9ft (longer for beach surf)",
    reel: "Shimano Saragosa / Baitrunner 5000–6000",
    mainline: "10–20lb braid",
    leader: "20–30lb wire trace or 30lb fluorocarbon",
    lures: "Metal slugs 20–60g (Halco Twisty, Chrome Slice), Raider lures, small hard bodies",
    notes: "Wire trace recommended — tailor have razor-sharp teeth; night runs in autumn",
  },
  {
    slug: "australian-salmon",
    name: "Australian Salmon",
    category: "inshore",
    environments: ["land_based", "inshore_boat"],
    techniques: ["medium", "light"],
    rod: "10–20lb spinning, 8–10ft for beach surf casting",
    reel: "Shimano Saragosa / Biomaster 5000–8000",
    mainline: "15–20lb braid",
    leader: "20–30lb fluorocarbon",
    lures: "Metal slugs 20–50g, small vibes, chrome hard bodies, small poppers",
  },
  {
    slug: "gummy-shark",
    name: "Gummy Shark",
    category: "inshore",
    environments: ["land_based", "inshore_boat"],
    techniques: ["medium"],
    rod: "20–30lb surf or boat rod, 10–12ft (surf) or 6–7ft (boat)",
    reel: "Penn Battle / Penn Spinfisher 6000–8000",
    mainline: "30–50lb monofilament or braid",
    leader: "50–80lb monofilament with short wire trace",
    hooks: "4/0–8/0 circle hooks on 50lb wire trace, size to suit bait",
    lures: "Pilchards, squid tubes, tuna belly strips — bottom presented",
    notes: "Night fishing from beaches and bay flats; best Mar–Oct in VIC/TAS",
  },

  // ── Reef ──────────────────────────────────────────────────────────────────────
  {
    slug: "coral-trout",
    name: "Coral Trout",
    category: "reef",
    environments: ["inshore_boat"],
    techniques: ["light", "medium"],
    rod: "15–30lb spinning or baitcaster, 6–7ft, fast action",
    reel: "Shimano Curado K 150 / Calcutta 300",
    mainline: "20–30lb braid",
    leader: "20–40lb fluorocarbon",
    lures: "Soft plastics 3–5 inch (Zman, Keitech), live bait on 3/0–5/0 jigheads, hard bodies 70–100mm",
  },
  {
    slug: "red-emperor",
    name: "Red Emperor",
    category: "reef",
    environments: ["inshore_boat"],
    techniques: ["medium", "heavy"],
    rod: "30–50lb overhead or electric-assisted, 6–7ft parabolic",
    reel: "Shimano TLD 20 or Daiwa Tanacom Electric",
    mainline: "50–80lb braid",
    leader: "60–100lb fluorocarbon or monofilament, 1–2m",
    hooks: "6/0–10/0 heavy-gauge on double-hook paternoster rig",
    lures: "Whole pilchards, squid, cut fish presented on the bottom in 40–120m",
  },
  {
    slug: "nannygai",
    name: "Nannygai",
    category: "reef",
    environments: ["inshore_boat"],
    techniques: ["medium"],
    rod: "30–50lb overhead, 6–7ft",
    reel: "Shimano Electric or TLD 20/30",
    mainline: "50–80lb braid",
    leader: "50–80lb monofilament",
    hooks: "4/0–8/0 on paternoster rig, snoods 30–40cm",
    lures: "Pilchards, squid, soft plastics 4–6 inch in deep water (60–200m)",
  },
  {
    slug: "snapper",
    name: "Snapper",
    category: "reef",
    environments: ["inshore_boat", "land_based"],
    techniques: ["medium", "light"],
    rod: "15–30lb spinning or light overhead, 7ft",
    reel: "Shimano Stradic / Saragosa 4000–6000",
    mainline: "20–30lb braid",
    leader: "20–40lb fluorocarbon",
    lures: "Soft plastics 3–5 inch, knife jigs, slow-pitch jigs 40–120g, gulp prawns",
    hooks: "2/0–5/0 circle hooks with pilchards or squid for bait fishing",
  },
  {
    slug: "kingfish-qld",
    name: "Amberjack (Samson Fish)",
    category: "reef",
    environments: ["inshore_boat"],
    techniques: ["heavy", "medium"],
    rod: "50–80lb jig rod or heavy popper rod, 6–7ft",
    reel: "Shimano Ocea Jigger 2000HG / Stella SW 14000",
    mainline: "60–80lb braid (PE5–6)",
    leader: "80–100lb fluorocarbon",
    lures: "Slow-pitch jigs 150–300g, live bait on 6/0–8/0 circle hooks",
    notes: "Found over offshore reefs and seamounts in NSW and southern QLD",
  },
  {
    slug: "blue-eye-trevalla",
    name: "Blue-eye Trevalla",
    category: "reef",
    environments: ["offshore_boat"],
    techniques: ["heavy", "medium"],
    rod: "30–80lb parabolic slow-pitch rod (Shimano Ocea BB), 5.8–6.5ft",
    reel: "Shimano Ocea Jigger 2000PG / Daiwa Tanacom Electric for deep water",
    mainline: "65–80lb braid (PE4–5), thin diameter for depth",
    leader: "80–130lb fluorocarbon, 1.5–2m",
    lures: "Slow-pitch jigs 200–500g (Shimano Butterfly Flat Fall, Yamashita), deep jigging 150–300m",
    notes: "Southern continental shelf; VIC and TAS offshore reefs in 150–500m",
  },
  {
    slug: "striped-trumpeter",
    name: "Striped Trumpeter",
    category: "reef",
    environments: ["inshore_boat", "land_based"],
    techniques: ["medium"],
    rod: "15–30lb rock or boat rod, 8–12ft for rocks; 6–7ft for boat",
    reel: "Conventional spinning 4000–6000",
    mainline: "20–30lb monofilament or braid",
    leader: "30–40lb monofilament",
    hooks: "4/0–6/0 on paternoster rig",
    lures: "Pippi, crab, cuttlefish, mackerel strip — bottom presented over kelp reefs",
    notes: "TAS specialty; cold kelp-covered reefs, rock ledges, and offshore reefs",
  },

  // ── Estuary ───────────────────────────────────────────────────────────────────
  {
    slug: "barramundi",
    name: "Barramundi",
    category: "estuary",
    environments: ["estuary_boat", "freshwater_shore"],
    techniques: ["medium"],
    rod: "20–30lb baitcasting rod, 7–7.6ft, medium-heavy fast action",
    reel: "Daiwa Tatula SV / Shimano Curado DC 200",
    mainline: "20–40lb braid",
    leader: "30–50lb fluorocarbon, 30–60cm",
    lures: "Hard bodies 70–120mm (Rapala, Zerek), surface lures (Jackall Mikey), soft plastics 4–6 inch",
    notes: "Cast tight to structure; barra ambush from mangrove roots and submerged timber",
  },
  {
    slug: "mangrove-jack",
    name: "Mangrove Jack",
    category: "estuary",
    environments: ["estuary_boat"],
    techniques: ["medium"],
    rod: "15–30lb baitcasting rod, 7ft medium-heavy",
    reel: "Daiwa Tatula SV / Shimano Curado K 150",
    mainline: "20–30lb braid",
    leader: "30–50lb fluorocarbon (abrasion-resistant, jack will saw against structure)",
    lures: "Hard bodies 50–90mm, soft plastics 3–4 inch on 3/0–4/0 jigheads",
    notes: "Set drag tight immediately — jack will cut you off in timber within seconds",
  },
  {
    slug: "flathead",
    name: "Dusky Flathead",
    category: "estuary",
    environments: ["estuary_boat", "land_based"],
    techniques: ["light", "finesse"],
    rod: "1–3kg to 3–6kg spinning, 7ft, medium action",
    reel: "Shimano Stradic / Vanquish 2500–4000",
    mainline: "6–12lb braid (PE0.6–1)",
    leader: "8–15lb fluorocarbon",
    lures: "Paddle-tail soft plastics 3–5 inch (Zman, Gulp) on 1/6–1/4oz jigheads",
    notes: "Slow retrieve along bottom; flathead are ambush predators, stop-start works well",
  },
  {
    slug: "mulloway",
    name: "Mulloway",
    category: "estuary",
    environments: ["estuary_boat", "land_based"],
    techniques: ["medium"],
    rod: "15–30lb spinning, 7–8ft; 10–12ft surf rod for beach",
    reel: "Shimano Stradic / Saragosa 5000–6000",
    mainline: "20–30lb braid",
    leader: "30–50lb fluorocarbon",
    lures: "Large soft plastics 5–7 inch (Zman Streakz XL, Slug-Go), large bibbed divers 120–160mm",
    hooks: "Circle hooks 4/0–6/0 with live mullet or tailor for bait",
    notes: "Night fishing peak; deep holes, bridge pylons, and ocean beaches",
  },
  {
    slug: "bream",
    name: "Yellowfin Bream",
    category: "estuary",
    environments: ["estuary_boat", "land_based"],
    techniques: ["finesse", "light"],
    rod: "1–3kg to 2–4kg spinning, 7ft, light fast action",
    reel: "Shimano Vanquish / Daiwa Exist 2000–2500",
    mainline: "4–8lb braid (PE0.4–0.8)",
    leader: "4–8lb fluorocarbon",
    lures: "Small soft plastics 1.5–3 inch (Gulp Minnow, ZMan), hard bodies 40–60mm, micro blades",
    notes: "Bite-sized presentations; patience rewarded — bream inspect before committing",
  },
  {
    slug: "whiting",
    name: "Sand Whiting",
    category: "estuary",
    environments: ["estuary_boat", "land_based"],
    techniques: ["finesse"],
    rod: "1–3kg spinning, 7ft, light flexible tip",
    reel: "Shimano Stradic CI4+ / Daiwa Legalis 2000–2500",
    mainline: "4–6lb braid (PE0.4)",
    leader: "4–6lb fluorocarbon, 50–80cm",
    hooks: "Size 4–8 long-shank hooks with bait, or 1/16oz jighead",
    lures: "Beach worms, nippers, yabbies, green prawn; Gulp Sandworm or small prawns on light jigheads",
  },
  {
    slug: "luderick",
    name: "Luderick (Blackfish)",
    category: "estuary",
    environments: ["land_based"],
    techniques: ["finesse"],
    rod: "Luderick float rod 10–14ft, light parabolic action (Daiwa Whisker)",
    reel: "Small spinning 2000–3000 or centre-pin reel",
    mainline: "4–8lb monofilament",
    leader: "3–4lb fluorocarbon tippet, 30–50cm",
    hooks: "Size 10–14 fine wire hooks (blackfish hooks)",
    lures: "Green weed (cabbage/sea lettuce); float rig set 30–60cm above bottom",
    notes: "Tide-sensitive; fish incoming on rock ledges and rock walls; NSW specialty",
  },
  {
    slug: "jewfish",
    name: "Black Jewfish",
    category: "estuary",
    environments: ["estuary_boat"],
    techniques: ["medium", "heavy"],
    rod: "30–50lb overhead or spinning, 6–7ft",
    reel: "Shimano TLD 20–25 / Penn Squall 30",
    mainline: "40–60lb braid",
    leader: "60–80lb fluorocarbon",
    hooks: "7/0–10/0 circle hooks with swivel",
    lures: "Live mullet, live bream, whole pilchard (night fishing); large soft plastics 6–8 inch",
    notes: "Night fishing peaking around the full moon; FNQ estuaries, creek mouths",
  },

  // ── Freshwater ────────────────────────────────────────────────────────────────
  {
    slug: "murray-cod",
    name: "Murray Cod",
    category: "freshwater",
    environments: ["freshwater_boat", "freshwater_shore"],
    techniques: ["heavy", "medium"],
    rod: "20–50lb baitcasting, 7–8ft, medium-heavy to heavy power (custom AU cod rods, Daiwa Brute)",
    reel: "Abu Garcia Revo Beast / Daiwa Tatula Type-HD 300",
    mainline: "30–65lb braid",
    leader: "40–80lb fluorocarbon, 50–80cm",
    lures: "Large bibbed minnows 100–180mm (Jackall Gantarel, Murray Cod lures), paddle tails 6–10 inch, spinnerbaits 1–2oz, surface lures (Jackall Mikey, McCraw)",
    notes: "Snag-heavy snooker; use maximum drag and haul hard — cod are powerful and bolt for timber",
  },
  {
    slug: "golden-perch",
    name: "Golden Perch",
    category: "freshwater",
    environments: ["freshwater_boat", "freshwater_shore"],
    techniques: ["medium", "light"],
    rod: "8–15lb spinning or baitcasting, 6.5–7.5ft, medium action",
    reel: "Shimano Stradic 2500–4000 or small baitcaster (Calcutta 200)",
    mainline: "10–20lb braid",
    leader: "10–20lb fluorocarbon",
    lures: "Bibbed minnows 70–100mm, paddle tails 3–5 inch, vibes 12–25g",
  },
  {
    slug: "silver-perch",
    name: "Silver Perch",
    category: "freshwater",
    environments: ["freshwater_boat", "freshwater_shore"],
    techniques: ["light", "finesse"],
    rod: "4–8lb spinning, 6–7ft, light action",
    reel: "Shimano Stradic 2000–2500",
    mainline: "6–10lb braid (PE0.6)",
    leader: "6–10lb fluorocarbon",
    lures: "Small soft plastics 1.5–2.5 inch, small inline spinners, nano blades",
    hooks: "Size 6–10 for bait (yabbies, worms)",
  },
  {
    slug: "australian-bass",
    name: "Australian Bass",
    category: "freshwater",
    environments: ["freshwater_shore", "freshwater_boat"],
    techniques: ["light", "finesse", "fly"],
    rod: "3–6kg spinning 7ft or #5–7 fly rod 9ft (medium-fast)",
    reel: "Shimano Stradic 2500 for spin; Orvis Clearwater / Sage Spectrum for fly",
    mainline: "8–15lb braid or WF5–7F fly line",
    leader: "10–15lb fluorocarbon or 2x–4x fluorocarbon tippet for fly",
    lures: "Topwater lures (Heddon Torpedo, Jackall Chopo, Megabass Dog-X), vibes 9–18g, small blades, Clouser Minnows and Poppers (fly)",
    notes: "Winter spawn run into estuaries; spring-autumn surface action in rivers",
  },
  {
    slug: "brown-trout",
    name: "Brown Trout",
    category: "freshwater",
    environments: ["freshwater_shore", "freshwater_boat"],
    techniques: ["fly", "finesse"],
    rod: "#4–6 fly rod 9ft (medium-fast, Sage X or Orvis Helios) or ultralight 1–3kg spinning 7ft",
    reel: "Sage Spectrum C / Orvis Clearwater fly reel; or 1000–2000 spin reel",
    mainline: "WF5F fly line or 4–8lb monofilament for spinning",
    leader: "4x–6x fluorocarbon tippet (0.7–1.5lb for dry fly); 6–8lb fluoro for spin",
    lures: "Dry flies (Adams, Royal Wulff, Elk Hair Caddis), nymphs, Woolly Buggers; small hard bodies 40–60mm and Tassie Devils for spinning",
    notes: "Highly selective — presentation and drift are everything; spring and autumn peak on dry flies",
  },
  {
    slug: "rainbow-trout",
    name: "Rainbow Trout",
    category: "freshwater",
    environments: ["freshwater_shore", "freshwater_boat"],
    techniques: ["fly", "finesse", "light"],
    rod: "#4–6 fly rod 9ft or 1–3kg spinning 7ft",
    reel: "Fly reel with WF5F or spinning 1000–2500",
    mainline: "WF5F fly line or 4–8lb monofilament",
    leader: "4x–5x tippet for fly; 6–10lb fluorocarbon for spin",
    lures: "Inline spinners (Aglia, Tassie Devil), soft plastics 2–3 inch, dry flies, nymphs, PowerBait (stocked lakes)",
    notes: "Trolled flatlines with spinners or Tassie Devils deadly in Snowy Mountain lakes",
  },
  {
    slug: "redfin",
    name: "Redfin (European Perch)",
    category: "freshwater",
    environments: ["freshwater_shore", "freshwater_boat"],
    techniques: ["light", "finesse"],
    rod: "1–3kg spinning, 6–7ft, light action",
    reel: "Shimano Stradic / Sienna 2000–2500",
    mainline: "4–8lb braid",
    leader: "6–10lb fluorocarbon",
    lures: "Small soft plastics 1.5–3 inch, blade vibes 6–15g, inline spinners, small hardbodies 40–60mm",
    notes: "School fish — keep catching once you find them; aggressive in autumn",
  },
  {
    slug: "saratoga",
    name: "Saratoga",
    category: "freshwater",
    environments: ["freshwater_boat", "freshwater_shore"],
    techniques: ["light", "fly"],
    rod: "3–6kg baitcasting or 7ft spinning; or #7–9 fly rod for fly",
    reel: "Small baitcaster (Tatula SV) or 2500–3000 spinning; fly reel with WF7–9F line",
    mainline: "10–20lb braid or floating fly line",
    leader: "12–20lb fluorocarbon; or 1x–2x for fly",
    lures: "Surface lures (Jackall Pompadour, Jackall Mikey), soft plastics 3–4 inch, large fly poppers",
    notes: "Surface predator in tropical QLD impoundments; slow twitching action most effective",
  },
  {
    slug: "catfish",
    name: "Eel-tailed Catfish",
    category: "freshwater",
    environments: ["freshwater_shore", "freshwater_boat"],
    techniques: ["medium"],
    rod: "8–15lb spinning or overhead, 6–7ft, medium action",
    reel: "Shimano Stradic / Saragosa 2500–4000",
    mainline: "10–20lb monofilament or braid",
    leader: "15–20lb monofilament",
    hooks: "2/0–4/0 wide-gap hooks rigged with running sinker to bottom",
    lures: "Worms, scrub worms, yabbies, whole pilchards, dough bait presented on the bottom",
  },
  {
    slug: "ocean-trout",
    name: "Ocean Trout",
    category: "freshwater",
    environments: ["estuary_boat", "freshwater_shore"],
    techniques: ["fly", "light"],
    rod: "#6–8 fly rod 9ft (fast action) or 3–6kg spinning 7ft",
    reel: "Orvis Clearwater / Sage Spectrum C with WF6–8F line; or spinning 2500–4000",
    mainline: "WF6–8F fly line or 8–12lb braid",
    leader: "3x–5x tippet for fly; 8–15lb fluorocarbon for spin",
    lures: "Streamer flies (Clouser Minnow, Rabbit Strip), spoons 15–30g, soft plastics 3–4 inch; trolled hard bodies in bays",
    notes: "TAS specialty — sea-run rainbows; stalk in shallow estuaries on low tide flats",
  },
];

// Checklist items by environment (for the packing list section)
export const ENV_CHECKLIST: Record<
  string,
  { category: string; item: string; essential: boolean; notes?: string }[]
> = {
  offshore_boat: [
    { category: "Safety", item: "EPIRB registered with AMSA", essential: true },
    { category: "Safety", item: "VHF marine radio (fixed-mount)", essential: true },
    { category: "Safety", item: "Marine flare kit (within expiry)", essential: true },
    { category: "Safety", item: "Life jackets / PFDs for all crew (AMSA approved)", essential: true },
    { category: "Safety", item: "Satellite communicator (SPOT or Garmin inReach)", essential: false },
    { category: "Tackle", item: "Fighting chair or kidney harness", essential: false },
    { category: "Tackle", item: "Gaffs — 2 short + 1 flying gaff", essential: true },
    { category: "Tackle", item: "Release tool / dehooker for billfish", essential: false },
    { category: "Tackle", item: "Outrigger clips and rubber bands", essential: false },
    { category: "Tackle", item: "Large insulated fish box (100L+) with ice", essential: true },
    { category: "Food", item: "Motion sickness tablets (Kwells/Stugeron) — take night before", essential: false },
  ],
  inshore_boat: [
    { category: "Safety", item: "EPIRB or PLB registered with AMSA", essential: true },
    { category: "Safety", item: "VHF marine radio (handheld)", essential: true },
    { category: "Safety", item: "Marine flares (within expiry)", essential: true },
    { category: "Safety", item: "Life jackets / PFDs for all crew", essential: true },
    { category: "Tackle", item: "Bait board with knife and scissors", essential: true },
    { category: "Tackle", item: "Aerated live bait bucket", essential: false },
    { category: "Tackle", item: "Rubber mesh landing net", essential: true },
    { category: "Tackle", item: "Esky with ice for catch", essential: true },
  ],
  land_based: [
    { category: "Safety", item: "PLB registered with AMSA (remote rock fishing)", essential: true },
    { category: "Safety", item: "Rock fishing helmet and cleated boots", essential: false, notes: "Recommended for offshore rock platforms" },
    { category: "Safety", item: "Rock fishing life jacket (inflatable vest)", essential: true, notes: "Mandatory in many NSW rock platforms" },
    { category: "Tackle", item: "Rod holder / spike (surf fishing)", essential: false },
    { category: "Tackle", item: "Long-handle landing net or gaff", essential: false },
    { category: "Tackle", item: "Esky or bucket with seawater for catch", essential: true },
  ],
  estuary_boat: [
    { category: "Safety", item: "PLB or EPIRB", essential: true },
    { category: "Safety", item: "Life jackets / PFDs for all crew", essential: true },
    { category: "Tackle", item: "Rubber mesh landing net", essential: true },
    { category: "Tackle", item: "Trolling motor / electric motor for quiet approach", essential: false },
    { category: "Tackle", item: "Anchor and rope for drifting control", essential: false },
    { category: "Tackle", item: "Esky for catch", essential: true },
  ],
  freshwater_boat: [
    { category: "Safety", item: "Life jackets / PFDs for all crew", essential: true },
    { category: "Safety", item: "PLB for remote impoundments", essential: false },
    { category: "Tackle", item: "Large rubber-mesh landing net", essential: true },
    { category: "Tackle", item: "Electric / trolling motor", essential: false },
    { category: "Tackle", item: "Anchor and rope", essential: true },
    { category: "Tackle", item: "Live bait aeration system", essential: false },
    { category: "Licence", item: "Valid state freshwater fishing licence", essential: true },
  ],
  freshwater_shore: [
    { category: "Safety", item: "PLB for remote alpine/wilderness areas", essential: false },
    { category: "Tackle", item: "Waders and wading boots (streams, alpine rivers)", essential: false },
    { category: "Tackle", item: "Wading staff (fast-flowing alpine streams)", essential: false },
    { category: "Tackle", item: "Net with rubberised mesh for trout/bass", essential: true },
    { category: "Tackle", item: "Fly patch / foam fly wallet (fly fishing)", essential: false },
    { category: "Licence", item: "Valid state freshwater fishing licence", essential: true },
  ],
};

export const UNIVERSAL_CHECKLIST = [
  { category: "Sun Protection", item: "Polarised sunglasses (amber or grey lens)", essential: true },
  { category: "Sun Protection", item: "Long-sleeve UV sun shirt (UPF 50+)", essential: true },
  { category: "Sun Protection", item: "Wide-brim hat or cap (UPF 50+)", essential: true },
  { category: "Sun Protection", item: "SPF 50+ sunscreen (reef-safe)", essential: true },
  { category: "Tools", item: "Long-nose pliers and hook remover", essential: true },
  { category: "Tools", item: "Sharp braid scissors or nail clippers", essential: true },
  { category: "Tools", item: "Digital fishing scales (0–30kg)", essential: false },
  { category: "Tools", item: "Folding fish ruler or measuring tape", essential: true },
  { category: "First Aid", item: "First aid kit with hook removal tool", essential: true },
  { category: "Food", item: "Drinking water — 2L per person per day", essential: true },
  { category: "Food", item: "High-energy snacks and meals", essential: true },
  { category: "Admin", item: "Valid state fishing licence (saltwater)", essential: true },
  { category: "Admin", item: "Fillet knife, cutting board, fish bags", essential: true },
  { category: "Admin", item: "Camera or GoPro for catch photos", essential: false },
  { category: "Admin", item: "Headlamp / torch (early starts or night fishing)", essential: false },
];
