export interface FishingTips {
  tide: string;
  timeOfDay: string;
  conditions: string;
  structure: string;
  retrieve: string;
  hotTip: string;
}

export const FISHING_TIPS: Record<string, FishingTips> = {
  // ── Pelagic ─────────────────────────────────────────────────────────────────
  "black-marlin": {
    tide: "Tide not critical offshore — focus on current edges and temperature breaks regardless of tidal phase",
    timeOfDay: "All-day feeders; activity often peaks mid-morning and mid-afternoon when the bite window opens",
    conditions: "Clear blue water 26°C+, light SE trade winds, look for colour changes where currents collide",
    structure: "Blue water 100m+, current seams, floating weed lines and debris, temperature breaks off the continental shelf",
    retrieve: "Troll at 7–9 knots; stagger the spread (short corner to shotgun); 'smoke' lures short-short-short when a fish appears behind",
    hotTip: "Cairns Ribbon Reefs Sep–Nov is the world's premier heavy-tackle fishery — a grander (1,000lb+) is possible. Book a liveaboard mothership for multi-day reef access.",
  },
  "blue-marlin": {
    tide: "Not tide-dependent; fish temperature and colour breaks in blue water",
    timeOfDay: "Active through the day; tend to feed deeper in the heat of midday",
    conditions: "Deep blue water, warm current, 24–28°C; look for debris, birds, and bait schools",
    structure: "Offshore canyons, seamounts, FADs, and deep-water drop-offs along the continental shelf",
    retrieve: "Troll at 6–9 knots with a varied spread; live mackerel on a bridle rig is deadly when fish are fussy",
    hotTip: "Blue marlin respond to a teaser/switchbait setup — pull a hookless teaser, then switch to a live bait when the fish is fired up",
  },
  "sailfish": {
    tide: "Light wind conditions on the change of tide produce surface-feeding spikes",
    timeOfDay: "Early morning to mid-morning is most productive; fish tend to go deeper midday",
    conditions: "Clear water, light breeze, 24–27°C; sailfish often school around baitfish busting on the surface",
    structure: "Reef edges in 30–80m, coral bommies, current seams, floating debris",
    retrieve: "Slow troll (4–6 knots) with live bait or small skirted lures; drop back on a bite for 3–5 seconds before striking",
    hotTip: "Light tackle sail fishing (15–20lb) is one of the most exciting fights in the sport — consider using a fly as a teaser to get fish fired up on the surface",
  },
  "yellowfin-tuna": {
    tide: "Fish current lines and colour edges; incoming tide often concentrates bait near structure",
    timeOfDay: "Dawn and dusk are explosive; fish can be found surface-feeding on bait schools any time of day",
    conditions: "Moderate swell, visible colour change in the water (blue vs green edge), birds working offshore",
    structure: "FADs, floating debris, weed lines, current seams, submarine ridges in blue water",
    retrieve: "High-speed crank for poppers and stickbaits; let jigs flutter on the drop at the desired depth; vary the jigging cadence — fast-then-pause triggers strikes",
    hotTip: "Match the hatch — if they're eating small baitfish, downsize your lures. Schools will follow a hooked fish; leave one in the water to keep the school lit up",
  },
  "longtail-tuna": {
    tide: "Productive on the run-in tide over headlands and reef edges; fish wash up with the tide",
    timeOfDay: "Early morning surface action is best; they'll push bait to the surface in clear sight",
    conditions: "Choppy surface with bait schools pushed up; look for diving gannets and terns",
    structure: "Headland washes, reef edges, blue water inside 5km, surface schools",
    retrieve: "Cast metals into or just past the school; fast retrieve with irregular jerks; poppers work well on nervous schools",
    hotTip: "Don't over-cast into the school — land lures on the edge and rip through. Stopping retrieve often triggers strikes as the lure sinks away",
  },
  "spanish-mackerel": {
    tide: "Incoming tide on reef edges and channel markers; fish the run-in for best results",
    timeOfDay: "Early morning peak; also productive in the last two hours of daylight",
    conditions: "Clear water with moderate current flow, 24–28°C; mackerel hunt on current-swept structure",
    structure: "Reef edges, channel markers, bomboras, rocky headlands, depth transitions from 10–30m",
    retrieve: "Troll at 5–8 knots with lure running 15–25m back; vary speed; live yakkas drifted back with current are deadly",
    hotTip: "Wire trace is non-negotiable — mackerel teeth will cut 100lb fluorocarbon in milliseconds. Use 49-strand wire and re-check it after each fish.",
  },
  "wahoo": {
    tide: "Not tide-sensitive in blue water; focus on temperature breaks and current edges",
    timeOfDay: "Very early morning is peak; wahoo are known for a pre-dawn bite window",
    conditions: "Warm blue water 26°C+; light wind; wahoo prefer fast-moving current lines",
    structure: "Offshore blue water, FADs, submarine ridges, current edges 50m+",
    retrieve: "High-speed trolling 10–14 knots is the primary technique; wire leader or 100lb+ fluoro is essential to prevent bite-offs",
    hotTip: "Use a bright attractor colour like chartreuse or pink/silver at speed; wahoo react to fast-moving targets. They often strike on the drop after a speed reduction.",
  },
  "mahi-mahi": {
    tide: "Not tide-dependent; focus on floating debris and temperature lines",
    timeOfDay: "Active feeders through the day; dawn and dusk are most productive",
    conditions: "Warm blue water with surface debris (floating weed, timber, pallets); calm to moderate sea",
    structure: "FADs, floating debris (any object), weed lines, colour edges in the current",
    retrieve: "Cast and retrieve metals and small poppers past debris; mahi-mahi are aggressive — a fast retrieve with pauses triggers strikes",
    hotTip: "Keep one hooked mahi-mahi in the water — the school will stay at the boat indefinitely, allowing multiple hookups. Schoolie mahi are easy to sight-cast to.",
  },
  "southern-bluefin-tuna": {
    tide: "Tidal flow creates bait-concentrating upwellings; fish the turn of tide over seamounts",
    timeOfDay: "Dawn trolling is very effective; also active when bait schools are visible midday",
    conditions: "Cold green/blue water 15–20°C; choppy conditions concentrate bait near upwellings",
    structure: "Continental shelf edges, seamounts, cold-water upwellings (Portland, St Helens), offshore canyon walls",
    retrieve: "Troll bibbed minnows at 5–7 knots; pitch metals and slow-pitch jigs over seamounts; SBT respond to natural baitfish colours",
    hotTip: "Portland (VIC) May–August and St Helens (TAS) Feb–April are the windows — troll skirted lures and bibbed minnows close to the shelf edge",
  },

  // ── Inshore ──────────────────────────────────────────────────────────────────
  "yellowtail-kingfish": {
    tide: "Incoming tide fires up kings around reef structure; early morning run-in is best",
    timeOfDay: "Dawn is the prime window; also productive in the afternoon when bait holds near the reef top",
    conditions: "Moderate swell, clear water, 18–22°C; kings are most aggressive in cooler months (winter aggregations)",
    structure: "Rocky headlands, offshore reefs and pinnacles, FADs, moorings, kelp-covered drop-offs",
    retrieve: "Cast poppers across the current, work back with aggressive long pulls; slow-pitch jigs over the reef are deadly at dawn",
    hotTip: "Set your drag before casting — kings bolt straight for the reef from the strike. Light drag means a cut-off on the reef edge within seconds.",
  },
  "giant-trevally": {
    tide: "Incoming tide flooding the reef flat is prime; GTs ambush baitfish pushed over shallow structure",
    timeOfDay: "Dawn patrol on the reef flat at first light produces the biggest fish; they also feed at night",
    conditions: "Clear water, moderate swell breaking over the reef flat; GT hunt in water as shallow as 50cm",
    structure: "Coral reef flats, passes between islands, bommies, drop-offs adjacent to shallow water",
    retrieve: "Large cup-face poppers — fast aggressive retrieves, sharp downward rod jabs; stop popper dead to trigger a follow-up strike",
    hotTip: "Max drag pressure from the first second — GTs sprint directly for coral heads with 100kg of force. Stand your ground and pump immediately.",
  },
  "cobia": {
    tide: "Productive on the incoming tide around structure; cobia follow rays and sharks in bays",
    timeOfDay: "Active through the day; sight-fishing to cobia on the surface is common on calm days",
    conditions: "Clear water, calm sea; cobia are sight-fishable — look for dark shapes cruising near the surface",
    structure: "Floating buoys, cray pots, offshore reefs, channel markers, manta ray schools",
    retrieve: "Cast soft plastics or lightly weighted jigs to the fish and let it sink — cobia are ambush predators and will eat on the drop",
    hotTip: "Follow a school of cownose rays or manta rays — cobia almost always accompany them. A large live bait cast ahead of the ray school will get smashed.",
  },
  "tailor": {
    tide: "Run-out tide pushing bait from estuaries onto beaches is prime; gutters form on the outgoing",
    timeOfDay: "Night fishing from the beach during autumn–winter migrations is most productive",
    conditions: "Choppy surf with broken gutters; tailor push bait against the beach in schools",
    structure: "Beach gutters, rock platforms, ocean entrances, creek mouths, headland washes",
    retrieve: "Fast retrieve with metal slugs and Raider lures; a stop-start action or surface popping also works",
    hotTip: "Wire trace is recommended — tailor razor teeth will destroy mono. School runs happen in autumn: be on the beach at dusk and you could catch 20+ fish.",
  },
  "australian-salmon": {
    tide: "Run-out tide concentrates bait in gutters and off headlands",
    timeOfDay: "Dawn and dusk peak; salmon runs are tide-driven on surf beaches",
    conditions: "Choppy surf, white water, active gutters; salmon push through gutters and along the beach face",
    structure: "Surf beaches, gutters, headland washes, river mouths, rock platforms",
    retrieve: "Fast straight retrieve with metals, slowing down as lure clears the wash; allow the wave to carry the lure back toward you in the shore break",
    hotTip: "Salmon congregate in huge schools on surf beaches in winter. When you find one, there are hundreds — don't move, just keep casting into the gutter.",
  },
  "gummy-shark": {
    tide: "High tide into the flats and bay channels is the most productive phase",
    timeOfDay: "Night fishing is significantly more productive — gummies are nocturnal hunters",
    conditions: "Calm to light swell, low tide for beach access, calm bay conditions; 15–18°C water",
    structure: "Sandy bay flats, estuary channels, reef edges adjacent to sand, tidal gutters",
    retrieve: "Static bottom presentation with pilchards or squid on wire trace — let the fish pick it up and run before setting the hook",
    hotTip: "Use an 8-12 hour soak in a bay channel or on a bay flat at night in VIC or TAS — gummies patrol sand flats methodically; patience is rewarded",
  },

  // ── Reef ─────────────────────────────────────────────────────────────────────
  "coral-trout": {
    tide: "Incoming tide and the top of the tide is most productive on reef structure",
    timeOfDay: "First two hours of daylight is the feeding window — be on the reef at dawn",
    conditions: "Clear water, light wind; coral trout are sight-sensitive and prefer high vis conditions",
    structure: "Coral bommies, gutters between reef structure, rubble edges, coral heads in 5–30m",
    retrieve: "Cast soft plastic past a bommie and hop back along the bottom; live bait held just above coral structure is deadly",
    hotTip: "Coral trout are lazy ambush predators — a lure that stops right in front of them is irresistible. Park it next to the coral and twitch in place.",
  },
  "red-emperor": {
    tide: "Incoming tide floods bait over reef structure; fish the run-in with fresh bait",
    timeOfDay: "Daytime bottom fishing — most productive mid-morning to mid-afternoon in 40–120m",
    conditions: "Calm sea essential in deep water; emperor retreat to deeper structure in rough conditions",
    structure: "Deep reef edges and drop-offs in 40–120m, rubble and coral bottom, submerged bomboras",
    retrieve: "Lower bait to the bottom and hold; drift bait 1m off the bottom works well; electric reels allow rapid depth changes to work the water column",
    hotTip: "Fresh bait is essential for red emperor — they're very choosy. Bridle-rigged live bait out-fishes dead bait 5-to-1 in prime habitat",
  },
  "nannygai": {
    tide: "School up on the turn of tide over deepwater structure; incoming is generally best",
    timeOfDay: "Good at any time in deeper water; early morning drop is most productive",
    conditions: "Deep water 60–200m; calm conditions allow electric reel fishing efficiently",
    structure: "Rocky bottom and ledges in 60–200m, deep reef pinnacles, offshore banks",
    retrieve: "Lower bait/jig to the bottom, wind up 2–5m and hold; or drop slow-pitch jigs to the bottom and pitch upward 1–2m repeatedly",
    hotTip: "Nannygai school densely — if you're getting bites, drop a multi-hook paternoster rig and you can wind up with 3 at a time",
  },
  "snapper": {
    tide: "Incoming tide over inshore reef edges produces consistent bites; fish the first hour of run-in",
    timeOfDay: "Dawn and dusk are best; snapper become wary in clear midday light",
    conditions: "Light to moderate current, clear water, 16–22°C; overcast days improve daytime fishing",
    structure: "Inshore reef edges, rubble fields, rocky headlands, submerged reef in 5–50m",
    retrieve: "Work soft plastics slowly along the bottom; let jigs flutter to the deck; bait under a paternoster in current is the classic method",
    hotTip: "Snapper are current-oriented — always fish on the up-current side of structure. They head-into-current and wait for food to wash to them.",
  },
  "kingfish-qld": {
    tide: "Incoming tide over reef edges and seamounts is most productive",
    timeOfDay: "Early morning until 10am; also productive during the last hour of light",
    conditions: "Clear water, moderate current over structure; 20–25°C",
    structure: "Offshore reefs, seamounts, and pinnacles in 40–100m — both for Samson Fish in WA style and amberjack in southeast",
    retrieve: "Slow-pitch jigging with long pauses; lure falls on slack line for maximum flutter; maintain contact through the pitch phase",
    hotTip: "Amberjack are structure-oriented — anchor precisely up-current and allow your jig to drift back to the pinnacle. Speed-jig if slow-pitch isn't working.",
  },
  "blue-eye-trevalla": {
    tide: "Not strongly tide-sensitive in deep water; fish changing light conditions at dawn",
    timeOfDay: "Deep-water fishing is most productive at dawn and dusk when fish move up in the water column",
    conditions: "Calm sea essential for 150–500m fishing; good boat positioning over structure is critical",
    structure: "Continental shelf drops, submarine ridges, seamounts in 150–500m off VIC and TAS",
    retrieve: "Slow-pitch jig to the bottom; pitch upward 1–2m and hold; the flutter on the fall triggers strikes — use a light drag for good action",
    hotTip: "Blue-eye are worth every dollar of the fuel to get to them. Target seamounts between 200–350m with slow-pitch jigs in natural colours — pink/white and glow patterns work well.",
  },
  "striped-trumpeter": {
    tide: "Strong tidal flow over rocky reef is essential; fish the run-in tide",
    timeOfDay: "Daytime fishing over deep reef and rock ledges; trumpeter are bolder in low light",
    conditions: "Cold, clear water 12–16°C; calm to light swell for kelp reef access",
    structure: "Rock ledges and deep reef in 15–60m, kelp-covered bottom, underwater rocky headlands off TAS coast",
    retrieve: "Static bottom bait with pippi, squid, or crab; or slow-worked jig along the reef profile",
    hotTip: "Trumpeter hold extremely close to the kelp — drop your bait right on the reef edge. If you're not getting snags, you're not fishing in the right spot.",
  },

  // ── Estuary ──────────────────────────────────────────────────────────────────
  "barramundi": {
    tide: "Incoming tide flooding structure (mangroves, rocky bars) is the most reliable trigger; the first 2hrs of run-in",
    timeOfDay: "Dawn and dusk are peak; barramundi are also heavily night-active post-wet season",
    conditions: "Warm water 26°C+, low light, slightly turbid water from tidal flow; barra prefer overcast days to bright sun",
    structure: "Mangrove roots, submerged timber, rock bars at creek mouths, bridge pylons, snags in rivers",
    retrieve: "Cast hard bodies and surface lures tight to structure and retrieve parallel to cover; stop-start retrieve with pauses beside snags triggers aggressive strikes",
    hotTip: "A metre-plus barra never chases — position the lure to land within 30cm of the structure and it's already in ambush range. Accuracy over distance wins.",
  },
  "mangrove-jack": {
    tide: "High tide pushing into mangrove systems is critical — jack spread across structure only on the high water",
    timeOfDay: "Last hour of the tide and the first hour of the run-out produce the biggest fish; night fishing is excellent",
    conditions: "Warm, turbid water 24°C+; jack are bolder in lower visibility and after dark",
    structure: "Mangrove root systems, submerged rocks and snags, bridge pylons, log jams in river bends",
    retrieve: "Cast hard bodies into mangroves and retrieve immediately — a lure sitting still next to cover is about to get bitten",
    hotTip: "Tighten your drag before casting — a jack will be back in the snag within 0.5 seconds of the strike. An underpowered hook-set guarantees a bust-off.",
  },
  "flathead": {
    tide: "Run-out tide concentrating bait in channels; the last 2hrs of the outgoing is prime",
    timeOfDay: "Dawn on the first run-out tide; also productive at dusk and through the night on sand flats",
    conditions: "Clear to slightly turbid water; flathead move from deep channels to sand flats on the tide",
    structure: "Sand and weed bed edges, drop-offs from sand flats into channels, the tail-out of deep holes",
    retrieve: "Slow hop along the bottom — lift the rod tip 30cm and let the plastic settle; flathead ambush from the sand bottom and eat on the pause",
    hotTip: "Fish the edge where sand meets weed — that transition zone is a flathead superhighway. Walk the edge of the drop-off methodically and you'll find fish consistently.",
  },
  "mulloway": {
    tide: "Run-out tide and a couple of hours either side of the low tide on large estuaries and beaches",
    timeOfDay: "Night fishing from 8pm to 2am is where big mulloway are caught; they're very light-shy",
    conditions: "Slightly turbid water after rain; mulloway prefer dark, overcast nights with a dirty tide",
    structure: "Deep estuarine holes (bridge pylons, bends), ocean beach gutters at night, rock platforms, creek mouths",
    retrieve: "Slow roll large soft plastics along the bottom with occasional pauses; live tailor or mullet are unbeatable as bait",
    hotTip: "The biggest mulloway (20kg+) are caught at night in deep estuarine holes using live bait. Be on the water by midnight on a dark, warm-water night with some tide movement.",
  },
  "bream": {
    tide: "Incoming and high tide in estuaries; bream move onto structure as water rises",
    timeOfDay: "Late afternoon and evening is consistent; dawn is excellent in cooler months",
    conditions: "Clear water and light current; bream are finicky — switch techniques if they're lock-jawed",
    structure: "Bridge pylons, rock walls, fallen timber, oyster racks, sand drop-offs, weed beds",
    retrieve: "Extremely slow — hop a 2-inch plastic millimetre by millimetre along the bottom; bream inspect a lure for 5 seconds before eating it",
    hotTip: "Downsize when bites stop — bream will refuse a 3-inch plastic and eat a 1.5-inch immediately after. Light fluorocarbon leader (4lb) in clear water is the difference.",
  },
  "whiting": {
    tide: "Incoming tide flooding sand flats is the primary feeding window; fish 2hrs either side of high",
    timeOfDay: "Morning low tide exposes flats and concentrates bait in channels; incoming mid-morning is ideal",
    conditions: "Calm, clear estuary water; whiting sight-feed on sand flats — bright conditions help you spot them",
    structure: "Sand flats, sandy gutters, beaches adjacent to estuary mouths, weed-edged sand beds",
    retrieve: "Static bait on the sand bottom (beach worms, nippers, yabbies); slow-drag a soft plastic across the flat with long pauses",
    hotTip: "Stealthy approach on sand flats is critical — whiting spook easily. Wear polarised glasses, look for tails-up feeding fish, and cast 2m ahead of them.",
  },
  "luderick": {
    tide: "The bite follows the tide — fish a float rig as the tide pushes through the rocks",
    timeOfDay: "Early morning on the incoming tide is most productive; overcast days extend the bite",
    conditions: "Calm to light swell, clear water where weed is visible; luderick feed on green algae in the wash",
    structure: "Rock ledges with green weed (cabbage, sea lettuce), rock walls, harbour walls, breakwaters",
    retrieve: "Float rig with green weed on a fine wire hook; set the float 30–50cm above bottom and let it drift naturally in the current",
    hotTip: "Learn to prepare green weed as bait — keep it moist and soft. A hook that shows is a bait that won't get eaten; thread the weed to hide the hook completely.",
  },
  "jewfish": {
    tide: "Top of the high tide in creek mouths and estuary channels; the first run-out is peak",
    timeOfDay: "Night fishing around the full moon produces biggest black jewfish; peak from 9pm–midnight",
    conditions: "Warm water 24°C+, turbid from tidal flow; black jewfish hunt by sound in low visibility",
    structure: "Rocky reef adjacent to sand bottom, creek and river mouths, channel edges in 5–20m",
    retrieve: "Live mullet or garfish drifted back with the tide under a balloon; or a large soft plastic slow-rolled along the bottom with pauses",
    hotTip: "Black jewfish make a distinctive 'knocking' sound — locals call it 'drumming'. In the right estuary at night, you can literally hear where the fish are before you cast.",
  },

  // ── Freshwater ───────────────────────────────────────────────────────────────
  "murray-cod": {
    tide: "River flow conditions matter — rising river (after rain) turns Murray Cod on significantly",
    timeOfDay: "Early morning and late evening are prime; large fish are often active at night",
    conditions: "Slightly coloured (turbid) water after rain triggers feeding; low, clear water in summer is harder",
    structure: "Undercut banks, large submerged snags, rock ledges in river bends, deep holes below weirs",
    retrieve: "Cast large lures precisely into snags and retrieve tight to cover; bibbed minnows worked slowly with stop-start pauses; spinnerbaits are deadly in turbid water",
    hotTip: "Murray Cod are the apex ambush predator of the system — a cod will let a lure drift 20cm past before striking. Slow down your retrieve by 50% from what feels natural.",
  },
  "golden-perch": {
    tide: "Rising water level after rain triggers feeding sprees; best after a flood event",
    timeOfDay: "Active through the day; twilight periods are most consistent for lure fishing",
    conditions: "Warm water 20°C+; yellowbelly feed heavily in the warmer months (Oct–Mar)",
    structure: "Submerged timber, rock bars, weed beds, eddies behind structure, impoundment edges",
    retrieve: "Bibbed minnow at a steady retrieve along timber edges; soft plastics hopped along the bottom; trolling around impoundment structure",
    hotTip: "Golden perch are aggressive eaters after a flood — find a stretch of river after rain and work every snag. The golden phase fish are in competition mode.",
  },
  "silver-perch": {
    tide: "River flow-dependent; fish after moderate rain events in warmer months",
    timeOfDay: "Daytime fishing in impoundments; schools visible in clear water on sonar",
    conditions: "Warm, clear water in impoundments; stocked lakes fish well year-round",
    structure: "Midwater in impoundments, weed beds, inflows to stocked lakes, rocky creek arms",
    retrieve: "Small vibes and blade lures at mid-depth; nymphs on fly; worms and yabbies on a light jighead",
    hotTip: "Silver perch are schooling fish — if you catch one, there are dozens. Use sonar to find the schools in open water impoundments and vertical-jig or drop bait to them.",
  },
  "australian-bass": {
    tide: "Tidal influence in lower reaches fires up bass feeding around structure",
    timeOfDay: "Dawn surface activity is exceptional in spring–autumn; bass crash bait at first light",
    conditions: "Mild water temperature 18–24°C; bass are spring and autumn species, avoiding summer heat",
    structure: "Rock ledges, fallen timber, waterfalls and rapids (bass congregate below rapids), bridge pylons",
    retrieve: "Walk-the-dog on surface lures at first light; small vibes and blades hopped along rocky bottom; fly fishing with poppers is outstanding",
    hotTip: "Australian bass are most active when you can see your breath — a cold autumn morning with a surface popper in a tight gorge pool is one of the great freshwater experiences.",
  },
  "brown-trout": {
    tide: "River flow levels matter — wade fish when the river is running clear and low",
    timeOfDay: "Late afternoon 'evening rise' (hatch time) is sacred; also productive early morning",
    conditions: "Cool air and water (10–16°C); overcast days extend the surface feeding window; avoid bright-sun low-river conditions",
    structure: "Riffles (productive nymphing), pools (hold big fish), runs at the head and tail of pools, undercut banks",
    retrieve: "Match the hatch — observe what insects are on the water and select flies accordingly; a dead-drift with zero drag is the foundation",
    hotTip: "Brown trout are selective — a perfect presentation of the wrong fly beats a perfect fly presented badly. First, stop; second, observe what they're eating; third, then cast.",
  },
  "rainbow-trout": {
    tide: "Water level and temperature drive feeding; fish clear-running rivers after snow-melt settles",
    timeOfDay: "Early morning is excellent; rainbows are more active through the day than browns",
    conditions: "Cold, clear water 10–15°C; rainbows are more tolerant of current than browns",
    structure: "Fast runs and riffles, tail-outs of pools, inlet streams to lakes",
    retrieve: "Spinners across and downstream in fast water; fly nymphs dead-drifted; PowerBait bottom-fished in stocked lakes",
    hotTip: "Rainbows in stocked lakes are not selective — match the size, not the exact pattern. In wild rivers, they're almost as discerning as browns.",
  },
  "redfin": {
    tide: "Not tide-dependent; fish in the cooler months (April–September) in freshwater",
    timeOfDay: "Daytime fishing is consistent; redfin are visual, aggressive feeders",
    conditions: "Cool, clear water; redfin tolerate a range of conditions but peak in autumn–winter",
    structure: "Submerged timber and rock piles, weed beds in impoundments, creek arms, boat ramps and jetties (they like man-made structure)",
    retrieve: "Cast small blades and vibes on a slow hop; drop and lift repeatedly — redfin hit on the drop with aggressive strikes",
    hotTip: "Redfin school densely in autumn — find one with sonar and vertical-jig with a small blade. You'll get multiple casts into the same school for rapid-fire action.",
  },
  "saratoga": {
    tide: "Not tide-dependent (freshwater); rising water levels in wet season trigger spawning",
    timeOfDay: "Early morning surface activity; saratoga patrol lily pad edges at first light",
    conditions: "Warm tropical water 26°C+; calm, overcast mornings produce surface action",
    structure: "Lily pads, fallen timber, overhanging vegetation, shallow margins of tropical impoundments",
    retrieve: "Work surface lures (Pompadour, Jackall Mikey) extremely slowly along lily pad edges with long pauses — saratoga inspect before striking",
    hotTip: "Saratoga are notoriously slow to commit — work a surface popper in one spot and wait. They'll circle a lure 3–4 times before eating. Patience is everything.",
  },
  "catfish": {
    tide: "Rising river after moderate rain concentrates catfish in eddies and slack water",
    timeOfDay: "Night fishing from dusk to midnight is most productive; catfish are nocturnal hunters",
    conditions: "Warm water 22°C+; turbid water after rain is prime; catfish hunt by scent in low visibility",
    structure: "Muddy river bends, deep pools, undercut banks, confluences of tributaries",
    retrieve: "Static bottom bait (scrub worm, yabby, or pilchard) on a running sinker; leave the bail arm open and let the fish take line before striking",
    hotTip: "Catfish dorsal and pectoral spines are venomous and can cause serious infection — always grip from behind the fins or use a lip gripper. Release carefully.",
  },
  "ocean-trout": {
    tide: "Incoming tide on TAS estuary flats is prime — fish the top of the tide on sand and weed flats",
    timeOfDay: "Dawn on estuary flats in TAS; overcast winter mornings are exceptional",
    conditions: "Cold estuary water 10–14°C; low tide exposes flats and concentrates fish in channels",
    structure: "Estuarine sand flats, channel edges, inlet streams, bays adjacent to highland lakes in TAS",
    retrieve: "Dead-drift streamers (Clouser Minnow) in the current; or strip-strip-pause for active takes; spoons and small soft plastics across the flat",
    hotTip: "Sea-run ocean trout in TAS reach 60cm+ — stalk them on the estuary flats with polarised glasses on a cold winter morning. It's sight-fishing at its finest.",
  },
};
