// Maps experience slugs to destination slugs
export const EXPERIENCE_DESTINATIONS: { experienceSlug: string; destinationSlug: string }[] = [
  // Dogtooth Tuna Jigging
  { experienceSlug: "dogtooth-jigging", destinationSlug: "cairns--osprey-reef-coral-sea" },
  { experienceSlug: "dogtooth-jigging", destinationSlug: "cocos-keeling-islands--cocos-blue-water" },
  // Topwater GT Fishing
  { experienceSlug: "topwater-gt", destinationSlug: "cairns--ribbon-reefs" },
  { experienceSlug: "topwater-gt", destinationSlug: "cairns--lizard-island-grounds" },
  { experienceSlug: "topwater-gt", destinationSlug: "cairns--osprey-reef-coral-sea" },
  { experienceSlug: "topwater-gt", destinationSlug: "christmas-island--christmas-island-flats" },
  { experienceSlug: "topwater-gt", destinationSlug: "christmas-island--flying-fish-cove" },
  { experienceSlug: "topwater-gt", destinationSlug: "cocos-keeling-islands--cocos-lagoon-flats" },
  { experienceSlug: "topwater-gt", destinationSlug: "cocos-keeling-islands--north-keeling-island" },
  { experienceSlug: "topwater-gt", destinationSlug: "exmouth-ningaloo--ningaloo-reef-flats" },
  { experienceSlug: "topwater-gt", destinationSlug: "arnhem-land--arafura-sea-coast" },
  { experienceSlug: "topwater-gt", destinationSlug: "groote-eylandt--groote-eylandt-reefs" },
  { experienceSlug: "topwater-gt", destinationSlug: "montebello-islands--montebello-main-group" },
  { experienceSlug: "topwater-gt", destinationSlug: "cooktown--lizard-island" },
  { experienceSlug: "topwater-gt", destinationSlug: "lord-howe-island--ball-pyramid" },

  // Blue Water Marlin Trolling
  { experienceSlug: "marlin-trolling", destinationSlug: "cairns--cairns-marlin-alley" },
  { experienceSlug: "marlin-trolling", destinationSlug: "cairns--lizard-island-grounds" },
  { experienceSlug: "marlin-trolling", destinationSlug: "cairns--osprey-reef-coral-sea" },
  { experienceSlug: "marlin-trolling", destinationSlug: "port-douglas--agincourt-reef" },
  { experienceSlug: "marlin-trolling", destinationSlug: "bay-of-islands--cavalli-islands" },
  { experienceSlug: "marlin-trolling", destinationSlug: "tauranga-bay-of-plenty--mayor-island" },
  { experienceSlug: "marlin-trolling", destinationSlug: "sydney--sydney-offshore-fads" },
  { experienceSlug: "marlin-trolling", destinationSlug: "eden--twofold-bay" },
  { experienceSlug: "marlin-trolling", destinationSlug: "gold-coast--seaway-canyon" },
  { experienceSlug: "marlin-trolling", destinationSlug: "port-stephens--pin-reef" },

  // Offshore Yellowfin Tuna
  { experienceSlug: "yellowfin-offshore", destinationSlug: "cairns--osprey-reef-coral-sea" },
  { experienceSlug: "yellowfin-offshore", destinationSlug: "sydney--sydney-offshore-fads" },
  { experienceSlug: "yellowfin-offshore", destinationSlug: "gold-coast--seaway-canyon" },
  { experienceSlug: "yellowfin-offshore", destinationSlug: "eden--eden-offshore-canyon" },
  { experienceSlug: "yellowfin-offshore", destinationSlug: "brisbane-moreton-bay--cape-moreton" },
  { experienceSlug: "yellowfin-offshore", destinationSlug: "coffs-harbour--coffs-harbour-offshore" },
  { experienceSlug: "yellowfin-offshore", destinationSlug: "newcastle--bar-beach-offshore" },
  { experienceSlug: "yellowfin-offshore", destinationSlug: "ballina-byron-bay--byron-bay-offshore" },
  { experienceSlug: "yellowfin-offshore", destinationSlug: "christmas-island--christmas-island-offshore" },
  { experienceSlug: "yellowfin-offshore", destinationSlug: "cocos-keeling-islands--cocos-blue-water" },

  // Kingfish Jigging
  { experienceSlug: "kingfish-jigging", destinationSlug: "tauranga-bay-of-plenty--mayor-island" },
  { experienceSlug: "kingfish-jigging", destinationSlug: "bay-of-islands--poor-knights-islands" },
  { experienceSlug: "kingfish-jigging", destinationSlug: "auckland-hauraki-gulf--little-barrier-island" },
  { experienceSlug: "kingfish-jigging", destinationSlug: "auckland-hauraki-gulf--mokohinau-islands" },
  { experienceSlug: "kingfish-jigging", destinationSlug: "lord-howe-island--ball-pyramid" },
  { experienceSlug: "kingfish-jigging", destinationSlug: "sydney--sydney-offshore-fads" },
  { experienceSlug: "kingfish-jigging", destinationSlug: "port-stephens--broughton-island" },
  { experienceSlug: "kingfish-jigging", destinationSlug: "jervis-bay--st-georges-head" },
  { experienceSlug: "kingfish-jigging", destinationSlug: "port-phillip-bay--rip-entrance" },
  { experienceSlug: "kingfish-jigging", destinationSlug: "eden--twofold-bay" },

  // Light Tackle Pelagics
  { experienceSlug: "light-tackle-pelagics", destinationSlug: "townsville--cape-cleveland" },
  { experienceSlug: "light-tackle-pelagics", destinationSlug: "cairns--cape-tribulation-offshore" },
  { experienceSlug: "light-tackle-pelagics", destinationSlug: "mackay--cape-hillsborough" },
  { experienceSlug: "light-tackle-pelagics", destinationSlug: "airlie-beach--outer-whitsunday-reefs" },
  { experienceSlug: "light-tackle-pelagics", destinationSlug: "sunshine-coast--north-reef" },
  { experienceSlug: "light-tackle-pelagics", destinationSlug: "brisbane-moreton-bay--cape-moreton" },
  { experienceSlug: "light-tackle-pelagics", destinationSlug: "coffs-harbour--solitary-islands" },
  { experienceSlug: "light-tackle-pelagics", destinationSlug: "exmouth-ningaloo--muiron-islands" },

  // Deep Dropping
  { experienceSlug: "deep-dropping", destinationSlug: "eden--eden-offshore-canyon" },
  { experienceSlug: "deep-dropping", destinationSlug: "port-phillip-bay--rip-entrance" },
  { experienceSlug: "deep-dropping", destinationSlug: "portland-vic--blue-eye-deep-reef" },
  { experienceSlug: "deep-dropping", destinationSlug: "wilsons-promontory--outer-prom-reefs" },
  { experienceSlug: "deep-dropping", destinationSlug: "kaikoura--kaikoura-canyon-edge" },
  { experienceSlug: "deep-dropping", destinationSlug: "marlborough-sounds--outer-sounds-reefs" },
  { experienceSlug: "deep-dropping", destinationSlug: "queenstown-fiordland--milford-sound" },
  { experienceSlug: "deep-dropping", destinationSlug: "queenstown-fiordland--doubtful-sound" },
  { experienceSlug: "deep-dropping", destinationSlug: "strahan--hell-gates" },
  { experienceSlug: "deep-dropping", destinationSlug: "port-arthur--tasman-peninsula-reefs" },
  { experienceSlug: "deep-dropping", destinationSlug: "bruny-island--south-bruny-reefs" },

  // Coral Trout Reef Fishing
  { experienceSlug: "coral-trout-reef", destinationSlug: "cairns--ribbon-reefs" },
  { experienceSlug: "coral-trout-reef", destinationSlug: "port-douglas--tongue-reef" },
  { experienceSlug: "coral-trout-reef", destinationSlug: "cooktown--north-direction-island" },
  { experienceSlug: "coral-trout-reef", destinationSlug: "airlie-beach--hook-island" },
  { experienceSlug: "coral-trout-reef", destinationSlug: "yeppoon--great-keppel-island" },
  { experienceSlug: "coral-trout-reef", destinationSlug: "gladstone--lady-musgrave-island" },
  { experienceSlug: "coral-trout-reef", destinationSlug: "exmouth-ningaloo--ningaloo-reef-flats" },
  { experienceSlug: "coral-trout-reef", destinationSlug: "karratha-dampier--legendre-island" },
  { experienceSlug: "coral-trout-reef", destinationSlug: "montebello-islands--montebello-main-group" },
  { experienceSlug: "coral-trout-reef", destinationSlug: "groote-eylandt--groote-eylandt-reefs" },

  // Snapper Bottom Bashing
  { experienceSlug: "snapper-bottom-bashing", destinationSlug: "auckland-hauraki-gulf--hen-chicken-islands" },
  { experienceSlug: "snapper-bottom-bashing", destinationSlug: "bay-of-islands--deep-water-cove" },
  { experienceSlug: "snapper-bottom-bashing", destinationSlug: "marlborough-sounds--queen-charlotte-sound" },
  { experienceSlug: "snapper-bottom-bashing", destinationSlug: "wellington-cook-strait--cook-strait-rips" },
  { experienceSlug: "snapper-bottom-bashing", destinationSlug: "brisbane-moreton-bay--north-reef-moreton" },
  { experienceSlug: "snapper-bottom-bashing", destinationSlug: "port-stephens--broughton-island" },
  { experienceSlug: "snapper-bottom-bashing", destinationSlug: "narooma--montague-island" },
  { experienceSlug: "snapper-bottom-bashing", destinationSlug: "sydney--cape-banks" },
  { experienceSlug: "snapper-bottom-bashing", destinationSlug: "jervis-bay--jervis-bay-offshore" },
  { experienceSlug: "snapper-bottom-bashing", destinationSlug: "port-phillip-bay--artificial-reefs" },

  // Slow Pitch Jigging
  { experienceSlug: "slow-pitch-jigging", destinationSlug: "cairns--ribbon-reefs" },
  { experienceSlug: "slow-pitch-jigging", destinationSlug: "port-douglas--tongue-reef" },
  { experienceSlug: "slow-pitch-jigging", destinationSlug: "auckland-hauraki-gulf--mokohinau-islands" },
  { experienceSlug: "slow-pitch-jigging", destinationSlug: "kaikoura--kaikoura-canyon-edge" },
  { experienceSlug: "slow-pitch-jigging", destinationSlug: "marlborough-sounds--outer-sounds-reefs" },
  { experienceSlug: "slow-pitch-jigging", destinationSlug: "eden--eden-offshore-canyon" },
  { experienceSlug: "slow-pitch-jigging", destinationSlug: "port-lincoln--neptune-islands" },
  { experienceSlug: "slow-pitch-jigging", destinationSlug: "geraldton--abrolhos-islands-reefs" },

  // WA Demersal Reef
  { experienceSlug: "wa-demersal-reef", destinationSlug: "perth-rottnest--rottnest-island-reefs" },
  { experienceSlug: "wa-demersal-reef", destinationSlug: "geraldton--abrolhos-islands-reefs" },
  { experienceSlug: "wa-demersal-reef", destinationSlug: "mandurah--mandurah-offshore-reefs" },
  { experienceSlug: "wa-demersal-reef", destinationSlug: "bunbury-margaret-river--bunbury-offshore" },
  { experienceSlug: "wa-demersal-reef", destinationSlug: "albany--king-george-sound" },
  { experienceSlug: "wa-demersal-reef", destinationSlug: "esperance--recherche-archipelago" },
  { experienceSlug: "wa-demersal-reef", destinationSlug: "shark-bay--denham-sound" },
  { experienceSlug: "wa-demersal-reef", destinationSlug: "perth-rottnest--two-rocks-wanneroo" },

  // Barramundi Estuary
  { experienceSlug: "barramundi-estuary", destinationSlug: "darwin--darwin-harbour" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "darwin--bynoe-harbour" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "daly-river--daly-river-middle-reaches" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "daly-river--daly-river-upper-tidal" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "kakadu--south-alligator-river" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "kakadu--east-alligator-river" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "katherine-river--nitmiluk-gorge" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "broome--dampier-peninsula-creeks" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "kununurra--ord-river" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "borroloola--mcarthur-river" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "arnhem-land--blyth-river" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "roper-river--roper-river-tidal" },
  { experienceSlug: "barramundi-estuary", destinationSlug: "fitzroy-crossing--fitzroy-river-gorge" },

  // Flathead on Soft Plastics
  { experienceSlug: "flathead-soft-plastics", destinationSlug: "port-stephens--myall-river" },
  { experienceSlug: "flathead-soft-plastics", destinationSlug: "sydney--port-hacking" },
  { experienceSlug: "flathead-soft-plastics", destinationSlug: "lake-macquarie--lake-macquarie-flats" },
  { experienceSlug: "flathead-soft-plastics", destinationSlug: "batemans-bay--clyde-river" },
  { experienceSlug: "flathead-soft-plastics", destinationSlug: "lakes-entrance--gippsland-lakes" },
  { experienceSlug: "flathead-soft-plastics", destinationSlug: "mallacoota--mallacoota-inlet" },
  { experienceSlug: "flathead-soft-plastics", destinationSlug: "brisbane-moreton-bay--south-passage" },
  { experienceSlug: "flathead-soft-plastics", destinationSlug: "sunshine-coast--noosa-river-estuary" },
  { experienceSlug: "flathead-soft-plastics", destinationSlug: "port-phillip-bay--werribee-flats" },
  { experienceSlug: "flathead-soft-plastics", destinationSlug: "hobart--derwent-estuary" },

  // Bream & Whiting Estuary
  { experienceSlug: "bream-estuary", destinationSlug: "lake-macquarie--swansea-channel" },
  { experienceSlug: "bream-estuary", destinationSlug: "hawkesbury-river--cowan-creek" },
  { experienceSlug: "bream-estuary", destinationSlug: "batemans-bay--clyde-river" },
  { experienceSlug: "bream-estuary", destinationSlug: "westernport-bay--lang-lang-flats" },
  { experienceSlug: "bream-estuary", destinationSlug: "port-phillip-bay--werribee-flats" },
  { experienceSlug: "bream-estuary", destinationSlug: "mandurah--peel-inlet" },
  { experienceSlug: "bream-estuary", destinationSlug: "perth-rottnest--cockburn-sound" },
  { experienceSlug: "bream-estuary", destinationSlug: "coorong--coorong-lagoon" },
  { experienceSlug: "bream-estuary", destinationSlug: "mallacoota--mallacoota-inlet" },
  { experienceSlug: "bream-estuary", destinationSlug: "tathra-merimbula--merimbula-lake" },

  // Mulloway Night Session
  { experienceSlug: "mulloway-night", destinationSlug: "sydney--sydney-harbour" },
  { experienceSlug: "mulloway-night", destinationSlug: "hawkesbury-river--upper-hawkesbury" },
  { experienceSlug: "mulloway-night", destinationSlug: "newcastle--hunter-river-estuary" },
  { experienceSlug: "mulloway-night", destinationSlug: "batemans-bay--clyde-river" },
  { experienceSlug: "mulloway-night", destinationSlug: "eden--kiah-river" },
  { experienceSlug: "mulloway-night", destinationSlug: "coorong--murray-mouth" },
  { experienceSlug: "mulloway-night", destinationSlug: "victor-harbor--encounter-bay" },
  { experienceSlug: "mulloway-night", destinationSlug: "lake-macquarie--wangi-wangi-deep" },

  // Squid Evening Session
  { experienceSlug: "squid-evening", destinationSlug: "port-phillip-bay--sorrento-portsea" },
  { experienceSlug: "squid-evening", destinationSlug: "victor-harbor--rapid-bay" },
  { experienceSlug: "squid-evening", destinationSlug: "kangaroo-island--vivonne-bay" },
  { experienceSlug: "squid-evening", destinationSlug: "yorke-peninsula--edithburgh" },
  { experienceSlug: "squid-evening", destinationSlug: "adelaide-gulf-st-vincent--port-noarlunga" },
  { experienceSlug: "squid-evening", destinationSlug: "coffin-bay--coffin-bay-inlet" },
  { experienceSlug: "squid-evening", destinationSlug: "port-lincoln--boston-bay" },
  { experienceSlug: "squid-evening", destinationSlug: "whyalla--arno-bay-area" },

  // Beach & Surf Casting
  { experienceSlug: "beach-casting-surf", destinationSlug: "fraser-coast--fraser-island-beach" },
  { experienceSlug: "beach-casting-surf", destinationSlug: "port-hedland--80-mile-beach" },
  { experienceSlug: "beach-casting-surf", destinationSlug: "shark-bay--steep-point" },
  { experienceSlug: "beach-casting-surf", destinationSlug: "esperance--cape-le-grand" },
  { experienceSlug: "beach-casting-surf", destinationSlug: "invercargill-southland--oreti-beach" },
  { experienceSlug: "beach-casting-surf", destinationSlug: "lakes-entrance--ninety-mile-beach" },
  { experienceSlug: "beach-casting-surf", destinationSlug: "broome--eighty-mile-beach-north" },
  { experienceSlug: "beach-casting-surf", destinationSlug: "wollongong--bass-point" },

  // Trout Fly Fishing
  { experienceSlug: "trout-fly-fishing", destinationSlug: "snowy-mountains-rivers--thredbo-river" },
  { experienceSlug: "trout-fly-fishing", destinationSlug: "snowy-mountains-rivers--tumut-river" },
  { experienceSlug: "trout-fly-fishing", destinationSlug: "ovens-king-rivers--bright-ovens-river" },
  { experienceSlug: "trout-fly-fishing", destinationSlug: "goulburn-river-vic--thornton-upper-goulburn" },
  { experienceSlug: "trout-fly-fishing", destinationSlug: "arthurs-lake-tas--arthurs-lake-shallows" },
  { experienceSlug: "trout-fly-fishing", destinationSlug: "arthurs-lake-tas--pine-tier-lagoon" },
  { experienceSlug: "trout-fly-fishing", destinationSlug: "lake-st-clair--narcissus-river-mouth" },
  { experienceSlug: "trout-fly-fishing", destinationSlug: "queenstown-fiordland--lake-wakatipu" },
  { experienceSlug: "trout-fly-fishing", destinationSlug: "invercargill-southland--mataura-river" },
  { experienceSlug: "trout-fly-fishing", destinationSlug: "west-coast-greymouth--grey-river" },
  { experienceSlug: "trout-fly-fishing", destinationSlug: "nelson-tasman--motueka-river" },

  // Murray Cod Lure Fishing
  { experienceSlug: "murray-cod-lure", destinationSlug: "murray-river-echuca--echuca-log-snags" },
  { experienceSlug: "murray-cod-lure", destinationSlug: "murray-river-albury--albury-wodonga-snags" },
  { experienceSlug: "murray-cod-lure", destinationSlug: "lake-mulwala--mulwala-timber" },
  { experienceSlug: "murray-cod-lure", destinationSlug: "lake-hume--bellbridge-point" },
  { experienceSlug: "murray-cod-lure", destinationSlug: "murrumbidgee-river--wagga-wagga-pools" },
  { experienceSlug: "murray-cod-lure", destinationSlug: "macquarie-river--dubbo-snags" },
  { experienceSlug: "murray-cod-lure", destinationSlug: "darling-river-bourke--back-darling-pools" },
  { experienceSlug: "murray-cod-lure", destinationSlug: "lake-eildon--delatite-arm" },

  // Bass Impoundment Fishing
  { experienceSlug: "bass-impoundment", destinationSlug: "lake-eildon--delatite-arm" },
  { experienceSlug: "bass-impoundment", destinationSlug: "lake-eildon--big-river-arm" },
  { experienceSlug: "bass-impoundment", destinationSlug: "hawkesbury-river--cowan-creek" },
  { experienceSlug: "bass-impoundment", destinationSlug: "lake-hume--lake-hume-arms" },
  { experienceSlug: "bass-impoundment", destinationSlug: "lake-mulwala--mulwala-timber" },
  { experienceSlug: "bass-impoundment", destinationSlug: "murray-river-mildura--lake-cullulleraine" },

  // NZ Blue Cod Bottom Fishing
  { experienceSlug: "nz-blue-cod", destinationSlug: "marlborough-sounds--queen-charlotte-sound" },
  { experienceSlug: "nz-blue-cod", destinationSlug: "marlborough-sounds--pelorus-sound" },
  { experienceSlug: "nz-blue-cod", destinationSlug: "marlborough-sounds--tory-channel" },
  { experienceSlug: "nz-blue-cod", destinationSlug: "kaikoura--kaikoura-canyon-edge" },
  { experienceSlug: "nz-blue-cod", destinationSlug: "kaikoura--south-bay-reefs" },
  { experienceSlug: "nz-blue-cod", destinationSlug: "wellington-cook-strait--cook-strait-rips" },
  { experienceSlug: "nz-blue-cod", destinationSlug: "invercargill-southland--bluff-harbour" },
  { experienceSlug: "nz-blue-cod", destinationSlug: "invercargill-southland--stewart-island" },
  { experienceSlug: "nz-blue-cod", destinationSlug: "dunedin-otago--otago-peninsula-reefs" },

  // NZ Snapper Fishing
  { experienceSlug: "nz-snapper", destinationSlug: "auckland-hauraki-gulf--little-barrier-island" },
  { experienceSlug: "nz-snapper", destinationSlug: "auckland-hauraki-gulf--hen-chicken-islands" },
  { experienceSlug: "nz-snapper", destinationSlug: "auckland-hauraki-gulf--waiheke-island-reefs" },
  { experienceSlug: "nz-snapper", destinationSlug: "bay-of-islands--cape-brett" },
  { experienceSlug: "nz-snapper", destinationSlug: "bay-of-islands--deep-water-cove" },
  { experienceSlug: "nz-snapper", destinationSlug: "tauranga-bay-of-plenty--mount-maunganui-offshore" },
  { experienceSlug: "nz-snapper", destinationSlug: "nelson-tasman--golden-bay-flats" },
  { experienceSlug: "nz-snapper", destinationSlug: "napier-hawkes-bay--napier-port-offshore" },

  // Bonefish Flats Fishing
  { experienceSlug: "bonefish-flats", destinationSlug: "christmas-island--christmas-island-flats" },
  { experienceSlug: "bonefish-flats", destinationSlug: "christmas-island--flying-fish-cove" },
  { experienceSlug: "bonefish-flats", destinationSlug: "cocos-keeling-islands--cocos-lagoon-flats" },
  { experienceSlug: "bonefish-flats", destinationSlug: "cocos-keeling-islands--north-keeling-island" },
];
