// tripType: 'offshore_pelagic' | 'reef' | 'estuary' | 'inshore_sport' | 'all'

export const GEAR_TEMPLATES = [
  // ─── Offshore Pelagic (marlin, tuna, wahoo, mahi-mahi) ─────────────────────
  { name: "Heavy trolling rod 80–130lb", category: "tackle", tripType: "offshore_pelagic", itemName: "Heavy trolling rod 80–130lb class", quantity: 2, isEssential: true },
  { name: "Overhead reel 80–130lb", category: "tackle", tripType: "offshore_pelagic", itemName: "Overhead trolling reel (Penn International / Shimano Tiagra)", quantity: 2, isEssential: true },
  { name: "Skirted trolling lures", category: "tackle", tripType: "offshore_pelagic", itemName: "Skirted trolling lures (assorted colours, 9–14 inch)", quantity: 6, isEssential: true, notes: "Carry black/red, purple/black, pink/white combos" },
  { name: "Bibbed minnow lures", category: "tackle", tripType: "offshore_pelagic", itemName: "Large bibbed diving minnows (Halco, Pakula, Nomad DTX)", quantity: 4, isEssential: false },
  { name: "Wire traces and leader", category: "tackle", tripType: "offshore_pelagic", itemName: "Single-strand wire traces 200–400lb, plus heavy fluorocarbon leader", quantity: 1, isEssential: true },
  { name: "Gaffs and flying gaff", category: "tackle", tripType: "offshore_pelagic", itemName: "Gaffs (2x short gaffs + 1 flying gaff for billfish)", quantity: 1, isEssential: true },
  { name: "Outriggers", category: "tackle", tripType: "offshore_pelagic", itemName: "Outrigger poles (if trailer boat — confirm charter has them)", quantity: 1, isEssential: false },
  { name: "Lure trolling spread plan", category: "tackle", tripType: "offshore_pelagic", itemName: "Pre-planned trolling spread (short/long corner, short/long rigger, shotgun)", quantity: 1, isEssential: false, notes: "Research standard 5-lure spread setup" },
  { name: "Live bait rigging kit", category: "tackle", tripType: "offshore_pelagic", itemName: "Live bait hooks (7/0–10/0), bridle rigging needles, rubber bands", quantity: 1, isEssential: false },
  { name: "Fighting harness", category: "tackle", tripType: "offshore_pelagic", itemName: "Kidney harness for heavy-tackle fights", quantity: 1, isEssential: false },
  { name: "Shimano / Penn light jigging setup", category: "tackle", tripType: "offshore_pelagic", itemName: "Light spin rod 20–30lb with 5000–8000 size reel for light jigging", quantity: 1, isEssential: false },
  { name: "Fire extinguisher", category: "safety", tripType: "offshore_pelagic", itemName: "Marine fire extinguisher (DCP or CO2) — serviceable", quantity: 1, isEssential: true },
  { name: "Anchor + chain + rode", category: "safety", tripType: "offshore_pelagic", itemName: "Anchor, chain (min 2m) and rope rode appropriate for vessel", quantity: 1, isEssential: true },
  { name: "Bilge pump", category: "safety", tripType: "offshore_pelagic", itemName: "Bilge pump (electric or manual) — operational", quantity: 1, isEssential: true },
  { name: "Kill switch lanyard", category: "safety", tripType: "offshore_pelagic", itemName: "Kill switch lanyard attached to operator while underway", quantity: 1, isEssential: true },
  { name: "Navigation lights", category: "safety", tripType: "offshore_pelagic", itemName: "Navigation lights checked (required between sunset and sunrise)", quantity: 1, isEssential: true },
  { name: "Sound signal", category: "safety", tripType: "offshore_pelagic", itemName: "Sound signal — air horn or whistle (legal requirement)", quantity: 1, isEssential: true },
  { name: "Boat registration papers", category: "logistics", tripType: "offshore_pelagic", itemName: "Boat registration papers on board", quantity: 1, isEssential: true },

  // ─── Reef Fishing (coral trout, snapper, red emperor, nannygai) ───────────
  { name: "Medium baitcasting / overhead rod", category: "tackle", tripType: "reef", itemName: "Medium-heavy overhead or baitcaster rod 30–50lb, 6–7ft", quantity: 2, isEssential: true },
  { name: "Electric or overhead reel", category: "tackle", tripType: "reef", itemName: "Shimano Electric Forcemaster or manual overhead reel", quantity: 2, isEssential: true },
  { name: "Monofilament or braid 30–50lb", category: "tackle", tripType: "reef", itemName: "50lb braid mainline, 60lb monofilament leader", quantity: 1, isEssential: true },
  { name: "Reef rigs and sinkers", category: "tackle", tripType: "reef", itemName: "Double hook paternoster rigs, snapper leads 100–400g", quantity: 1, isEssential: true },
  { name: "Pilchards (frozen)", category: "tackle", tripType: "reef", itemName: "Frozen pilchards (2-3 boxes)", quantity: 3, isEssential: true },
  { name: "Squid (frozen or fresh)", category: "tackle", tripType: "reef", itemName: "Frozen squid tubes and whole squid", quantity: 2, isEssential: true },
  { name: "Soft plastics for reef", category: "tackle", tripType: "reef", itemName: "Large paddle tails and curly tails 5–7 inch (Zerek, Zman)", quantity: 1, isEssential: false },
  { name: "Bait cutting board and knife", category: "tackle", tripType: "reef", itemName: "Bait board with knife and bait scissors", quantity: 1, isEssential: true },
  { name: "Bait bucket", category: "tackle", tripType: "reef", itemName: "Aerated live bait bucket", quantity: 1, isEssential: false },

  // ─── Estuary (barramundi, flathead, bream, mulloway, jewfish) ─────────────
  { name: "Light-medium spin rod", category: "tackle", tripType: "estuary", itemName: "7ft light-medium spinning rod (6–10lb or 10–15lb class)", quantity: 2, isEssential: true },
  { name: "Spinning reel 2500–4000", category: "tackle", tripType: "estuary", itemName: "Spinning reel 2500–4000 size with 10–15lb braid", quantity: 2, isEssential: true },
  { name: "Soft plastic lures", category: "tackle", tripType: "estuary", itemName: "Soft plastics assortment — paddle tails, curl tails, grubs 2–5 inch", quantity: 1, isEssential: true, notes: "Carry natural colours (prawn, baitfish) and bright (chartreuse)" },
  { name: "Jigheads", category: "tackle", tripType: "estuary", itemName: "Jigheads 1/6–3/8 oz in various colours", quantity: 1, isEssential: true },
  { name: "Hard body lures", category: "tackle", tripType: "estuary", itemName: "Shallow diving hard body lures 50–80mm (Jackal, Ima, Daiwa)", quantity: 1, isEssential: false },
  { name: "Fluorocarbon leader", category: "tackle", tripType: "estuary", itemName: "Fluorocarbon leader 8–20lb", quantity: 1, isEssential: true },
  { name: "Bait for estuary", category: "tackle", tripType: "estuary", itemName: "Prawns, worms, mullet strips (for whiting and bream options)", quantity: 1, isEssential: false },
  { name: "Landing net", category: "tackle", tripType: "estuary", itemName: "Rubber mesh landing net", quantity: 1, isEssential: true },
  { name: "Waders or water shoes", category: "clothing", tripType: "estuary", itemName: "Wading booties or neoprene waders for wade fishing", quantity: 1, isEssential: false },

  // ─── Inshore Sport (kingfish, GT, cobia, Spanish mackerel) ────────────────
  { name: "Popper rod", category: "tackle", tripType: "inshore_sport", itemName: "Heavy popper rod 40–80lb (topwater game rod)", quantity: 1, isEssential: true },
  { name: "High-capacity spin reel 8000–14000", category: "tackle", tripType: "inshore_sport", itemName: "Shimano Stella / Daiwa Saltiga 8000–14000 with 65–80lb braid", quantity: 1, isEssential: true },
  { name: "Surface poppers", category: "tackle", tripType: "inshore_sport", itemName: "Cup face poppers 80–120g (Halco Roosta Popper, GT Raider)", quantity: 4, isEssential: true },
  { name: "Stickbaits", category: "tackle", tripType: "inshore_sport", itemName: "Sinking and floating stickbaits 100–160g", quantity: 3, isEssential: false },
  { name: "Speed jigs", category: "tackle", tripType: "inshore_sport", itemName: "Speed jigs 100–200g (for vertical jigging over reefs)", quantity: 4, isEssential: false },
  { name: "Heavy fluorocarbon trace", category: "tackle", tripType: "inshore_sport", itemName: "Heavy fluorocarbon trace 60–100lb", quantity: 1, isEssential: true },
  { name: "Wire trace for mackerel", category: "tackle", tripType: "inshore_sport", itemName: "Single-strand wire trace 60–100lb (Spanish mackerel cut-off prevention)", quantity: 1, isEssential: false },
  { name: "Assist hooks", category: "tackle", tripType: "inshore_sport", itemName: "Assist hook rigs for jigs (Decoy, Owner)", quantity: 1, isEssential: true },
  { name: "BKK or Owner split rings", category: "tackle", tripType: "inshore_sport", itemName: "Heavy split rings and snap locks for lures", quantity: 1, isEssential: true },
  { name: "Fire extinguisher (inshore)", category: "safety", tripType: "inshore_sport", itemName: "Marine fire extinguisher (DCP or CO2) — serviceable", quantity: 1, isEssential: true },
  { name: "Anchor + chain + rode (inshore)", category: "safety", tripType: "inshore_sport", itemName: "Anchor, chain (min 2m) and rope rode appropriate for vessel", quantity: 1, isEssential: true },
  { name: "Bilge pump (inshore)", category: "safety", tripType: "inshore_sport", itemName: "Bilge pump (electric or manual) — operational", quantity: 1, isEssential: true },
  { name: "Kill switch lanyard (inshore)", category: "safety", tripType: "inshore_sport", itemName: "Kill switch lanyard attached to operator while underway", quantity: 1, isEssential: true },
  { name: "Navigation lights (inshore)", category: "safety", tripType: "inshore_sport", itemName: "Navigation lights checked (required between sunset and sunrise)", quantity: 1, isEssential: true },
  { name: "Sound signal (inshore)", category: "safety", tripType: "inshore_sport", itemName: "Sound signal — air horn or whistle (legal requirement)", quantity: 1, isEssential: true },
  { name: "Boat registration papers (inshore)", category: "logistics", tripType: "inshore_sport", itemName: "Boat registration papers on board", quantity: 1, isEssential: true },

  // ─── All trips (universal items) ──────────────────────────────────────────
  { name: "Fishing licence", category: "logistics", tripType: "all", itemName: "Valid state fishing licence (check QLD / NSW requirements)", quantity: 1, isEssential: true },
  { name: "Sun protection", category: "clothing", tripType: "all", itemName: "Sun protection — SPF50+ sunscreen, polarised sunnies, UV shirt & wide-brim hat", quantity: 1, isEssential: true },
  { name: "Gloves", category: "clothing", tripType: "all", itemName: "Fishing gloves (sun and grip protection)", quantity: 1, isEssential: false },
  { name: "Pliers / multi-tool", category: "tackle", tripType: "all", itemName: "Long-nose pliers and hook remover", quantity: 1, isEssential: true },
  { name: "Line scissors / braid cutters", category: "tackle", tripType: "all", itemName: "Sharp braid scissors", quantity: 1, isEssential: true },
  { name: "Scales", category: "tackle", tripType: "all", itemName: "Digital fishing scales (0–30kg)", quantity: 1, isEssential: false },
  { name: "Ruler / measuring tape", category: "tackle", tripType: "all", itemName: "Folding fish ruler or measure tape", quantity: 1, isEssential: true },
  { name: "First aid kit", category: "safety", tripType: "all", itemName: "Marine first aid kit with fish hook removal", quantity: 1, isEssential: true },
  { name: "Life jackets", category: "safety", tripType: "all", itemName: "Life jackets / PFDs for all crew (USCG/AMSA approved)", quantity: 1, isEssential: true },
  { name: "EPIRB or PLB", category: "safety", tripType: "all", itemName: "EPIRB (boat) or PLB (personal) — registered with AMSA", quantity: 1, isEssential: true },
  { name: "VHF radio", category: "safety", tripType: "all", itemName: "VHF marine radio (handheld or fixed-mount)", quantity: 1, isEssential: true },
  { name: "Flares", category: "safety", tripType: "all", itemName: "Marine flare kit (within expiry date)", quantity: 1, isEssential: true },
  { name: "Phone (charged)", category: "safety", tripType: "all", itemName: "Fully charged mobile in waterproof case", quantity: 1, isEssential: true },
  { name: "Water", category: "food", tripType: "all", itemName: "Drinking water 2L per person per day", quantity: 1, isEssential: true },
  { name: "Snacks and meals", category: "food", tripType: "all", itemName: "High-energy snacks, sandwiches, and easy-to-eat meals", quantity: 1, isEssential: true },
  { name: "Seasickness tablets", category: "food", tripType: "all", itemName: "Motion sickness tablets (Kwells or Stugeron) — take night before", quantity: 1, isEssential: false },
  { name: "Esky with ice", category: "food", tripType: "all", itemName: "Esky with ice for catch and drinks", quantity: 1, isEssential: true },
  { name: "Fish cleaning supplies", category: "logistics", tripType: "all", itemName: "Fillet knife, cutting board, fish bags, zip-lock bags", quantity: 1, isEssential: true },
  { name: "Camera / GoPro", category: "logistics", tripType: "all", itemName: "Camera or GoPro for catch photos", quantity: 1, isEssential: false },
  { name: "Torch / headlamp", category: "logistics", tripType: "all", itemName: "Waterproof torch or headlamp (for early starts / night fishing)", quantity: 1, isEssential: false },
];
