export const REGIONS = [
  // ── New Zealand — North Island ────────────────────────────────────────────
  { slug: "bay-of-islands", name: "Bay of Islands", state: "NZ", zone: "nz_north_island", latitude: -35.2667, longitude: 174.1333, description: "NZ's premier big-game fishing destination. World-class marlin in summer, year-round snapper and kingfish in the 144-island bay system. Cape Brett and the Poor Knights Islands hold trophy yellowtail kingfish and hapuku." },
  { slug: "auckland-hauraki-gulf", name: "Auckland / Hauraki Gulf", state: "NZ", zone: "nz_north_island", latitude: -36.8485, longitude: 174.7633, description: "New Zealand's snapper capital. The Hauraki Gulf teems with snapper year-round, with yellowtail kingfish over the reefs. Great Barrier and Waiheke Islands extend the options. Close-range yellowfin and bluefin tuna in summer." },
  { slug: "tauranga-bay-of-plenty", name: "Tauranga / Bay of Plenty", state: "NZ", zone: "nz_north_island", latitude: -37.6878, longitude: 176.1651, description: "Major NZ sport fishing port. Snapper and kingfish on the near-shore reefs; striped and blue marlin out wide in summer. Mayor Island is a world-class light-tackle destination for giant yellowtail kingfish." },
  { slug: "gisborne-east-cape", name: "Gisborne / East Cape", state: "NZ", zone: "nz_north_island", latitude: -38.6623, longitude: 178.0176, description: "Remote east coast with outstanding snapper, blue moki, and tarakihi. First region in the world to see each new day. Big surf beaches produce kahawai and trevally. Deep water close to shore." },
  { slug: "napier-hawkes-bay", name: "Napier / Hawke's Bay", state: "NZ", zone: "nz_north_island", latitude: -39.4928, longitude: 176.9120, description: "Snapper and kahawai year-round in Hawke's Bay. Yellowtail kingfish congregate over offshore reefs in summer. Pacific bluefin tuna visit the canyon grounds offshore." },
  { slug: "wellington-cook-strait", name: "Wellington / Cook Strait", state: "NZ", zone: "nz_north_island", latitude: -41.2865, longitude: 174.7762, description: "Cook Strait's ferocious tidal rips concentrate baitfish and predators. Exceptional blue cod, tarakihi, and snapper. Hapuku and bluenose from deep water channels. One of NZ's most productive but challenging fisheries." },

  // ── New Zealand — South Island ────────────────────────────────────────────
  { slug: "nelson-tasman", name: "Nelson / Tasman Bay", state: "NZ", zone: "nz_south_island", latitude: -41.2706, longitude: 173.2840, description: "Blue cod and snapper in sheltered Tasman Bay. Golden Bay produces large snapper on the remote northern flats. Inland rivers hold outstanding brown trout. Salmon in the Motueka River in autumn." },
  { slug: "marlborough-sounds", name: "Marlborough Sounds", state: "NZ", zone: "nz_south_island", latitude: -41.5123, longitude: 174.0650, description: "Queen Charlotte Sound and Pelorus Sound deliver superb blue cod and snapper fishing in sheltered waterways. Yellowtail kingfish patrol the sound entrances in summer. Remote bays accessible only by water." },
  { slug: "kaikoura", name: "Kaikōura", state: "NZ", zone: "nz_south_island", latitude: -42.4000, longitude: 173.6833, description: "Deep water rises steeply close to shore, producing exceptional hapuku (groper), blue cod, and tarakihi. Yellowtail kingfish arrive in summer. Dramatic Kaikōura Range backdrop. Access to spectacular canyon-edge fishing." },
  { slug: "christchurch-canterbury", name: "Christchurch / Canterbury", state: "NZ", zone: "nz_south_island", latitude: -43.5321, longitude: 172.6362, description: "Canterbury Bight delivers blue cod, tarakihi, and snapper. The Waimakariri and Rakaia rivers run world-class salmon runs in autumn. Pristine braided river trout fishing nearby in the foothills and high country." },
  { slug: "akaroa-banks-peninsula", name: "Akaroa / Banks Peninsula", state: "NZ", zone: "nz_south_island", latitude: -43.8030, longitude: 172.9630, description: "Blue cod hotspot in the dramatic volcanic harbour bays. Tarakihi and snapper on the outer shelf. Unique enclosed harbour fishing. Scenic day-trip destination from Christchurch with productive inshore reefs." },
  { slug: "queenstown-fiordland", name: "Queenstown / Fiordland", state: "NZ", zone: "nz_south_island", latitude: -45.0312, longitude: 168.6626, description: "World-famous trout fishing in Lake Wakatipu, Wanaka, and remote Fiordland lakes. Exceptional wilderness fly fishing. Milford Sound and Doubtful Sound produce hapuku, blue cod, and groper in spectacular deep-fiord settings." },
  { slug: "dunedin-otago", name: "Dunedin / Otago", state: "NZ", zone: "nz_south_island", latitude: -45.8788, longitude: 170.5028, description: "Blue cod in Otago Harbour and the nearby coast. Hapuku (groper) on the outer continental shelf. Salmon in the Clutha and Taieri rivers. Rock and beach fishing for blue moki and kahawai around the Otago Peninsula." },
  { slug: "invercargill-southland", name: "Invercargill / Southland", state: "NZ", zone: "nz_south_island", latitude: -46.4132, longitude: 168.3538, description: "The Bluff is an iconic NZ blue cod destination. Stewart Island access for deep-water hapuku, blue cod, and groper. Oreti Beach for surf casting. Salmon in the Mataura system. Remote and wild southern fishing at its finest." },
  { slug: "west-coast-greymouth", name: "West Coast / Greymouth", state: "NZ", zone: "nz_south_island", latitude: -42.4502, longitude: 171.2100, description: "Wild, remote west coast with challenging bar crossings and rugged terrain. Blue cod, tarakihi, and hapuku offshore. Exceptional brown trout fishing in the Grey, Buller, and Hokitika rivers. Uncrowded and pristine wilderness fishing." },

  // ── Far North QLD ─────────────────────────────────────────────────────────
  { slug: "cairns", name: "Cairns", state: "QLD", zone: "far_north_qld", latitude: -16.9186, longitude: 145.7781, description: "World-renowned for black marlin season and Great Barrier Reef reef fishing. The Ribbon Reefs and Coral Sea produce trophy pelagics Sep–Dec." },
  { slug: "port-douglas", name: "Port Douglas", state: "QLD", zone: "far_north_qld", latitude: -16.4844, longitude: 145.4650, description: "Gateway to the Low Isles and outer Barrier Reef. Excellent coral trout, red emperor, and marlin options year-round." },
  { slug: "cooktown", name: "Cooktown", state: "QLD", zone: "far_north_qld", latitude: -15.4711, longitude: 145.2503, description: "Remote far-north fishing with outstanding GT, barramundi, and offshore reef action. Access to Lizard Island and the Ribbon Reefs." },
  { slug: "townsville", name: "Townsville", state: "QLD", zone: "far_north_qld", latitude: -19.2590, longitude: 146.8169, description: "Magnetic Island and the nearby reefs deliver year-round reef fishing. Strong Spanish mackerel runs winter through spring." },

  // ── Central QLD ───────────────────────────────────────────────────────────
  { slug: "mackay", name: "Mackay", state: "QLD", zone: "central_qld", latitude: -21.1411, longitude: 149.1860, description: "Prime Spanish mackerel grounds in central Queensland. The Coral Sea reefs and Whitsunday passages hold excellent pelagic action." },
  { slug: "airlie-beach", name: "Airlie Beach / Whitsundays", state: "QLD", zone: "central_qld", latitude: -20.2686, longitude: 148.7183, description: "The Whitsunday Islands offer sheltered reef fishing and strong pelagic action outside. Great mahi-mahi and wahoo trolling." },
  { slug: "yeppoon", name: "Yeppoon", state: "QLD", zone: "central_qld", latitude: -23.1298, longitude: 150.7452, description: "Keppel Bay and the Keppel Islands provide excellent reef fishing. Strong barramundi estuary options in the Fitzroy River system." },
  { slug: "gladstone", name: "Gladstone", state: "QLD", zone: "central_qld", latitude: -23.8427, longitude: 151.2556, description: "Access to Capricorn and Bunker groups reefs. Strong coral trout, snapper, and pelagic fishery. Good estuary options." },

  // ── Southeast QLD ─────────────────────────────────────────────────────────
  { slug: "hervey-bay", name: "Hervey Bay", state: "QLD", zone: "southeast_qld", latitude: -25.2908, longitude: 152.8407, description: "Protected bay fishing for snapper, tuna, cobia, and large pelagics. Fraser Island estuary fishing for tailor and flathead." },
  { slug: "fraser-coast", name: "Fraser Coast", state: "QLD", zone: "southeast_qld", latitude: -25.5100, longitude: 152.7050, description: "Fraser Island lake and beach systems, plus offshore Breaksea Spit for tuna and mahi-mahi. Strong tailor and whiting." },
  { slug: "sunshine-coast", name: "Sunshine Coast", state: "QLD", zone: "southeast_qld", latitude: -26.6500, longitude: 153.0667, description: "Mixed fishery with strong inshore cobia, pelagic tuna schools, and good flathead estuaries in the Noosa and Maroochy systems." },
  { slug: "brisbane-moreton-bay", name: "Brisbane / Moreton Bay", state: "QLD", zone: "southeast_qld", latitude: -27.3818, longitude: 153.1399, description: "Moreton Bay is a world-class snapper, flathead, and whiting destination. Offshore pelagics from Cape Moreton including yellowfin tuna." },
  { slug: "gold-coast", name: "Gold Coast", state: "QLD", zone: "southeast_qld", latitude: -28.0167, longitude: 153.4000, description: "The Gold Coast broadwater and Seaway produce flathead, snapper, and jewfish. Offshore canyons hold yellowfin tuna and marlin." },

  // ── NSW Coastal ───────────────────────────────────────────────────────────
  { slug: "ballina-byron-bay", name: "Ballina / Byron Bay", state: "NSW", zone: "nsw", latitude: -28.8656, longitude: 153.5656, description: "The Richmond River estuary delivers mulloway and flathead. Offshore Byron Bay holds tuna, mahi-mahi, and wahoo. Strong Spanish mackerel autumn runs." },
  { slug: "south-west-rocks", name: "South West Rocks", state: "NSW", zone: "nsw", latitude: -30.8800, longitude: 153.0400, description: "Trial Bay and the surrounding reefs produce excellent snapper, kingfish, and tuna. Smoky Cape is a known pelagic aggregation point." },
  { slug: "coffs-harbour", name: "Coffs Harbour", state: "NSW", zone: "nsw", latitude: -30.2986, longitude: 153.1094, description: "The Solitary Islands Marine Park produces excellent reef fishing. Strong yellowfin tuna and mahi-mahi in blue water. Good estuary bream and flathead." },
  { slug: "port-macquarie", name: "Port Macquarie", state: "NSW", zone: "nsw", latitude: -31.4333, longitude: 152.9000, description: "Hastings River estuary provides excellent flathead, bream, and jewfish. Offshore holds tuna and marlin during warmer months." },
  { slug: "port-stephens", name: "Port Stephens", state: "NSW", zone: "nsw", latitude: -32.7200, longitude: 152.1000, description: "One of NSW's premier destinations. Deep-water port with excellent flathead, bream, and luderick inside. Offshore canyon delivers yellowfin tuna and marlin." },
  { slug: "newcastle", name: "Newcastle", state: "NSW", zone: "nsw", latitude: -32.9267, longitude: 151.7789, description: "Hunter River estuary and offshore waters produce great jewfish, snapper, and kingfish. Major yellowfin tuna aggregations in summer." },
  { slug: "lake-macquarie", name: "Lake Macquarie", state: "NSW", zone: "nsw", latitude: -33.0700, longitude: 151.6000, description: "Australia's largest coastal saltwater lake. Exceptional flathead, bream, mullet, and luderick. Swansea channel connection delivers pelagic access." },
  { slug: "hawkesbury-river", name: "Hawkesbury River", state: "NSW", zone: "nsw", latitude: -33.5700, longitude: 151.2700, description: "Major river system north of Sydney with excellent flathead, bream, jewfish, and Australian bass. Mangrove systems hold mulloway on tide changes." },
  { slug: "sydney", name: "Sydney", state: "NSW", zone: "nsw", latitude: -33.8688, longitude: 151.2093, description: "Sydney Harbour flathead and bream, plus offshore kingfish and yellowfin tuna. The canyon system south of the heads holds blue and black marlin." },
  { slug: "wollongong", name: "Wollongong", state: "NSW", zone: "nsw", latitude: -34.4300, longitude: 150.8900, description: "Rock fishing capital of NSW. Close offshore canyon access produces kingfish and tuna. Shellharbour and Lake Illawarra hold flathead and bream." },
  { slug: "jervis-bay", name: "Jervis Bay", state: "NSW", zone: "nsw", latitude: -35.1500, longitude: 150.7000, description: "Crystal-clear bay with excellent snapper, kingfish, and flathead. Offshore Jervis holds tuna, mahi-mahi, and marlin in season." },
  { slug: "ulladulla", name: "Ulladulla", state: "NSW", zone: "nsw", latitude: -35.3500, longitude: 150.4700, description: "Productive offshore grounds with excellent yellowfin tuna and mahi-mahi. The harbour and Pigeon Bay hold bream, flathead, and jewfish." },
  { slug: "batemans-bay", name: "Batemans Bay", state: "NSW", zone: "nsw", latitude: -35.7072, longitude: 150.1757, description: "Clyde River estuary with outstanding flathead, bream, and jewfish. Offshore produces snapper and tuna during summer months." },
  { slug: "narooma", name: "Narooma", state: "NSW", zone: "nsw", latitude: -36.2200, longitude: 150.1300, description: "Wagonga Inlet holds bream, flathead, and luderick. Offshore delivers excellent snapper and tuna. Montague Island draws pelagics and seals." },
  { slug: "tathra-merimbula", name: "Tathra / Merimbula", state: "NSW", zone: "nsw", latitude: -36.7300, longitude: 149.9000, description: "Two Lakes at Merimbula and the Tathra wharf are local icons. Snapper, flathead, and bream in the lakes. Offshore pelagics in summer." },
  { slug: "eden", name: "Eden", state: "NSW", zone: "nsw", latitude: -37.0653, longitude: 149.9019, description: "Twofold Bay is famous for tuna, kingfish, and marlin. The deep water canyon is one of the best big-game fishing destinations in Australia." },

  // ── Lord Howe Island ──────────────────────────────────────────────────────
  { slug: "lord-howe-island", name: "Lord Howe Island", state: "NSW", zone: "lord_howe", latitude: -31.5500, longitude: 159.0800, description: "World Heritage island 600km offshore. Exceptional kingfish, trevally, wahoo, and coral reef fishing. Remote and pristine — world-class light-tackle action." },

  // ── Victoria Coastal ──────────────────────────────────────────────────────
  { slug: "port-phillip-bay", name: "Port Phillip Bay / Melbourne", state: "VIC", zone: "vic_coast", latitude: -37.8136, longitude: 144.9631, description: "Victoria's largest bay offers year-round snapper, flathead, whiting, and bream. Rips and artificial reefs attract kingfish and southern bluefin tuna in summer." },
  { slug: "mornington-peninsula", name: "Mornington Peninsula", state: "VIC", zone: "vic_coast", latitude: -38.2000, longitude: 145.0300, description: "The Port Phillip side holds flathead and bream; Bass Strait side offers snapper and excellent kingfish in summer. Strong gummy shark fishery." },
  { slug: "phillip-island", name: "Phillip Island", state: "VIC", zone: "vic_coast", latitude: -38.5000, longitude: 145.2000, description: "Strong snapper and barracouta. Western Entrance and the Nobbies are productive for SBT in summer. Good rock fishing for salmon and sweep." },
  { slug: "westernport-bay", name: "Westernport Bay", state: "VIC", zone: "vic_coast", latitude: -38.3500, longitude: 145.3500, description: "Excellent snapper and whiting bay. Channels and flats around French Island produce great flathead and bream year-round. Good gummy shark at night." },
  { slug: "wilsons-promontory", name: "Wilsons Promontory", state: "VIC", zone: "vic_coast", latitude: -39.1300, longitude: 146.3700, description: "The southernmost tip of mainland Australia. Remote offshore reefs hold snapper, blue-eye trevalla, and striped trumpeter. SBT and kingfish in summer." },
  { slug: "lakes-entrance", name: "Lakes Entrance / Gippsland", state: "VIC", zone: "vic_coast", latitude: -37.8800, longitude: 147.9800, description: "Gippsland Lakes is one of Australia's largest lake systems. Bream, flathead, and estuary perch inside. Offshore holds snapper, blue-eye trevalla, and SBT." },
  { slug: "mallacoota", name: "Mallacoota", state: "VIC", zone: "vic_coast", latitude: -37.5700, longitude: 149.7500, description: "Remote and pristine, Mallacoota Inlet holds exceptional bream, flathead, and estuary perch. Offshore reefs deliver snapper and blue-eye trevalla." },
  { slug: "apollo-bay", name: "Apollo Bay", state: "VIC", zone: "vic_coast", latitude: -38.7500, longitude: 143.6700, description: "Great Ocean Road fishing hub. Offshore reefs hold snapper and blue-eye. Rock and jetty fishing for salmon and sweep. SBT from charters in summer." },
  { slug: "portland-vic", name: "Portland", state: "VIC", zone: "vic_coast", latitude: -38.3400, longitude: 141.6000, description: "Victoria's main southern bluefin tuna port. SBT charters run summer through autumn. Offshore reefs hold blue-eye trevalla, snapper, and gummy shark." },
  { slug: "warrnambool", name: "Warrnambool", state: "VIC", zone: "vic_coast", latitude: -38.3800, longitude: 142.4800, description: "Surf coast fishing for salmon and tailor. Lady Bay and Hopkins River hold bream and flathead. Offshore snapper and gummy shark." },

  // ── Tasmania ──────────────────────────────────────────────────────────────
  { slug: "hobart", name: "Hobart / D'Entrecasteaux Channel", state: "TAS", zone: "tas", latitude: -42.8800, longitude: 147.3300, description: "Tasmania's capital on the Derwent Estuary with bream, flathead, and estuary perch. D'Entrecasteaux Channel offers snapper and blue-eye trevalla. Sea-run trout are a specialty." },
  { slug: "st-helens", name: "St Helens", state: "TAS", zone: "tas", latitude: -41.3200, longitude: 148.2500, description: "Northeast Tasmania's premier fishing hub. Exceptional bluefin tuna from St Helens Point. Nearby reefs and Georges Bay hold snapper, flathead, and bream." },
  { slug: "bicheno", name: "Bicheno", state: "TAS", zone: "tas", latitude: -41.8700, longitude: 148.3000, description: "Protected east-coast location with good reef fishing. Snapper, bastard trumpeter, and blue warehou are common. Offshore for blue-eye and striped trumpeter." },
  { slug: "bruny-island", name: "Bruny Island", state: "TAS", zone: "tas", latitude: -43.4500, longitude: 147.3800, description: "Remote island south of Hobart. Excellent snapper, blue-eye trevalla, and striped trumpeter. Wild sea-run trout in the Adventure Bay area." },
  { slug: "strahan", name: "Strahan / Macquarie Harbour", state: "TAS", zone: "tas", latitude: -42.1500, longitude: 145.3300, description: "West coast fishing with Macquarie Harbour holding exceptional sea-run trout. Offshore for blue-eye and striped trumpeter in season." },
  { slug: "devonport", name: "Devonport / Bass Strait", state: "TAS", zone: "tas", latitude: -41.1800, longitude: 146.3500, description: "Northern Tasmania facing Bass Strait. Good snapper and flathead in the Mersey River. Offshore delivers school and bluefin tuna in season." },
  { slug: "launceston-tamar", name: "Launceston / Tamar River", state: "TAS", zone: "tas", latitude: -41.4300, longitude: 147.1300, description: "The Tamar estuary holds bream, flathead, and estuary perch. Sea-run trout run the river in autumn. Bass Strait offshore for tuna and snapper." },
  { slug: "port-arthur", name: "Port Arthur / Tasman Peninsula", state: "TAS", zone: "tas", latitude: -43.1500, longitude: 147.8500, description: "Spectacular cliff fishing for striped trumpeter and blue warehou. Offshore deep reefs hold blue-eye trevalla and diverse reef species." },

  // ── Murray-Darling Freshwater ─────────────────────────────────────────────
  { slug: "murray-river-albury", name: "Murray River (Albury)", state: "NSW", zone: "murray_darling", latitude: -36.0700, longitude: 146.9200, description: "The upper Murray around Albury-Wodonga is prime Murray cod and golden perch country. Snags, rock bars, and deep pools hold big cod throughout the system." },
  { slug: "murray-river-echuca", name: "Murray River (Echuca)", state: "VIC", zone: "murray_darling", latitude: -36.1400, longitude: 144.7500, description: "Historic paddle steamer town on the Murray. Excellent Murray cod with trophy fish common. Golden perch and catfish year-round." },
  { slug: "murray-river-mildura", name: "Murray River (Mildura)", state: "VIC", zone: "murray_darling", latitude: -34.1900, longitude: 142.1600, description: "Lower Murray with warm water and excellent golden perch. Lake Cullulleraine nearby. Trophy Murray cod in the deeper pools and log snags." },
  { slug: "lake-hume", name: "Lake Hume", state: "NSW", zone: "murray_darling", latitude: -36.1000, longitude: 147.0300, description: "Large reservoir on the upper Murray. Excellent golden perch, Murray cod, and trout. Rocky points and submerged timber hold fish year-round." },
  { slug: "lake-mulwala", name: "Lake Mulwala / Yarrawonga", state: "VIC", zone: "murray_darling", latitude: -35.9800, longitude: 146.0000, description: "Impoundment on the Murray at Yarrawonga. Famous for large Murray cod and golden perch. Fallen trees and rock walls provide excellent structure." },
  { slug: "murrumbidgee-river", name: "Murrumbidgee River", state: "NSW", zone: "murray_darling", latitude: -34.8200, longitude: 146.0400, description: "Major Murray-Darling tributary with good Murray cod and golden perch. The Wagga Wagga to Hay stretch has significant snag habitat for big cod." },
  { slug: "macquarie-river", name: "Macquarie River", state: "NSW", zone: "murray_darling", latitude: -31.9700, longitude: 148.6600, description: "Western NSW river system with good golden perch and Murray cod. The Macquarie Marshes hold healthy populations in flood seasons." },
  { slug: "darling-river-bourke", name: "Darling River (Bourke)", state: "NSW", zone: "murray_darling", latitude: -30.0900, longitude: 145.9400, description: "Remote outback fishing on the iconic Darling River. Golden perch, bony bream, and catfish. Best in spring when flood flows activate the system." },

  // ── Alpine / Snowy Mountains / TAS Highlands ──────────────────────────────
  { slug: "lake-eucumbene", name: "Lake Eucumbene", state: "NSW", zone: "alpine", latitude: -36.1300, longitude: 148.7500, description: "Australia's largest inland reservoir. Trophy brown and rainbow trout fishing. Spring bait fishing and autumn fly fishing are highlights of the trout calendar." },
  { slug: "lake-jindabyne", name: "Lake Jindabyne", state: "NSW", zone: "alpine", latitude: -36.4200, longitude: 148.6300, description: "Gateway to Snowy Mountains trout fishing. Brown and rainbow trout with excellent trolling and fly fishing. Surrounded by spectacular mountain scenery." },
  { slug: "snowy-mountains-rivers", name: "Snowy Mountains Rivers", state: "NSW", zone: "alpine", latitude: -36.4000, longitude: 148.3600, description: "World-class fly fishing on the Thredbo, Eucumbene, and Tumut rivers. Wild brown trout in pristine alpine streams — dry fly and nymph territory." },
  { slug: "lake-eildon", name: "Lake Eildon", state: "VIC", zone: "alpine", latitude: -37.1800, longitude: 145.9300, description: "Victoria's largest reservoir. Excellent golden perch, Murray cod, and rainbow trout. Rocky points, creek arms, and the Delatite arm hold fish year-round." },
  { slug: "ovens-king-rivers", name: "Ovens / King Rivers", state: "VIC", zone: "alpine", latitude: -36.7300, longitude: 146.8900, description: "Victorian alpine rivers with wild brown and rainbow trout. The Ovens between Bright and Myrtleford is a fly fishing gem — clear water and challenging fish." },
  { slug: "goulburn-river-vic", name: "Goulburn River (VIC)", state: "VIC", zone: "alpine", latitude: -37.3300, longitude: 145.9100, description: "One of Victoria's premier trout fisheries. The upper Goulburn above Eildon has wild brown trout. Excellent dry fly fishing during the evening rise." },
  { slug: "arthurs-lake-tas", name: "Arthurs Lake", state: "TAS", zone: "alpine", latitude: -41.9900, longitude: 146.9000, description: "Tasmania's premier trout lake. Prolific brown and rainbow trout with famous polaroiding in the shallows. Dun season produces spectacular dry fly fishing." },
  { slug: "lake-st-clair", name: "Lake St Clair", state: "TAS", zone: "alpine", latitude: -42.1100, longitude: 146.1700, description: "Australia's deepest lake in the heart of the World Heritage wilderness. Remote brown and rainbow trout in a spectacular alpine setting." },

  // ── Northern Territory — Top End ──────────────────────────────────────────
  { slug: "darwin", name: "Darwin", state: "NT", zone: "nt_top_end", latitude: -12.4634, longitude: 130.8456, description: "Australia's tropical fishing capital. Darwin Harbour teems with barramundi, mangrove jack, and black jewfish. Offshore reef and pelagic action year-round with trevally, tuna, and sailfish." },
  { slug: "daly-river", name: "Daly River", state: "NT", zone: "nt_top_end", latitude: -13.7500, longitude: 130.6900, description: "Legendary barramundi river system. The Daly produces trophy barra in the build-up and dry season. Also excellent mangrove jack, black jewfish, and threadfin salmon." },
  { slug: "katherine-river", name: "Katherine / Nitmiluk Gorge", state: "NT", zone: "nt_top_end", latitude: -14.4646, longitude: 132.2635, description: "Katherine Gorge delivers spectacular barramundi fishing surrounded by ancient sandstone gorges. Dry season access Jun–Oct brings peak barra runs." },
  { slug: "kakadu", name: "Kakadu / South Alligator River", state: "NT", zone: "nt_top_end", latitude: -12.7000, longitude: 132.4000, description: "World Heritage wetlands with exceptional barramundi. The South Alligator, East Alligator, and tidal estuaries produce some of Australia's most prolific barra fishing." },
  { slug: "arnhem-land", name: "Nhulunbuy / Arnhem Land", state: "NT", zone: "nt_top_end", latitude: -12.1833, longitude: 136.7667, description: "Remote coastal wilderness with outstanding reef and estuary fishing. GT, Spanish mackerel, queenfish, and barramundi are all targeted. Permit required to access." },

  // ── Northern Territory — Gulf ─────────────────────────────────────────────
  { slug: "groote-eylandt", name: "Groote Eylandt", state: "NT", zone: "nt_gulf", latitude: -13.9333, longitude: 136.4167, description: "Large island in the Gulf of Carpentaria renowned for red emperor, coral trout, and barramundi. Superb GT and queenfish in the tidal channels." },
  { slug: "borroloola", name: "Borroloola / McArthur River", state: "NT", zone: "nt_gulf", latitude: -16.0753, longitude: 136.2985, description: "Remote Gulf of Carpentaria fishing hub. The McArthur River and Sir Edward Pellew Islands provide world-class barramundi, black jewfish, and reef species." },
  { slug: "roper-river", name: "Roper River / Numbulwar", state: "NT", zone: "nt_gulf", latitude: -14.7167, longitude: 135.4333, description: "Trophy barramundi country in eastern Arnhem Land. Large tidal estuary system with resident barra, mangrove jack, and threadfin salmon." },

  // ── Western Australia — Kimberley ─────────────────────────────────────────
  { slug: "broome", name: "Broome / Kimberley Coast", state: "WA", zone: "wa_kimberley", latitude: -17.9614, longitude: 122.2359, description: "Spectacular tidal ranges and remote coastline. Excellent barramundi in the freshwater creek systems, plus queenfish, threadfin salmon, and offshore reef and pelagics." },
  { slug: "kununurra", name: "Kununurra / Ord River", state: "WA", zone: "wa_kimberley", latitude: -15.7667, longitude: 128.7333, description: "Lake Argyle and the Ord River system deliver massive barramundi and saratoga. One of Australia's premier freshwater fishing destinations in a remote Kimberley setting." },
  { slug: "derby", name: "Derby / King Sound", state: "WA", zone: "wa_kimberley", latitude: -17.3000, longitude: 123.6333, description: "Some of the highest tidal ranges in the world create explosive estuary fishing. Barramundi, queenfish, and threadfin salmon fill the tidal creeks and river mouths." },
  { slug: "fitzroy-crossing", name: "Fitzroy Crossing / Fitzroy River", state: "WA", zone: "wa_kimberley", latitude: -18.1833, longitude: 125.5833, description: "Iconic Kimberley river with large barramundi and freshwater crocodile country. Excellent saratoga and bream fishing in the pools and tidal reaches." },

  // ── Western Australia — Pilbara / Ningaloo ────────────────────────────────
  { slug: "exmouth-ningaloo", name: "Exmouth / Ningaloo", state: "WA", zone: "wa_pilbara", latitude: -21.9322, longitude: 114.1244, description: "World-famous Ningaloo Reef offers outstanding coral trout, spangled emperor, and sailfish. GT on the flats, whale sharks seasonally, and outstanding shore-based fishing." },
  { slug: "karratha-dampier", name: "Karratha / Dampier", state: "WA", zone: "wa_pilbara", latitude: -20.7362, longitude: 116.8463, description: "Montebello Islands and the Dampier Archipelago deliver remote reef fishing for coral trout, red emperor, and queenfish. Excellent offshore trolling grounds." },
  { slug: "port-hedland", name: "Port Hedland / 80-Mile Beach", state: "WA", zone: "wa_pilbara", latitude: -20.3109, longitude: 118.5769, description: "80-Mile Beach is one of WA's great beach fishing locations for whiting and tailor. Offshore reef and pelagic fishing for Spanish mackerel and tuna." },
  { slug: "montebello-islands", name: "Montebello Islands", state: "WA", zone: "wa_pilbara", latitude: -20.4500, longitude: 115.5500, description: "Remote island chain off the Pilbara coast. World-class GT, Spanish mackerel, coral trout, and red emperor fishing. Accessible only by live-aboard charter." },

  // ── Western Australia — Mid West ──────────────────────────────────────────
  { slug: "geraldton", name: "Geraldton / Abrolhos Islands", state: "WA", zone: "wa_mid_west", latitude: -28.7744, longitude: 114.6089, description: "The Abrolhos Islands are WA's premier fishing destination. Outstanding dhufish, baldchin groper, pink snapper, and coral trout on pristine reef systems." },
  { slug: "shark-bay", name: "Shark Bay / Monkey Mia", state: "WA", zone: "wa_mid_west", latitude: -25.9967, longitude: 113.7194, description: "UNESCO World Heritage site with excellent snapper, whiting, and trevally. Remote fishing in pristine protected waters. Tiger sharks common in season." },
  { slug: "carnarvon", name: "Carnarvon / Shark Bay North", state: "WA", zone: "wa_mid_west", latitude: -24.8667, longitude: 113.6667, description: "Gascoyne River mouth and nearby coast produce excellent snapper, mulloway, and tailor. The Ningaloo coast begins nearby with increasing tropical species." },

  // ── Western Australia — Southwest ─────────────────────────────────────────
  { slug: "perth-rottnest", name: "Perth / Rottnest Island", state: "WA", zone: "wa_southwest", latitude: -31.9505, longitude: 115.8605, description: "Perth metro fishing for dhufish, pink snapper, and baldchin groper on the offshore reefs. Rottnest Island is a world-class fishing destination with stunning reef and pelagic action." },
  { slug: "mandurah", name: "Mandurah / Peel Inlet", state: "WA", zone: "wa_southwest", latitude: -32.5339, longitude: 115.7234, description: "Peel Inlet and Harvey Estuary deliver excellent bream, black bream, and flathead. Offshore access to snapper and dhufish reefs. Good King George whiting in season." },
  { slug: "bunbury-margaret-river", name: "Bunbury / Margaret River", state: "WA", zone: "wa_southwest", latitude: -33.3271, longitude: 115.6391, description: "Southwest WA coast with snapper, pink snapper, and dhufish offshore. Strong surfer's beach tailor and salmon runs. Trout stocking in the nearby Margaret River." },
  { slug: "albany", name: "Albany / Great Southern", state: "WA", zone: "wa_southwest", latitude: -35.0275, longitude: 117.8840, description: "King Sound and Princess Royal Harbour offer fantastic southern species. Dhufish, pink snapper, and blue-eye trevalla offshore. Excellent southern bluefin tuna access." },
  { slug: "esperance", name: "Esperance / South Coast", state: "WA", zone: "wa_southwest", latitude: -33.8610, longitude: 121.8898, description: "Remote and pristine south coast with excellent pink snapper, dhufish, and southern bluefin tuna. The Recherche Archipelago islands hold superb reef fishing." },

  // ── South Australia — Spencer Gulf ───────────────────────────────────────
  { slug: "whyalla", name: "Whyalla / Upper Spencer Gulf", state: "SA", zone: "sa_spencer_gulf", latitude: -33.0333, longitude: 137.5833, description: "Giant Australian cuttlefish aggregation (winter). Excellent snapper and King George whiting in Spencer Gulf. Good mulloway from beaches and rock platforms." },
  { slug: "port-augusta", name: "Port Augusta", state: "SA", zone: "sa_spencer_gulf", latitude: -32.4928, longitude: 137.7657, description: "Head of Spencer Gulf with excellent snapper and King George whiting. The Spencer Gulf system produces some of SA's best recreational fishing year-round." },
  { slug: "yorke-peninsula", name: "Yorke Peninsula", state: "SA", zone: "sa_spencer_gulf", latitude: -34.5000, longitude: 137.6000, description: "Excellent King George whiting and snapper throughout the gulf waters. Arno Bay and Marion Bay are well-known hotspots. Southern bluefin tuna accessible offshore." },

  // ── South Australia — South Coast ────────────────────────────────────────
  { slug: "adelaide-gulf-st-vincent", name: "Adelaide / Gulf St Vincent", state: "SA", zone: "sa_south", latitude: -34.9285, longitude: 138.6007, description: "The gulf produces excellent snapper in winter, with King George whiting year-round. Beach fishing for mulloway and salmon. Offshore tuna during summer." },
  { slug: "port-lincoln", name: "Port Lincoln / Eyre Peninsula", state: "SA", zone: "sa_south", latitude: -34.7207, longitude: 135.8596, description: "Tuna Capital of Australia. Southern bluefin tuna cage diving and sport fishing. Excellent dhufish, snapper, and King George whiting on superb offshore reefs." },
  { slug: "coffin-bay", name: "Coffin Bay / Elliston", state: "SA", zone: "sa_south", latitude: -34.4000, longitude: 135.4600, description: "Pristine waters on the Eyre Peninsula with excellent King George whiting, snapper, and southern bluefin tuna. Remote and uncrowded with world-class oysters." },
  { slug: "kangaroo-island", name: "Kangaroo Island", state: "SA", zone: "sa_south", latitude: -35.8000, longitude: 137.2000, description: "SA's premier fishing island. Southern bluefin tuna, snapper, King George whiting, and excellent rock fishing for salmon and sweep. Remote and pristine waters." },
  { slug: "coorong", name: "Coorong / Murray Mouth", state: "SA", zone: "sa_south", latitude: -36.1000, longitude: 139.5500, description: "Unique lagoon system at the Murray mouth. Excellent mulloway (jewfish), bream, and estuary species. Renowned Murray cod and golden perch in the lower Murray reaches." },
  { slug: "victor-harbor", name: "Victor Harbor / Fleurieu Peninsula", state: "SA", zone: "sa_south", latitude: -35.5523, longitude: 138.6173, description: "Encounter Bay and the Fleurieu Peninsula produce snapper, King George whiting, and mulloway. Southern bluefin tuna visit offshore in summer." },

  // ── Islands ───────────────────────────────────────────────────────────────
  { slug: "christmas-island", name: "Christmas Island", state: "External Territory", zone: "christmas_island", latitude: -10.4833, longitude: 105.6333, description: "Remote Indian Ocean island world-famous for giant trevally on fly and lure. Also bonefish, milkfish, wahoo, yellowfin tuna, and mahi-mahi around the island. Bucket-list light-tackle destination." },
  { slug: "cocos-keeling-islands", name: "Cocos (Keeling) Islands", state: "External Territory", zone: "cocos_islands", latitude: -12.1167, longitude: 96.9000, description: "Tiny Indian Ocean atoll with extraordinary GT, bonefish, and tuna fishing. Crystal-clear lagoon flats and deep blue water drop-offs. One of the world's most remote fishing destinations." },
];
