export const REGIONS = [
  // ── Far North QLD ─────────────────────────────────────────────────────────
  { slug: "cairns", name: "Cairns", state: "QLD", zone: "far_north_qld", latitude: -16.9186, longitude: 145.7781, description: "World-renowned for black marlin season and Great Barrier Reef reef fishing. The Ribbon Reefs and Coral Sea produce trophy pelagics Sep–Dec." },
  { slug: "port-douglas", name: "Port Douglas", state: "QLD", zone: "far_north_qld", latitude: -16.4844, longitude: 145.4650, description: "Gateway to the Low Isles and outer Barrier Reef. Excellent coral trout, red emperor, and marlin options year-round." },
  { slug: "cooktown", name: "Cooktown", state: "QLD", zone: "far_north_qld", latitude: -15.4711, longitude: 145.2503, description: "Remote far-north fishing with outstanding GT, barramundi, and offshore reef action. Access to Lizard Island and the Ribbon Reefs." },
  { slug: "townsville", name: "Townsville", state: "QLD", zone: "far_north_qld", latitude: -19.2590, longitude: 146.8169, description: "Magnetic Island and the nearby reefs deliver year-round reef fishing. Strong Spanish mackerel runs winter through spring." },

  // ── Central QLD ───────────────────────────────────────────────────────────
  { slug: "mackay", name: "Mackay", state: "QLD", zone: "central_qld", latitude: -21.1411, longitude: 149.1860, description: "Prime Spanish mackerel grounds in central Queensland. The Coral Sea reefs and Whitsunday passages hold excellent pelagic action." },
  { slug: "airlie-beach", name: "Airlie Beach / Whitsundays", state: "QLD", zone: "central_qld", latitude: -20.2686, longitude: 148.7183, description: "The Whitsunday Islands offer sheltered reef fishing and strong pelagic action outside. Great mahi-mahi and wahoo trolling." },
  { slug: "yeppoon", name: "Yeppoon", state: "QLD", zone: "central_qld", latitude: -23.1298, longitude: 150.7452, description: "Keppel Bay and the Keppel Islands provide excellent reef fishing. Strong barramundi estuary options in the Fitzroy River system." },
  { slug: "gladstone", name: "Gladstone", state: "QLD", zone: "central_qld", latitude: -23.8427, longitude: 151.2556, description: "Access to Capricorn and Bunker groups reefs. Strong coral trout, snapper, and pelagic fishery. Good estuary options." },

  // ── Southeast QLD ─────────────────────────────────────────────────────────
  { slug: "hervey-bay", name: "Hervey Bay", state: "QLD", zone: "southeast_qld", latitude: -25.2908, longitude: 152.8407, description: "Protected bay fishing for snapper, tuna, cobia, and large pelagics. Fraser Island estuary fishing for tailor and flathead." },
  { slug: "fraser-coast", name: "Fraser Coast", state: "QLD", zone: "southeast_qld", latitude: -25.5100, longitude: 152.7050, description: "Fraser Island lake and beach systems, plus offshore Breaksea Spit for tuna and mahi-mahi. Strong tailor and whiting." },
  { slug: "sunshine-coast", name: "Sunshine Coast", state: "QLD", zone: "southeast_qld", latitude: -26.6500, longitude: 153.0667, description: "Mixed fishery with strong inshore cobia, pelagic tuna schools, and good flathead estuaries in the Noosa and Maroochy systems." },
  { slug: "brisbane-moreton-bay", name: "Brisbane / Moreton Bay", state: "QLD", zone: "southeast_qld", latitude: -27.3818, longitude: 153.1399, description: "Moreton Bay is a world-class snapper, flathead, and whiting destination. Offshore pelagics from Cape Moreton including yellowfin tuna." },
  { slug: "gold-coast", name: "Gold Coast", state: "QLD", zone: "southeast_qld", latitude: -28.0167, longitude: 153.4000, description: "The Gold Coast broadwater and Seaway produce flathead, snapper, and jewfish. Offshore canyons hold yellowfin tuna and marlin." },

  // ── NSW Coastal ───────────────────────────────────────────────────────────
  { slug: "ballina-byron-bay", name: "Ballina / Byron Bay", state: "NSW", zone: "nsw", latitude: -28.8656, longitude: 153.5656, description: "The Richmond River estuary delivers mulloway and flathead. Offshore Byron Bay holds tuna, mahi-mahi, and wahoo. Strong Spanish mackerel autumn runs." },
  { slug: "south-west-rocks", name: "South West Rocks", state: "NSW", zone: "nsw", latitude: -30.8800, longitude: 153.0400, description: "Trial Bay and the surrounding reefs produce excellent snapper, kingfish, and tuna. Smoky Cape is a known pelagic aggregation point." },
  { slug: "coffs-harbour", name: "Coffs Harbour", state: "NSW", zone: "nsw", latitude: -30.2986, longitude: 153.1094, description: "The Solitary Islands Marine Park produces excellent reef fishing. Strong yellowfin tuna and mahi-mahi in blue water. Good estuary bream and flathead." },
  { slug: "port-macquarie", name: "Port Macquarie", state: "NSW", zone: "nsw", latitude: -31.4333, longitude: 152.9000, description: "Hastings River estuary provides excellent flathead, bream, and jewfish. Offshore holds tuna and marlin during warmer months." },
  { slug: "port-stephens", name: "Port Stephens", state: "NSW", zone: "nsw", latitude: -32.7200, longitude: 152.1000, description: "One of NSW's premier destinations. Deep-water port with excellent flathead, bream, and luderick inside. Offshore canyon delivers yellowfin tuna and marlin." },
  { slug: "newcastle", name: "Newcastle", state: "NSW", zone: "nsw", latitude: -32.9267, longitude: 151.7789, description: "Hunter River estuary and offshore waters produce great jewfish, snapper, and kingfish. Major yellowfin tuna aggregations in summer." },
  { slug: "lake-macquarie", name: "Lake Macquarie", state: "NSW", zone: "nsw", latitude: -33.0700, longitude: 151.6000, description: "Australia's largest coastal saltwater lake. Exceptional flathead, bream, mullet, and luderick. Swansea channel connection delivers pelagic access." },
  { slug: "hawkesbury-river", name: "Hawkesbury River", state: "NSW", zone: "nsw", latitude: -33.5700, longitude: 151.2700, description: "Major river system north of Sydney with excellent flathead, bream, jewfish, and Australian bass. Mangrove systems hold mulloway on tide changes." },
  { slug: "sydney", name: "Sydney", state: "NSW", zone: "nsw", latitude: -33.8688, longitude: 151.2093, description: "Sydney Harbour flathead and bream, plus offshore kingfish and yellowfin tuna. The canyon system south of the heads holds blue and black marlin." },
  { slug: "wollongong", name: "Wollongong", state: "NSW", zone: "nsw", latitude: -34.4300, longitude: 150.8900, description: "Rock fishing capital of NSW. Close offshore canyon access produces kingfish and tuna. Shellharbour and Lake Illawarra hold flathead and bream." },
  { slug: "jervis-bay", name: "Jervis Bay", state: "NSW", zone: "nsw", latitude: -35.1500, longitude: 150.7000, description: "Crystal-clear bay with excellent snapper, kingfish, and flathead. Offshore Jervis holds tuna, mahi-mahi, and marlin in season." },
  { slug: "ulladulla", name: "Ulladulla", state: "NSW", zone: "nsw", latitude: -35.3500, longitude: 150.4700, description: "Productive offshore grounds with excellent yellowfin tuna and mahi-mahi. The harbour and Pigeon Bay hold bream, flathead, and jewfish." },
  { slug: "batemans-bay", name: "Batemans Bay", state: "NSW", zone: "nsw", latitude: -35.7072, longitude: 150.1757, description: "Clyde River estuary with outstanding flathead, bream, and jewfish. Offshore produces snapper and tuna during summer months." },
  { slug: "narooma", name: "Narooma", state: "NSW", zone: "nsw", latitude: -36.2200, longitude: 150.1300, description: "Wagonga Inlet holds bream, flathead, and luderick. Offshore delivers excellent snapper and tuna. Montague Island draws pelagics and seals." },
  { slug: "tathra-merimbula", name: "Tathra / Merimbula", state: "NSW", zone: "nsw", latitude: -36.7300, longitude: 149.9000, description: "Two Lakes at Merimbula and the Tathra wharf are local icons. Snapper, flathead, and bream in the lakes. Offshore pelagics in summer." },
  { slug: "eden", name: "Eden", state: "NSW", zone: "nsw", latitude: -37.0653, longitude: 149.9019, description: "Twofold Bay is famous for tuna, kingfish, and marlin. The deep water canyon is one of the best big-game fishing destinations on the east coast." },

  // ── Lord Howe Island ──────────────────────────────────────────────────────
  { slug: "lord-howe-island", name: "Lord Howe Island", state: "NSW", zone: "lord_howe", latitude: -31.5500, longitude: 159.0800, description: "World Heritage island 600km offshore. Exceptional kingfish, trevally, wahoo, and coral reef fishing. Remote and pristine — world-class light-tackle action." },

  // ── Victoria Coastal ──────────────────────────────────────────────────────
  { slug: "port-phillip-bay", name: "Port Phillip Bay / Melbourne", state: "VIC", zone: "vic_coast", latitude: -37.8136, longitude: 144.9631, description: "Victoria's largest bay offers year-round snapper, flathead, whiting, and bream. Rips and artificial reefs attract kingfish and southern bluefin tuna in summer." },
  { slug: "mornington-peninsula", name: "Mornington Peninsula", state: "VIC", zone: "vic_coast", latitude: -38.2000, longitude: 145.0300, description: "The Port Phillip side holds flathead and bream; Bass Strait side offers snapper and excellent kingfish in summer. Strong gummy shark fishery." },
  { slug: "phillip-island", name: "Phillip Island", state: "VIC", zone: "vic_coast", latitude: -38.5000, longitude: 145.2000, description: "Strong snapper and barracouta. Western Entrance and the Nobbies are productive for SBT in summer. Good rock fishing for salmon and sweep." },
  { slug: "westernport-bay", name: "Westernport Bay", state: "VIC", zone: "vic_coast", latitude: -38.3500, longitude: 145.3500, description: "Excellent snapper and whiting bay. Channels and flats around French Island produce great flathead and bream year-round. Good gummy shark at night." },
  { slug: "wilsons-promontory", name: "Wilsons Promontory", state: "VIC", zone: "vic_coast", latitude: -39.1300, longitude: 146.3700, description: "The southernmost tip of mainland Australia. Remote offshore reefs hold snapper, blue-eye trevalla, and striped trumpeter. SBT and kingfish in summer." },
  { slug: "lakes-entrance", name: "Lakes Entrance / Gippsland", state: "VIC", zone: "vic_coast", latitude: -37.8800, longitude: 147.9800, description: "Gippsland Lakes is one of Australia's largest lake systems. Bream, flathead, and estuary perch inside. Offshore holds snapper, blue-eye trevalla, and SBT." },
  { slug: "mallacoota", name: "Mallacoota", state: "VIC", zone: "vic_coast", latitude: -37.5700, longitude: 149.7500, description: "Remote and pristine, Mallacoota Inlet holds exceptional bream, flathead, and estuary perch. Offshore reefs deliver snapper and blue-eye trevalla." },
  { slug: "apollo-bay", name: "Apollo Bay", state: "VIC", zone: "vic_coast", latitude: -38.7500, longitude: 143.6700, description: "Great Ocean Road fishing hub. Offshore reefs hold snapper and blue-eye. Rock and jetty fishing for salmon and sweep. SBT from charters in summer." },
  { slug: "portland-vic", name: "Portland", state: "VIC", zone: "vic_coast", latitude: -38.3400, longitude: 141.6000, description: "Victoria's main southern bluefin tuna port. SBT charters run summer through autumn. Offshore reefs hold blue-eye trevalla, snapper, and gummy shark." },
  { slug: "warrnambool", name: "Warrnambool", state: "VIC", zone: "vic_coast", latitude: -38.3800, longitude: 142.4800, description: "Surf coast fishing for salmon and tailor. Lady Bay and Hopkins River hold bream and flathead. Offshore snapper and gummy shark." },

  // ── Tasmania ──────────────────────────────────────────────────────────────
  { slug: "hobart", name: "Hobart / D'Entrecasteaux Channel", state: "TAS", zone: "tas", latitude: -42.8800, longitude: 147.3300, description: "Tasmania's capital on the Derwent Estuary with bream, flathead, and estuary perch. D'Entrecasteaux Channel offers snapper and blue-eye trevalla. Sea-run trout are a specialty." },
  { slug: "st-helens", name: "St Helens", state: "TAS", zone: "tas", latitude: -41.3200, longitude: 148.2500, description: "Northeast Tasmania's premier fishing hub. Exceptional bluefin tuna from St Helens Point. Nearby reefs and Georges Bay hold snapper, flathead, and bream." },
  { slug: "bicheno", name: "Bicheno", state: "TAS", zone: "tas", latitude: -41.8700, longitude: 148.3000, description: "Protected east coast location with good reef fishing. Snapper, bastard trumpeter, and blue warehou are common. Offshore for blue-eye and striped trumpeter." },
  { slug: "bruny-island", name: "Bruny Island", state: "TAS", zone: "tas", latitude: -43.4500, longitude: 147.3800, description: "Remote island south of Hobart. Excellent snapper, blue-eye trevalla, and striped trumpeter. Wild sea-run trout in the Adventure Bay area." },
  { slug: "strahan", name: "Strahan / Macquarie Harbour", state: "TAS", zone: "tas", latitude: -42.1500, longitude: 145.3300, description: "West coast fishing with Macquarie Harbour holding exceptional sea-run trout. Offshore for blue-eye and striped trumpeter in season." },
  { slug: "devonport", name: "Devonport / Bass Strait", state: "TAS", zone: "tas", latitude: -41.1800, longitude: 146.3500, description: "Northern Tasmania facing Bass Strait. Good snapper and flathead in the Mersey River. Offshore delivers school and bluefin tuna in season." },
  { slug: "launceston-tamar", name: "Launceston / Tamar River", state: "TAS", zone: "tas", latitude: -41.4300, longitude: 147.1300, description: "The Tamar estuary holds bream, flathead, and estuary perch. Sea-run trout run the river in autumn. Bass Strait offshore for tuna and snapper." },
  { slug: "port-arthur", name: "Port Arthur / Tasman Peninsula", state: "TAS", zone: "tas", latitude: -43.1500, longitude: 147.8500, description: "Spectacular cliff fishing for striped trumpeter and blue warehou. Offshore deep reefs hold blue-eye trevalla and diverse reef species." },

  // ── Murray-Darling Freshwater ─────────────────────────────────────────────
  { slug: "murray-river-albury", name: "Murray River (Albury)", state: "NSW", zone: "murray_darling", latitude: -36.0700, longitude: 146.9200, description: "The upper Murray around Albury-Wodonga is prime Murray cod and golden perch country. Snags, rock bars, and deep pools hold big cod throughout the system." },
  { slug: "murray-river-echuca", name: "Murray River (Echuca)", state: "VIC", zone: "murray_darling", latitude: -36.1400, longitude: 144.7500, description: "Historic paddle steamer town on the Murray. Excellent Murray cod with trophy fish common. Golden perch and catfish year-round." },
  { slug: "murray-river-mildura", name: "Murray River (Mildura)", state: "VIC", zone: "murray_darling", latitude: -34.1900, longitude: 142.1600, description: "Lower Murray with warm water and excellent golden perch. Lake Cullulleraine nearby. Trophy Murray cod in the deeper pools and log snags." },
  { slug: "lake-hume", name: "Lake Hume", state: "NSW", zone: "murray_darling", latitude: -36.1000, longitude: 147.0300, description: "Large reservoir on the upper Murray. Excellent golden perch, Murray cod, and trout. Rocky points and submerged timber hold fish year-round." },
  { slug: "lake-mulwala", name: "Lake Mulwala / Yarrawonga", state: "VIC", zone: "murray_darling", latitude: -35.9800, longitude: 146.0000, description: "Impoundment on the Murray at Yarrawonga. Famous for large Murray cod and golden perch. Fallen trees and rock walls provide excellent structure." },
  { slug: "murrumbidgee-river", name: "Murrumbidgee River", state: "NSW", zone: "murray_darling", latitude: -34.8200, longitude: 146.0400, description: "Major Murray-Darling tributary with good Murray cod and golden perch. The Wagga Wagga to Hay stretch has significant snag habitat for big cod." },
  { slug: "macquarie-river", name: "Macquarie River", state: "NSW", zone: "murray_darling", latitude: -31.9700, longitude: 148.6600, description: "Western NSW river system with good golden perch and Murray cod. The Macquarie Marshes hold healthy populations in flood seasons." },
  { slug: "darling-river-bourke", name: "Darling River (Bourke)", state: "NSW", zone: "murray_darling", latitude: -30.0900, longitude: 145.9400, description: "Remote outback fishing on the iconic Darling River. Golden perch, bony bream, and catfish. Best in spring when flood flows activate the system." },

  // ── Alpine / Snowy Mountains / TAS Highlands ──────────────────────────────
  { slug: "lake-eucumbene", name: "Lake Eucumbene", state: "NSW", zone: "alpine", latitude: -36.1300, longitude: 148.7500, description: "Australia's largest inland reservoir. Trophy brown and rainbow trout fishing. Spring bait fishing and autumn fly fishing are highlights of the trout calendar." },
  { slug: "lake-jindabyne", name: "Lake Jindabyne", state: "NSW", zone: "alpine", latitude: -36.4200, longitude: 148.6300, description: "Gateway to Snowy Mountains trout fishing. Brown and rainbow trout with excellent trolling and fly fishing. Surrounded by spectacular mountain scenery." },
  { slug: "snowy-mountains-rivers", name: "Snowy Mountains Rivers", state: "NSW", zone: "alpine", latitude: -36.4000, longitude: 148.3600, description: "World-class fly fishing on the Thredbo, Eucumbene, and Tumut rivers. Wild brown trout in pristine alpine streams — dry fly and nymph territory." },
  { slug: "lake-eildon", name: "Lake Eildon", state: "VIC", zone: "alpine", latitude: -37.1800, longitude: 145.9300, description: "Victoria's largest reservoir. Excellent golden perch, Murray cod, and rainbow trout. Rocky points, creek arms, and the Delatite arm hold fish year-round." },
  { slug: "ovens-king-rivers", name: "Ovens / King Rivers", state: "VIC", zone: "alpine", latitude: -36.7300, longitude: 146.8900, description: "Victorian alpine rivers with wild brown and rainbow trout. The Ovens between Bright and Myrtleford is a fly fishing gem — clear water and challenging fish." },
  { slug: "goulburn-river-vic", name: "Goulburn River (VIC)", state: "VIC", zone: "alpine", latitude: -37.3300, longitude: 145.9100, description: "One of Victoria's premier trout fisheries. The upper Goulburn above Eildon has wild brown trout. Excellent dry fly fishing during the evening rise." },
  { slug: "arthurs-lake-tas", name: "Arthurs Lake", state: "TAS", zone: "alpine", latitude: -41.9900, longitude: 146.9000, description: "Tasmania's premier trout lake. Prolific brown and rainbow trout with famous polaroiding in the shallows. Dun season produces spectacular dry fly fishing." },
  { slug: "lake-st-clair", name: "Lake St Clair", state: "TAS", zone: "alpine", latitude: -42.1100, longitude: 146.1700, description: "Australia's deepest lake in the heart of the World Heritage wilderness. Remote brown and rainbow trout in a spectacular alpine setting." },
];
