// Zone-based seasonal ratings for each species.
// Index 0 is unused. Indices 1-12 = Jan-Dec.
// Ratings: null = skip (no/very poor), 'poor', 'fair', 'good', 'peak'

type Rating = "poor" | "fair" | "good" | "peak" | null;
type ZoneRatings = Record<string, (Rating | null)[]>;

// Zones: far_north_qld | central_qld | southeast_qld | nsw |
//        vic_coast | tas | lord_howe | murray_darling | alpine
export const SEASON_DATA: Record<string, ZoneRatings> = {
  "black-marlin": {
    far_north_qld: [null, null, null, null, null, null, null, null, "fair", "peak", "peak", "peak", "fair"],
    central_qld:   [null, null, null, null, null, null, null, "fair", "fair", "good", "good", "fair", null],
    southeast_qld: [null, null, null, null, null, null, null, null, null, "fair", "fair", "fair", null],
    nsw:           [null, "fair", "fair", null, null, null, null, null, null, null, "fair", "fair", "fair"],
    lord_howe:     [null, "fair", "peak", "good", null, null, null, null, null, null, "fair", "good", "fair"],
  },
  "blue-marlin": {
    far_north_qld: [null, "fair", "fair", "fair", null, null, null, null, "fair", "fair", "good", "good", "fair"],
    central_qld:   [null, "fair", "fair", null, null, null, null, null, "fair", "fair", "good", "fair", "fair"],
    southeast_qld: [null, "fair", "good", "fair", null, null, null, null, null, "fair", "fair", "fair", "fair"],
    nsw:           [null, "good", "peak", "good", "fair", null, null, null, null, null, "fair", "good", "good"],
    lord_howe:     [null, "good", "peak", "good", "fair", null, null, null, null, null, "fair", "good", "good"],
  },
  "sailfish": {
    far_north_qld: [null, "good", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "good", "good", "good"],
    central_qld:   [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "good", "good", "good"],
    southeast_qld: [null, "fair", "good", "fair", "poor", null, null, null, null, "fair", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", null, null, null, null, null, null, null, "fair", "fair"],
    lord_howe:     [null, "good", "good", "fair", "poor", null, null, null, null, "fair", "fair", "good", "good"],
  },
  "yellowfin-tuna": {
    far_north_qld: [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    central_qld:   [null, "good", "good", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    southeast_qld: [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    nsw:           [null, "peak", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "good", "peak", "peak"],
    vic_coast:     [null, "good", "good", "fair", "poor", null, null, null, null, "fair", "fair", "good", "good"],
    tas:           [null, "fair", "good", "fair", "poor", null, null, null, null, null, "fair", "fair", "fair"],
    lord_howe:     [null, "good", "good", "good", "fair", "poor", null, null, "fair", "good", "peak", "peak", "good"],
  },
  "longtail-tuna": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "good", "fair", "fair", "good", "peak", "peak", "good", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "good", "fair", "fair", "good", "peak", "peak", "good", "fair"],
    southeast_qld: [null, "fair", "good", "good", "peak", "good", "fair", "fair", "good", "peak", "peak", "good", "fair"],
    nsw:           [null, "good", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "good", "good", "good"],
    vic_coast:     [null, "fair", "fair", "fair", "fair", "poor", null, null, null, "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "fair", "good", "good", "peak", "good", "fair", "fair", "good", "peak", "peak", "good", "fair"],
  },
  "spanish-mackerel": {
    far_north_qld: [null, "good", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    central_qld:   [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    southeast_qld: [null, "fair", "good", "good", "fair", "poor", "poor", "poor", "poor", "fair", "good", "good", "good"],
    nsw:           [null, "fair", "fair", "good", "good", "good", "fair", "fair", "good", "good", "good", "fair", "fair"],
    lord_howe:     [null, "good", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "good"],
  },
  "wahoo": {
    far_north_qld: [null, "peak", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    central_qld:   [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    southeast_qld: [null, "good", "good", "fair", "poor", null, null, null, null, "fair", "good", "good", "good"],
    nsw:           [null, "good", "good", "fair", "poor", null, null, null, null, "fair", "fair", "good", "good"],
    lord_howe:     [null, "peak", "peak", "good", "fair", "poor", null, null, "fair", "good", "peak", "peak", "peak"],
  },
  "mahi-mahi": {
    far_north_qld: [null, "peak", "peak", "good", "fair", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    central_qld:   [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    southeast_qld: [null, "good", "good", "fair", "poor", null, null, null, null, "fair", "good", "good", "good"],
    nsw:           [null, "good", "good", "good", "fair", "poor", null, null, null, "fair", "fair", "good", "good"],
    lord_howe:     [null, "peak", "peak", "good", "fair", "poor", null, null, null, "good", "peak", "peak", "peak"],
  },
  "southern-bluefin-tuna": {
    vic_coast:     [null, "peak", "peak", "good", "fair", "poor", null, null, null, "fair", "good", "peak", "peak"],
    tas:           [null, "peak", "peak", "good", "fair", "poor", null, null, null, "fair", "good", "good", "peak"],
    nsw:           [null, "good", "good", "fair", "poor", null, null, null, null, null, "fair", "fair", "good"],
  },
  "yellowtail-kingfish": {
    far_north_qld: [null, "fair", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    nsw:           [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    vic_coast:     [null, "good", "good", "fair", "fair", "fair", "poor", "poor", "fair", "fair", "good", "peak", "peak"],
    tas:           [null, "fair", "good", "fair", "fair", "poor", "poor", "poor", "poor", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "good", "good", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
  },
  "giant-trevally": {
    far_north_qld: [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "good", "good"],
    central_qld:   [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    southeast_qld: [null, "fair", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "poor", "poor", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "good", "good"],
  },
  "cobia": {
    far_north_qld: [null, "good", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "good", "good", "good"],
    central_qld:   [null, "good", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "good", "good", "good"],
    southeast_qld: [null, "fair", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "good", "fair", "fair"],
    nsw:           [null, "fair", "good", "good", "good", "fair", "poor", "poor", "poor", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "peak", "peak", "good", "fair", null, null, null, "fair", "good", "good", "good"],
  },
  "tailor": {
    far_north_qld: [null, "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "fair", "good", "good", "good", "good", "fair", "fair", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "fair", "fair", "fair"],
    vic_coast:     [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair"],
    tas:           [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "fair", "fair", "fair", "fair", "good", "good", "good", "good", "fair", "fair", "fair", "fair"],
  },
  "australian-salmon": {
    vic_coast:     [null, "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "fair", "fair", "fair"],
    tas:           [null, "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "fair", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "good", "fair", "fair", "good", "good", "fair", "fair", "fair"],
  },
  "gummy-shark": {
    vic_coast:     [null, "good", "good", "good", "peak", "good", "fair", "fair", "fair", "good", "good", "good", "good"],
    tas:           [null, "good", "good", "good", "peak", "good", "fair", "fair", "fair", "good", "good", "good", "good"],
    nsw:           [null, "fair", "fair", "good", "peak", "good", "fair", "fair", "fair", "good", "good", "fair", "fair"],
  },
  "coral-trout": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "good", "good", "good", "good", "good", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "fair", "fair"],
  },
  "red-emperor": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "good", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
  },
  "nannygai": {
    far_north_qld: [null, "good", "good", "good", "peak", "peak", "peak", "peak", "peak", "good", "good", "good", "good"],
    central_qld:   [null, "good", "good", "fair", "peak", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    southeast_qld: [null, "good", "good", "good", "peak", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    nsw:           [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    vic_coast:     [null, "fair", "fair", "fair", "good", "good", "good", "good", "good", "good", "fair", "fair", "fair"],
    tas:           [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "fair", "fair", "fair"],
  },
  "snapper": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    southeast_qld: [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    nsw:           [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    vic_coast:     [null, "good", "fair", "fair", "good", "peak", "good", "fair", "peak", "peak", "peak", "good", "good"],
    tas:           [null, "good", "good", "good", "peak", "good", "fair", "fair", "good", "peak", "peak", "good", "good"],
    lord_howe:     [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "fair", "fair", "fair"],
  },
  "kingfish-qld": {
    far_north_qld: [null, "fair", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "fair", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    vic_coast:     [null, "good", "good", "fair", "fair", "fair", "poor", "poor", "fair", "fair", "good", "good", "good"],
    tas:           [null, "fair", "fair", "fair", "fair", "poor", "poor", "poor", "poor", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "good", "fair", "fair", "good", "good", "good", "fair", "good", "good", "good", "good"],
  },
  "blue-eye-trevalla": {
    vic_coast:     [null, "good", "fair", "good", "peak", "peak", "good", "good", "good", "good", "fair", "fair", "good"],
    tas:           [null, "good", "fair", "good", "peak", "peak", "good", "good", "good", "good", "fair", "fair", "good"],
    nsw:           [null, "fair", "fair", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair", "fair"],
  },
  "striped-trumpeter": {
    tas:           [null, "good", "good", "fair", "peak", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    vic_coast:     [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair"],
  },
  "barramundi": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "good", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "fair", "fair"],
    southeast_qld: [null, "fair", "poor", "poor", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
  },
  "mangrove-jack": {
    far_north_qld: [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    central_qld:   [null, "good", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "good", "good"],
    southeast_qld: [null, "good", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "good", "good"],
    nsw:           [null, "fair", "fair", "poor", "poor", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "fair", "fair", "fair", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
  },
  "flathead": {
    far_north_qld: [null, "fair", "fair", "fair", "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    southeast_qld: [null, "good", "fair", "fair", "good", "good", "peak", "peak", "good", "good", "peak", "peak", "good"],
    nsw:           [null, "good", "fair", "fair", "good", "good", "good", "good", "good", "peak", "peak", "peak", "good"],
    vic_coast:     [null, "good", "good", "fair", "fair", "fair", "fair", "fair", "fair", "good", "good", "peak", "peak"],
    tas:           [null, "good", "good", "fair", "fair", "fair", "fair", "fair", "fair", "good", "good", "good", "good"],
  },
  "mulloway": {
    far_north_qld: [null, "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "good", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    nsw:           [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    vic_coast:     [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "fair", "fair", "fair"],
    tas:           [null, "fair", "fair", "fair", "good", "good", "fair", "fair", "fair", "good", "fair", "fair", "fair"],
  },
  "bream": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "good", "good", "good", "good", "good", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "good", "good", "good", "good", "good", "fair", "fair", "fair"],
    southeast_qld: [null, "good", "fair", "fair", "good", "peak", "peak", "good", "good", "peak", "peak", "good", "good"],
    nsw:           [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "peak", "peak", "good", "good"],
    vic_coast:     [null, "good", "good", "fair", "good", "peak", "peak", "good", "good", "good", "good", "good", "good"],
    tas:           [null, "good", "good", "fair", "fair", "good", "fair", "fair", "good", "good", "good", "good", "good"],
  },
  "whiting": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "good", "good", "good", "good", "good", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "good", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    southeast_qld: [null, "good", "fair", "fair", "good", "good", "peak", "peak", "good", "peak", "peak", "good", "good"],
    nsw:           [null, "good", "good", "fair", "good", "good", "peak", "peak", "good", "peak", "peak", "good", "good"],
    vic_coast:     [null, "good", "good", "fair", "fair", "good", "good", "good", "fair", "good", "good", "good", "good"],
    tas:           [null, "good", "good", "fair", "fair", "good", "good", "good", "fair", "good", "good", "good", "good"],
  },
  "luderick": {
    southeast_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "fair", "fair", "fair"],
    vic_coast:     [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    tas:           [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
  },
  "jewfish": {
    far_north_qld: [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    central_qld:   [null, "good", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "good", "good"],
    southeast_qld: [null, "fair", "fair", "poor", "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "good", "good"],
  },

  // ── Freshwater species ────────────────────────────────────────────────────
  "murray-cod": {
    murray_darling: [null, "good", "good", "good", "fair", "fair", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    alpine:         [null, "fair", "fair", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "good", "fair"],
  },
  "golden-perch": {
    murray_darling: [null, "good", "fair", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    alpine:         [null, "fair", "fair", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "good", "fair"],
  },
  "silver-perch": {
    murray_darling: [null, "fair", "fair", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "good", "fair"],
  },
  "australian-bass": {
    southeast_qld:  [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    nsw:            [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
  },
  "brown-trout": {
    alpine:         [null, "fair", "fair", "good", "peak", "peak", "fair", "poor", "poor", "good", "peak", "peak", "good"],
    murray_darling: [null, "fair", "fair", "good", "peak", "good", "fair", "poor", "poor", "good", "peak", "good", "fair"],
    tas:            [null, "fair", "good", "good", "peak", "peak", "good", "fair", "fair", "good", "peak", "peak", "fair"],
  },
  "rainbow-trout": {
    alpine:         [null, "fair", "good", "good", "peak", "peak", "good", "fair", "poor", "good", "peak", "peak", "good"],
    murray_darling: [null, "fair", "good", "good", "peak", "good", "fair", "poor", "poor", "good", "peak", "good", "fair"],
    tas:            [null, "good", "good", "good", "peak", "peak", "good", "fair", "fair", "good", "peak", "peak", "good"],
  },
  "ocean-trout": {
    tas:            [null, "good", "good", "peak", "peak", "good", "fair", "fair", "good", "peak", "peak", "good", "good"],
    alpine:         [null, "good", "good", "good", "peak", "peak", "good", "fair", "fair", "peak", "peak", "good", "good"],
    vic_coast:      [null, "fair", "fair", "good", "peak", "good", "fair", "fair", "fair", "good", "good", "fair", "fair"],
    nsw:            [null, "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "good", "good", "fair", "fair"],
  },
  "redfin": {
    murray_darling: [null, "good", "good", "fair", "peak", "peak", "good", "fair", "fair", "good", "good", "good", "good"],
    alpine:         [null, "good", "good", "fair", "peak", "peak", "fair", "fair", "fair", "good", "good", "good", "good"],
    tas:            [null, "good", "good", "fair", "peak", "peak", "fair", "fair", "fair", "good", "good", "good", "good"],
    nsw:            [null, "good", "good", "fair", "peak", "good", "fair", "fair", "fair", "good", "good", "good", "good"],
  },
  "saratoga": {
    far_north_qld:  [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    central_qld:    [null, "fair", "fair", "fair", "fair", "good", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
  },
  "catfish": {
    murray_darling: [null, "good", "good", "fair", "fair", "fair", "fair", "fair", "fair", "good", "peak", "peak", "good"],
    far_north_qld:  [null, "good", "good", "fair", "fair", "good", "good", "good", "good", "good", "good", "good", "good"],
    central_qld:    [null, "fair", "fair", "fair", "fair", "good", "good", "good", "good", "fair", "fair", "good", "fair"],
    southeast_qld:  [null, "good", "good", "fair", "fair", "good", "good", "good", "fair", "fair", "good", "good", "good"],
  },
};
