// Zone-based seasonal ratings for each species.
// Index 0 is unused. Indices 1-12 = Jan-Dec.
// Ratings: null = skip (no/very poor), 'poor', 'fair', 'good', 'peak'

type Rating = "poor" | "fair" | "good" | "peak" | null;
type ZoneRatings = Record<string, (Rating | null)[]>;

// Zones: far_north_qld | central_qld | southeast_qld | nsw |
//        vic_coast | tas | lord_howe | murray_darling | alpine
export const SEASON_DATA: Record<string, ZoneRatings> = {
  "black-marlin": {
    far_north_qld: [null, null, null, null, null, null, null, null, "fair", "peak", "peak", "peak", "fair"],
    central_qld:   [null, null, null, null, null, null, null, "fair", "fair", "good", "good", "fair", null],
    southeast_qld: [null, null, null, null, null, null, null, null, null, "fair", "fair", "fair", null],
    nsw:           [null, "fair", "fair", null, null, null, null, null, null, null, "fair", "fair", "fair"],
    lord_howe:     [null, "fair", "peak", "good", null, null, null, null, null, null, "fair", "good", "fair"],
    wa_pilbara:      [null, null, null, null, null, null, null, null, "fair", "good", "peak", "good", null],
    wa_kimberley:    [null, null, null, null, null, null, null, null, "fair", "good", "peak", "good", null],
    christmas_island:[null, null, null, null, null, null, null, null, "fair", "good", "peak", "peak", "fair"],
    cocos_islands:   [null, null, null, null, null, null, null, null, "fair", "good", "peak", "peak", "fair"],
  },
  "blue-marlin": {
    far_north_qld: [null, "fair", "fair", "fair", null, null, null, null, "fair", "fair", "good", "good", "fair"],
    central_qld:   [null, "fair", "fair", null, null, null, null, null, "fair", "fair", "good", "fair", "fair"],
    southeast_qld: [null, "fair", "good", "fair", null, null, null, null, null, "fair", "fair", "fair", "fair"],
    nsw:           [null, "good", "peak", "good", "fair", null, null, null, null, null, "fair", "good", "good"],
    lord_howe:     [null, "good", "peak", "good", "fair", null, null, null, null, null, "fair", "good", "good"],
  },
  "sailfish": {
    far_north_qld: [null, "good", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "good", "good", "good"],
    central_qld:   [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "good", "good", "good"],
    southeast_qld: [null, "fair", "good", "fair", "poor", null, null, null, null, "fair", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", null, null, null, null, null, null, null, "fair", "fair"],
    lord_howe:     [null, "good", "good", "fair", "poor", null, null, null, null, "fair", "fair", "good", "good"],
    nt_top_end:      [null, "peak", "peak", "good", "fair", "poor", null, null, "fair", "good", "good", "peak", "peak"],
    nt_gulf:         [null, "peak", "peak", "good", "fair", "poor", null, null, "fair", "good", "good", "peak", "peak"],
    wa_kimberley:    [null, "peak", "peak", "good", "fair", null, null, null, "fair", "good", "good", "peak", "peak"],
    wa_pilbara:      [null, "peak", "peak", "good", "fair", null, null, null, "fair", "good", "good", "peak", "peak"],
    wa_mid_west:     [null, "good", "peak", "good", "fair", null, null, null, "fair", "good", "good", "good", "good"],
    christmas_island:[null, "peak", "peak", "peak", "good", "fair", null, null, "fair", "good", "peak", "peak", "peak"],
    cocos_islands:   [null, "peak", "peak", "peak", "good", "fair", null, null, "fair", "good", "peak", "peak", "peak"],
  },
  "yellowfin-tuna": {
    nz_north_island: [null, "peak", "peak", "good", "fair", null, null, null, null, null, null, null, "fair"],
    far_north_qld: [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    central_qld:   [null, "good", "good", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    southeast_qld: [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    nsw:           [null, "peak", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "good", "peak", "peak"],
    vic_coast:     [null, "good", "good", "fair", "poor", null, null, null, null, "fair", "fair", "good", "good"],
    tas:           [null, "fair", "good", "fair", "poor", null, null, null, null, null, "fair", "fair", "fair"],
    lord_howe:     [null, "good", "good", "good", "fair", "poor", null, null, "fair", "good", "peak", "peak", "good"],
    nt_top_end:      [null, "good", "fair", "fair", "poor", null, null, null, null, "fair", "good", "peak", "peak"],
    nt_gulf:         [null, "good", "fair", "fair", "poor", null, null, null, null, "fair", "good", "peak", "peak"],
    wa_kimberley:    [null, "good", "fair", "fair", "fair", "poor", null, null, "fair", "good", "peak", "peak", "good"],
    wa_pilbara:      [null, "peak", "good", "good", "fair", "poor", null, null, "fair", "good", "peak", "peak", "peak"],
    wa_mid_west:     [null, "peak", "good", "good", "fair", "poor", null, null, "fair", "good", "peak", "peak", "peak"],
    wa_southwest:    [null, "good", "good", "good", "fair", null, null, null, null, "fair", "fair", "good", "good"],
    sa_spencer_gulf: [null, "good", "fair", "fair", null, null, null, null, null, null, null, "fair", "fair"],
    sa_south:        [null, "good", "good", "fair", null, null, null, null, null, null, "fair", "good", "good"],
    christmas_island:[null, "peak", "peak", "good", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    cocos_islands:   [null, "peak", "peak", "good", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
  },
  "longtail-tuna": {
    nz_north_island: [null, "good", "peak", "good", "fair", null, null, null, null, null, null, "fair", "good"],
    far_north_qld: [null, "fair", "fair", "fair", "good", "good", "fair", "fair", "good", "peak", "peak", "good", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "good", "fair", "fair", "good", "peak", "peak", "good", "fair"],
    southeast_qld: [null, "fair", "good", "good", "peak", "good", "fair", "fair", "good", "peak", "peak", "good", "fair"],
    nsw:           [null, "good", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "good", "good", "good"],
    vic_coast:     [null, "fair", "fair", "fair", "fair", "poor", null, null, null, "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "fair", "good", "good", "peak", "good", "fair", "fair", "good", "peak", "peak", "good", "fair"],
  },
  "spanish-mackerel": {
    far_north_qld: [null, "good", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    central_qld:   [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    southeast_qld: [null, "fair", "good", "good", "fair", "poor", "poor", "poor", "poor", "fair", "good", "good", "good"],
    nsw:           [null, "fair", "fair", "good", "good", "good", "fair", "fair", "good", "good", "good", "fair", "fair"],
    lord_howe:     [null, "good", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    nt_top_end:      [null, "good", "fair", "fair", "poor", null, null, null, null, "fair", "good", "peak", "peak"],
    nt_gulf:         [null, "good", "fair", "fair", "poor", null, null, null, null, "fair", "good", "peak", "peak"],
    wa_kimberley:    [null, "peak", "peak", "good", "fair", "poor", null, null, "fair", "good", "peak", "peak", "peak"],
    wa_pilbara:      [null, "peak", "peak", "good", "fair", "poor", null, null, "fair", "good", "peak", "peak", "peak"],
    wa_mid_west:     [null, "good", "peak", "good", "fair", null, null, null, "fair", "good", "peak", "peak", "good"],
    wa_southwest:    [null, "fair", "good", "good", "fair", null, null, null, null, "fair", "fair", "good", "fair"],
    christmas_island:[null, "good", "good", "good", "fair", null, null, null, "fair", "good", "peak", "peak", "good"],
    cocos_islands:   [null, "good", "good", "good", "fair", null, null, null, "fair", "good", "peak", "peak", "good"],
  },
  "wahoo": {
    far_north_qld: [null, "peak", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    central_qld:   [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    southeast_qld: [null, "good", "good", "fair", "poor", null, null, null, null, "fair", "good", "good", "good"],
    nsw:           [null, "good", "good", "fair", "poor", null, null, null, null, "fair", "fair", "good", "good"],
    lord_howe:     [null, "peak", "peak", "good", "fair", "poor", null, null, "fair", "good", "peak", "peak", "peak"],
    nt_top_end:      [null, "peak", "peak", "good", "fair", null, null, null, "fair", "good", "peak", "peak", "peak"],
    wa_kimberley:    [null, "peak", "peak", "good", "fair", null, null, null, "fair", "good", "peak", "peak", "peak"],
    wa_pilbara:      [null, "peak", "peak", "good", "fair", null, null, null, "fair", "good", "peak", "peak", "peak"],
    christmas_island:[null, "peak", "peak", "peak", "good", "fair", null, null, "fair", "peak", "peak", "peak", "peak"],
    cocos_islands:   [null, "peak", "peak", "peak", "good", "fair", null, null, "fair", "peak", "peak", "peak", "peak"],
  },
  "mahi-mahi": {
    nz_north_island: [null, "peak", "peak", "good", "fair", null, null, null, null, null, null, "fair", "good"],
    far_north_qld: [null, "peak", "peak", "good", "fair", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    central_qld:   [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    southeast_qld: [null, "good", "good", "fair", "poor", null, null, null, null, "fair", "good", "good", "good"],
    nsw:           [null, "good", "good", "good", "fair", "poor", null, null, null, "fair", "fair", "good", "good"],
    lord_howe:     [null, "peak", "peak", "good", "fair", "poor", null, null, null, "good", "peak", "peak", "peak"],
    nt_top_end:      [null, "peak", "peak", "good", "fair", null, null, null, "fair", "good", "peak", "peak", "peak"],
    wa_kimberley:    [null, "peak", "peak", "good", "fair", null, null, null, "fair", "good", "peak", "peak", "peak"],
    wa_pilbara:      [null, "peak", "peak", "good", "fair", null, null, null, "fair", "good", "peak", "peak", "peak"],
    christmas_island:[null, "peak", "peak", "peak", "good", "fair", null, null, "fair", "peak", "peak", "peak", "peak"],
    cocos_islands:   [null, "peak", "peak", "peak", "good", "fair", null, null, "fair", "peak", "peak", "peak", "peak"],
  },
  "southern-bluefin-tuna": {
    vic_coast:     [null, "peak", "peak", "good", "fair", "poor", null, null, null, "fair", "good", "peak", "peak"],
    tas:           [null, "peak", "peak", "good", "fair", "poor", null, null, null, "fair", "good", "good", "peak"],
    nsw:           [null, "good", "good", "fair", "poor", null, null, null, null, null, "fair", "fair", "good"],
    wa_southwest:    [null, "good", "good", "fair", "poor", null, null, null, null, null, "fair", "fair", "good"],
    sa_south:        [null, "peak", "peak", "good", "fair", null, null, null, null, null, "fair", "good", "peak"],
    sa_spencer_gulf: [null, "fair", "good", "fair", null, null, null, null, null, null, null, "fair", "fair"],
  },
  "yellowtail-kingfish": {
    nz_north_island: [null, "peak", "peak", "peak", "good", "good", "fair", null, null, null, "fair", "good", "peak"],
    nz_south_island: [null, "good", "peak", "good", "fair", "fair", null, null, null, null, "fair", "fair", "good"],
    far_north_qld: [null, "fair", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    nsw:           [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    vic_coast:     [null, "good", "good", "fair", "fair", "fair", "poor", "poor", "fair", "fair", "good", "peak", "peak"],
    tas:           [null, "fair", "good", "fair", "fair", "poor", "poor", "poor", "poor", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "good", "good", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
  },
  "giant-trevally": {
    far_north_qld: [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "good", "good"],
    central_qld:   [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    southeast_qld: [null, "fair", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "poor", "poor", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "good", "good"],
    nt_top_end:      [null, "peak", "peak", "peak", "good", "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak"],
    nt_gulf:         [null, "peak", "peak", "peak", "good", "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak"],
    wa_kimberley:    [null, "peak", "peak", "peak", "good", "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak"],
    wa_pilbara:      [null, "peak", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    wa_mid_west:     [null, "good", "peak", "peak", "good", "fair", null, null, "fair", "good", "peak", "peak", "good"],
    christmas_island:[null, "peak", "peak", "peak", "peak", "good", "good", "good", "peak", "peak", "peak", "peak", "peak"],
    cocos_islands:   [null, "peak", "peak", "peak", "peak", "good", "good", "good", "peak", "peak", "peak", "peak", "peak"],
  },
  "cobia": {
    far_north_qld: [null, "good", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "good", "good", "good"],
    central_qld:   [null, "good", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "good", "good", "good"],
    southeast_qld: [null, "fair", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "good", "fair", "fair"],
    nsw:           [null, "fair", "good", "good", "good", "fair", "poor", "poor", "poor", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "peak", "peak", "good", "fair", null, null, null, "fair", "good", "good", "good"],
    nt_top_end:      [null, "good", "good", "fair", "fair", "fair", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    wa_kimberley:    [null, "good", "good", "fair", "fair", null, null, null, "fair", "good", "peak", "peak", "good"],
    wa_pilbara:      [null, "good", "good", "fair", "fair", null, null, null, "fair", "good", "peak", "peak", "good"],
  },
  "tailor": {
    nz_north_island: [null, "fair", "fair", "good", "good", "fair", null, null, null, null, null, "fair", "fair"],
    far_north_qld: [null, "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "fair", "good", "good", "good", "good", "fair", "fair", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "fair", "fair", "fair"],
    vic_coast:     [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair"],
    tas:           [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "fair", "fair", "fair", "fair", "good", "good", "good", "good", "fair", "fair", "fair", "fair"],
    wa_southwest:    [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    wa_mid_west:     [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    sa_south:        [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    sa_spencer_gulf: [null, "fair", "fair", "fair", "good", "peak", "good", "fair", "fair", "fair", "fair", "fair", "fair"],
  },
  "australian-salmon": {
    nz_north_island: [null, "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    nz_south_island: [null, "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair"],
    vic_coast:     [null, "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "fair", "fair", "fair"],
    tas:           [null, "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "fair", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "good", "fair", "fair", "good", "good", "fair", "fair", "fair"],
    wa_southwest:    [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    sa_south:        [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    sa_spencer_gulf: [null, "fair", "fair", "fair", "peak", "peak", "peak", "fair", "fair", "fair", "fair", "fair", "fair"],
  },
  "gummy-shark": {
    nz_south_island: [null, "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
    vic_coast:     [null, "good", "good", "good", "peak", "good", "fair", "fair", "fair", "good", "good", "good", "good"],
    tas:           [null, "good", "good", "good", "peak", "good", "fair", "fair", "fair", "good", "good", "good", "good"],
    nsw:           [null, "fair", "fair", "good", "peak", "good", "fair", "fair", "fair", "good", "good", "fair", "fair"],
    wa_southwest:    [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    sa_south:        [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "fair", "fair", "fair", "fair", "fair"],
    sa_spencer_gulf: [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
  },
  "coral-trout": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "good", "good", "good", "good", "good", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "fair", "fair"],
    nt_top_end:      [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    nt_gulf:         [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    wa_kimberley:    [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    wa_pilbara:      [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    wa_mid_west:     [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    christmas_island:[null, "good", "good", "good", "fair", "fair", "fair", "fair", "good", "good", "peak", "peak", "good"],
    cocos_islands:   [null, "good", "good", "good", "fair", "fair", "fair", "fair", "good", "good", "peak", "peak", "good"],
  },
  // No verified season data exists for dogtooth tuna yet — these ratings are a
  // reasonable estimate (calmer dry-season weather windows for reaching remote
  // offshore reef structure), not sourced facts. Replace once real data lands.
  "dogtooth-tuna": {
    far_north_qld:   [null, "fair", "fair", "fair", "good", "good", "peak", "peak", "peak", "good", "good", "fair", "fair"],
    christmas_island:[null, "good", "good", "good", "peak", "peak", "peak", "peak", "peak", "good", "good", "good", "good"],
    cocos_islands:   [null, "good", "good", "good", "peak", "peak", "peak", "peak", "peak", "good", "good", "good", "good"],
  },
  "red-emperor": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "good", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    nt_top_end:      [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    nt_gulf:         [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    wa_kimberley:    [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    wa_pilbara:      [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    wa_mid_west:     [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
  },
  "nannygai": {
    nz_north_island: [null, "fair", "fair", "fair", "good", "good", "fair", "fair", "fair", "good", "good", "fair", "fair"],
    far_north_qld: [null, "good", "good", "good", "peak", "peak", "peak", "peak", "peak", "good", "good", "good", "good"],
    central_qld:   [null, "good", "good", "fair", "peak", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    southeast_qld: [null, "good", "good", "good", "peak", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    nsw:           [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    vic_coast:     [null, "fair", "fair", "fair", "good", "good", "good", "good", "good", "good", "fair", "fair", "fair"],
    tas:           [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "fair", "fair", "fair"],
  },
  "snapper": {
    nz_north_island: [null, "peak", "peak", "good", "good", "fair", "fair", "fair", "fair", "fair", "good", "peak", "peak"],
    nz_south_island: [null, "fair", "good", "good", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    far_north_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    southeast_qld: [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    nsw:           [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    vic_coast:     [null, "good", "fair", "fair", "good", "peak", "good", "fair", "peak", "peak", "peak", "good", "good"],
    tas:           [null, "good", "good", "good", "peak", "good", "fair", "fair", "good", "peak", "peak", "good", "good"],
    lord_howe:     [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "fair", "fair", "fair"],
    wa_mid_west:     [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    wa_southwest:    [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    sa_spencer_gulf: [null, "fair", "fair", "fair", "peak", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    sa_south:        [null, "fair", "fair", "fair", "peak", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
  },
  "kingfish-qld": {
    far_north_qld: [null, "fair", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "fair", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    vic_coast:     [null, "good", "good", "fair", "fair", "fair", "poor", "poor", "fair", "fair", "good", "good", "good"],
    tas:           [null, "fair", "fair", "fair", "fair", "poor", "poor", "poor", "poor", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "good", "fair", "fair", "good", "good", "good", "fair", "good", "good", "good", "good"],
  },
  "blue-eye-trevalla": {
    nz_south_island: [null, "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "good", "fair", "fair"],
    vic_coast:     [null, "good", "fair", "good", "peak", "peak", "good", "good", "good", "good", "fair", "fair", "good"],
    tas:           [null, "good", "fair", "good", "peak", "peak", "good", "good", "good", "good", "fair", "fair", "good"],
    nsw:           [null, "fair", "fair", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair", "fair"],
  },
  "striped-trumpeter": {
    nz_south_island: [null, "fair", "fair", "good", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    tas:           [null, "good", "good", "fair", "peak", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    vic_coast:     [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair"],
  },
  "barramundi": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "good", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "fair", "fair"],
    southeast_qld: [null, "fair", "poor", "poor", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    nt_top_end:      [null, "peak", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    nt_gulf:         [null, "peak", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    wa_kimberley:    [null, "peak", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
  },
  "mangrove-jack": {
    far_north_qld: [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    central_qld:   [null, "good", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "good", "good"],
    southeast_qld: [null, "good", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "good", "good"],
    nsw:           [null, "fair", "fair", "poor", "poor", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "fair", "fair", "fair", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    nt_top_end:      [null, "peak", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    nt_gulf:         [null, "peak", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    wa_kimberley:    [null, "peak", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    wa_pilbara:      [null, "good", "peak", "peak", "good", "fair", null, null, "fair", "good", "peak", "peak", "good"],
  },
  "flathead": {
    far_north_qld: [null, "fair", "fair", "fair", "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    southeast_qld: [null, "good", "fair", "fair", "good", "good", "peak", "peak", "good", "good", "peak", "peak", "good"],
    nsw:           [null, "good", "fair", "fair", "good", "good", "good", "good", "good", "peak", "peak", "peak", "good"],
    vic_coast:     [null, "good", "good", "fair", "fair", "fair", "fair", "fair", "fair", "good", "good", "peak", "peak"],
    tas:           [null, "good", "good", "fair", "fair", "fair", "fair", "fair", "fair", "good", "good", "good", "good"],
    wa_southwest:    [null, "good", "good", "good", "good", "good", "good", "good", "good", "good", "peak", "peak", "good"],
    sa_south:        [null, "good", "good", "good", "good", "fair", "fair", "fair", "fair", "good", "peak", "peak", "good"],
  },
  "mulloway": {
    far_north_qld: [null, "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "fair", "fair"],
    southeast_qld: [null, "fair", "fair", "fair", "good", "good", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    nsw:           [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    vic_coast:     [null, "fair", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "fair", "fair", "fair"],
    tas:           [null, "fair", "fair", "fair", "good", "good", "fair", "fair", "fair", "good", "fair", "fair", "fair"],
    wa_southwest:    [null, "good", "good", "fair", "fair", "poor", null, null, null, "fair", "fair", "good", "good"],
    sa_spencer_gulf: [null, "good", "good", "fair", "fair", "poor", null, null, null, "fair", "fair", "good", "good"],
    sa_south:        [null, "peak", "peak", "good", "fair", "poor", null, null, null, "fair", "good", "peak", "peak"],
  },
  "bream": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "good", "good", "good", "good", "good", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "good", "good", "good", "good", "good", "fair", "fair", "fair"],
    southeast_qld: [null, "good", "fair", "fair", "good", "peak", "peak", "good", "good", "peak", "peak", "good", "good"],
    nsw:           [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "peak", "peak", "good", "good"],
    vic_coast:     [null, "good", "good", "fair", "good", "peak", "peak", "good", "good", "good", "good", "good", "good"],
    tas:           [null, "good", "good", "fair", "fair", "good", "fair", "fair", "good", "good", "good", "good", "good"],
    wa_southwest:    [null, "good", "good", "good", "good", "fair", "fair", "fair", "good", "good", "peak", "peak", "good"],
    sa_south:        [null, "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "good", "good", "fair", "fair"],
  },
  "whiting": {
    far_north_qld: [null, "fair", "fair", "fair", "good", "good", "good", "good", "good", "good", "fair", "fair", "fair"],
    central_qld:   [null, "fair", "fair", "fair", "good", "good", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    southeast_qld: [null, "good", "fair", "fair", "good", "good", "peak", "peak", "good", "peak", "peak", "good", "good"],
    nsw:           [null, "good", "good", "fair", "good", "good", "peak", "peak", "good", "peak", "peak", "good", "good"],
    vic_coast:     [null, "good", "good", "fair", "fair", "good", "good", "good", "fair", "good", "good", "good", "good"],
    tas:           [null, "good", "good", "fair", "fair", "good", "good", "good", "fair", "good", "good", "good", "good"],
    wa_southwest:    [null, "good", "good", "fair", "fair", "poor", null, null, null, "fair", "good", "peak", "peak"],
    sa_spencer_gulf: [null, "peak", "peak", "good", "fair", "poor", null, null, null, "fair", "good", "peak", "peak"],
    sa_south:        [null, "peak", "peak", "good", "fair", "poor", null, null, null, "fair", "good", "peak", "peak"],
  },
  "luderick": {
    southeast_qld: [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "fair", "fair", "fair"],
    nsw:           [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "fair", "fair", "fair"],
    vic_coast:     [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    tas:           [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
  },
  "jewfish": {
    far_north_qld: [null, "good", "fair", "fair", "good", "peak", "peak", "peak", "good", "good", "good", "good", "good"],
    central_qld:   [null, "good", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "good", "good"],
    southeast_qld: [null, "fair", "fair", "poor", "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "fair"],
    lord_howe:     [null, "good", "fair", "fair", "good", "peak", "peak", "good", "good", "good", "good", "good", "good"],
  },

  // ── Freshwater species ────────────────────────────────────────────────────
  "murray-cod": {
    murray_darling: [null, "good", "good", "good", "fair", "fair", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    alpine:         [null, "fair", "fair", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "good", "fair"],
  },
  "golden-perch": {
    murray_darling: [null, "good", "fair", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    alpine:         [null, "fair", "fair", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "good", "fair"],
  },
  "silver-perch": {
    murray_darling: [null, "fair", "fair", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "good", "fair"],
  },
  "australian-bass": {
    southeast_qld:  [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    nsw:            [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
  },
  "brown-trout": {
    nz_north_island: [null, "good", "good", "good", "good", "fair", null, null, null, "fair", "peak", "peak", "good"],
    nz_south_island: [null, "good", "good", "good", "fair", "fair", null, null, null, "good", "peak", "peak", "good"],
    alpine:         [null, "fair", "fair", "good", "peak", "peak", "fair", "poor", "poor", "good", "peak", "peak", "good"],
    murray_darling: [null, "fair", "fair", "good", "peak", "good", "fair", "poor", "poor", "good", "peak", "good", "fair"],
    tas:            [null, "fair", "good", "good", "peak", "peak", "good", "fair", "fair", "good", "peak", "peak", "fair"],
  },
  "rainbow-trout": {
    nz_north_island: [null, "good", "good", "good", "good", "fair", "fair", "fair", "fair", "fair", "peak", "peak", "good"],
    nz_south_island: [null, "good", "good", "good", "fair", "fair", "fair", "fair", "fair", "good", "peak", "peak", "good"],
    alpine:         [null, "fair", "good", "good", "peak", "peak", "good", "fair", "poor", "good", "peak", "peak", "good"],
    murray_darling: [null, "fair", "good", "good", "peak", "good", "fair", "poor", "poor", "good", "peak", "good", "fair"],
    tas:            [null, "good", "good", "good", "peak", "peak", "good", "fair", "fair", "good", "peak", "peak", "good"],
  },
  "ocean-trout": {
    nz_north_island: [null, "fair", "fair", "fair", "fair", null, null, null, null, null, "fair", "fair", "fair"],
    nz_south_island: [null, "good", "peak", "peak", "good", "fair", null, null, null, "fair", "good", "good", "good"],
    tas:            [null, "good", "good", "peak", "peak", "good", "fair", "fair", "good", "peak", "peak", "good", "good"],
    alpine:         [null, "good", "good", "good", "peak", "peak", "good", "fair", "fair", "peak", "peak", "good", "good"],
    vic_coast:      [null, "fair", "fair", "good", "peak", "good", "fair", "fair", "fair", "good", "good", "fair", "fair"],
    nsw:            [null, "fair", "fair", "good", "good", "fair", "fair", "fair", "fair", "good", "good", "fair", "fair"],
  },
  "redfin": {
    murray_darling: [null, "good", "good", "fair", "peak", "peak", "good", "fair", "fair", "good", "good", "good", "good"],
    alpine:         [null, "good", "good", "fair", "peak", "peak", "fair", "fair", "fair", "good", "good", "good", "good"],
    tas:            [null, "good", "good", "fair", "peak", "peak", "fair", "fair", "fair", "good", "good", "good", "good"],
    nsw:            [null, "good", "good", "fair", "peak", "good", "fair", "fair", "fair", "good", "good", "good", "good"],
  },
  "saratoga": {
    far_north_qld:  [null, "fair", "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    central_qld:    [null, "fair", "fair", "fair", "fair", "good", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    wa_kimberley:    [null, "good", "good", "fair", "fair", "poor", null, null, "fair", "good", "peak", "peak", "good"],
    nt_top_end:      [null, "good", "good", "fair", "fair", "poor", null, null, "fair", "good", "peak", "peak", "good"],
  },
  "catfish": {
    murray_darling: [null, "good", "good", "fair", "fair", "fair", "fair", "fair", "fair", "good", "peak", "peak", "good"],
    far_north_qld:  [null, "good", "good", "fair", "fair", "good", "good", "good", "good", "good", "good", "good", "good"],
    central_qld:    [null, "fair", "fair", "fair", "fair", "good", "good", "good", "good", "fair", "fair", "good", "fair"],
    southeast_qld:  [null, "good", "good", "fair", "fair", "good", "good", "good", "fair", "fair", "good", "good", "good"],
  },
  "queenfish": {
    nt_top_end:      [null, "peak", "peak", "peak", "good", "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak"],
    nt_gulf:         [null, "peak", "peak", "peak", "good", "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak"],
    wa_kimberley:    [null, "peak", "peak", "peak", "good", "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak"],
    wa_pilbara:      [null, "good", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    far_north_qld:   [null, "peak", "peak", "peak", "good", "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak"],
    christmas_island:[null, "peak", "peak", "peak", "peak", "good", "good", "good", "peak", "peak", "peak", "peak", "peak"],
    cocos_islands:   [null, "peak", "peak", "peak", "peak", "good", "good", "good", "peak", "peak", "peak", "peak", "peak"],
  },
  "threadfin-salmon": {
    nt_top_end:      [null, "peak", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    nt_gulf:         [null, "peak", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    wa_kimberley:    [null, "peak", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    far_north_qld:   [null, "peak", "peak", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    central_qld:     [null, "good", "peak", "good", "fair", "poor", null, null, "poor", "fair", "good", "good", "good"],
    southeast_qld:   [null, "fair", "good", "fair", "poor", null, null, null, null, "fair", "fair", "fair", "fair"],
  },
  "spangled-emperor": {
    nt_top_end:      [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    nt_gulf:         [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    wa_kimberley:    [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    wa_pilbara:      [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    wa_mid_west:     [null, "good", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    far_north_qld:   [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    central_qld:     [null, "good", "good", "fair", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "good"],
    christmas_island:[null, "good", "peak", "peak", "good", "fair", "fair", "fair", "good", "peak", "peak", "peak", "good"],
    cocos_islands:   [null, "good", "peak", "peak", "good", "fair", "fair", "fair", "good", "peak", "peak", "peak", "good"],
  },
  "dhufish": {
    wa_mid_west:     [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    wa_southwest:    [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    wa_pilbara:      [null, "fair", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
  },
  "baldchin-groper": {
    wa_mid_west:     [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    wa_southwest:    [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    wa_pilbara:      [null, "fair", "good", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair", "fair"],
    wa_kimberley:    [null, "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair", "good", "good", "fair"],
  },
  "king-george-whiting": {
    sa_south:        [null, "peak", "peak", "good", "fair", "poor", null, null, null, "fair", "good", "peak", "peak"],
    sa_spencer_gulf: [null, "peak", "peak", "good", "fair", "poor", null, null, null, "fair", "good", "peak", "peak"],
    vic_coast:       [null, "peak", "peak", "good", "fair", "poor", null, null, null, "fair", "fair", "good", "peak"],
    wa_southwest:    [null, "good", "peak", "good", "fair", "poor", null, null, null, "fair", "fair", "good", "good"],
  },
  "black-bream": {
    sa_south:        [null, "good", "good", "good", "peak", "peak", "good", "good", "good", "good", "peak", "peak", "good"],
    sa_spencer_gulf: [null, "good", "good", "good", "peak", "peak", "good", "good", "good", "good", "peak", "peak", "good"],
    vic_coast:       [null, "good", "good", "good", "peak", "peak", "good", "good", "good", "good", "peak", "peak", "good"],
    wa_southwest:    [null, "good", "good", "good", "peak", "peak", "good", "good", "good", "good", "peak", "peak", "good"],
  },
  "bonefish": {
    christmas_island:[null, "peak", "peak", "peak", "peak", "good", "good", "good", "peak", "peak", "peak", "peak", "peak"],
    cocos_islands:   [null, "peak", "peak", "peak", "peak", "good", "good", "good", "peak", "peak", "peak", "peak", "peak"],
    nt_top_end:      [null, "good", "good", "fair", "fair", "poor", null, null, "fair", "good", "peak", "peak", "good"],
    wa_pilbara:      [null, "good", "good", "fair", "fair", null, null, null, "fair", "good", "peak", "peak", "good"],
  },
  "milkfish": {
    christmas_island:[null, "peak", "peak", "peak", "good", "good", "good", "good", "good", "peak", "peak", "peak", "peak"],
    cocos_islands:   [null, "peak", "peak", "peak", "good", "good", "good", "good", "good", "peak", "peak", "peak", "peak"],
  },
  "rankin-cod": {
    wa_kimberley:    [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    wa_pilbara:      [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    wa_mid_west:     [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    wa_southwest:    [null, "fair", "fair", "fair", "good", "peak", "peak", "fair", "fair", "fair", "fair", "fair", "fair"],
  },
  // ── New species ───────────────────────────────────────────────────────────
  "european-carp": {
    // Warm months best (warmer water = more active). Cold winter = slow.
    nz_north_island: [null, "good", "good", "peak", "good", "fair", "poor", "poor", "fair", "good", "peak", "good", "good"],
    murray_darling:  [null, "peak", "peak", "good", "fair", "poor", "poor", "poor", "fair", "good", "peak", "peak", "peak"],
    alpine:          [null, "good", "good", "fair", "fair", "poor", null,   null,   "fair", "good", "peak", "good", "good"],
    nsw:             [null, "good", "good", "good", "fair", "poor", "poor", "poor", "fair", "good", "good", "peak", "peak"],
    vic_coast:       [null, "good", "good", "good", "fair", "poor", null,   null,   "fair", "good", "good", "good", "good"],
    southeast_qld:   [null, "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair", "good", "peak", "peak", "peak"],
    sa_south:        [null, "good", "good", "fair", "fair", "poor", null,   null,   "fair", "good", "good", "peak", "peak"],
  },
  "black-drummer": {
    // Rock platform species. Year-round but winter-spring peak when feeding heaviest on weed.
    nsw:             [null, "fair", "fair", "good", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    vic_coast:       [null, "fair", "fair", "good", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair"],
    southeast_qld:   [null, "fair", "fair", "fair", "good", "good", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    tas:             [null, "fair", "fair", "good", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "fair"],
  },
  // ── Baitfish & Invertebrates ──────────────────────────────────────────────
  "yellowtail-scad": {
    // Schooling baitfish; abundant year-round, peaks with warmer water in summer/autumn.
    nz_north_island: [null, "good", "peak", "good", "good", "fair", "fair", "fair", "fair", "fair", "good", "good", "good"],
    nz_south_island: [null, "fair", "good", "good", "fair", "fair", "fair", "fair", "fair", "fair", "good", "fair", "fair"],
    far_north_qld:   [null, "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair", "good", "peak", "peak", "peak"],
    central_qld:     [null, "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair", "good", "peak", "peak", "peak"],
    southeast_qld:   [null, "peak", "peak", "good", "fair", "fair", "fair", "fair", "good", "good", "peak", "peak", "peak"],
    nsw:             [null, "peak", "peak", "good", "fair", "fair", "fair", "fair", "good", "good", "good", "peak", "peak"],
    vic_coast:       [null, "good", "good", "good", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "good", "good"],
    tas:             [null, "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
    lord_howe:       [null, "peak", "peak", "peak", "good", "fair", "fair", "fair", "good", "peak", "peak", "peak", "peak"],
  },
  "calamari-squid": {
    // Peaks in cooler months when squid aggregate in bays and estuaries. Year-round NZ.
    nz_north_island: [null, "fair", "fair", "good", "good", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair"],
    nz_south_island: [null, "fair", "fair", "good", "peak", "peak", "peak", "peak", "good", "good", "fair", "fair", "fair"],
    vic_coast:       [null, "good", "fair", "good", "peak", "peak", "peak", "peak", "good", "fair", "fair", "good", "good"],
    tas:             [null, "good", "fair", "good", "peak", "peak", "peak", "peak", "good", "fair", "fair", "good", "good"],
    nsw:             [null, "good", "fair", "good", "good", "peak", "peak", "good", "good", "fair", "fair", "fair", "good"],
    sa_south:        [null, "good", "fair", "good", "peak", "peak", "peak", "good", "good", "fair", "fair", "good", "good"],
    sa_spencer_gulf: [null, "good", "fair", "fair", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "good"],
    wa_southwest:    [null, "good", "good", "good", "peak", "peak", "peak", "good", "fair", "fair", "fair", "fair", "good"],
    southeast_qld:   [null, "fair", "fair", "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair"],
  },
  // ── NZ endemic species ────────────────────────────────────────────────────
  "blue-cod": {
    nz_north_island: [null, "fair", "fair", "fair", "good", "good", "good", "good", "fair", "fair", "good", "fair", "fair"],
    nz_south_island: [null, "good", "good", "peak", "peak", "peak", "peak", "good", "good", "good", "good", "good", "good"],
  },
  "tarakihi": {
    nz_north_island: [null, "fair", "fair", "good", "good", "peak", "peak", "good", "fair", "fair", "fair", "fair", "fair"],
    nz_south_island: [null, "good", "good", "peak", "peak", "peak", "peak", "good", "good", "good", "good", "good", "good"],
  },
  "hapuku-groper": {
    nz_north_island: [null, "fair", "fair", "good", "good", "peak", "peak", "good", "good", "good", "fair", "fair", "fair"],
    nz_south_island: [null, "good", "good", "peak", "peak", "peak", "good", "good", "good", "peak", "peak", "good", "good"],
  },
  "john-dory": {
    nz_north_island: [null, "fair", "fair", "good", "good", "peak", "peak", "good", "fair", "good", "fair", "fair", "fair"],
    nz_south_island: [null, "fair", "fair", "good", "peak", "peak", "peak", "good", "fair", "good", "good", "fair", "fair"],
  },
  "blue-moki": {
    nz_north_island: [null, "fair", "fair", "good", "good", "good", "fair", "fair", "fair", "fair", "fair", "fair", "fair"],
    nz_south_island: [null, "good", "good", "peak", "peak", "good", "good", "fair", "fair", "good", "good", "good", "good"],
  },
};
