export const SPECIES = [
  // Pelagic game fish
  {
    slug: "black-marlin",
    commonName: "Black Marlin",
    scientificName: "Istiompax indica",
    category: "pelagic",
    description: "The pinnacle of Australian game fishing. Heavy tackle trolling off the Ribbon Reefs north of Cairns produces the world's best black marlin fishing Sep–Dec.",
    minLegalSizeMm: null,
    bagLimit: 1,
  },
  {
    slug: "blue-marlin",
    commonName: "Blue Marlin",
    scientificName: "Makaira nigricans",
    category: "pelagic",
    description: "Found in deep blue water year-round. More common in NSW and southern QLD. Trolled with skirted lures in 100m+ water.",
    minLegalSizeMm: null,
    bagLimit: 1,
  },
  {
    slug: "sailfish",
    commonName: "Sailfish",
    scientificName: "Istiophorus platypterus",
    category: "pelagic",
    description: "The acrobatic billfish of tropical Australia. Cairns and the Whitsundays hold strong sailfish populations. Light-tackle trolling or live-bait rigging.",
    minLegalSizeMm: null,
    bagLimit: 1,
  },
  {
    slug: "yellowfin-tuna",
    commonName: "Yellowfin Tuna",
    scientificName: "Thunnus albacares",
    category: "pelagic",
    description: "Hard-fighting tuna found in blue water across the east coast. Aggregates around current lines and FADs. Excellent on poppers, stickbaits, and trolled lures.",
    minLegalSizeMm: 450,
    bagLimit: 10,
  },
  {
    slug: "longtail-tuna",
    commonName: "Longtail Tuna",
    scientificName: "Thunnus tonggol",
    category: "pelagic",
    description: "Prolific schooling tuna of the east coast. Exciting surface action on poppers and metal slugs. Found from QLD to NSW in warmer months.",
    minLegalSizeMm: 450,
    bagLimit: 10,
  },
  {
    slug: "spanish-mackerel",
    commonName: "Spanish Mackerel",
    scientificName: "Scomberomorus commerson",
    category: "pelagic",
    description: "One of Australia's premier sportfish. Explosive strikes on trolled hard bodies and live bait. Found year-round in QLD and migrates south to NSW spring–autumn.",
    minLegalSizeMm: 750,
    bagLimit: 5,
  },
  {
    slug: "wahoo",
    commonName: "Wahoo",
    scientificName: "Acanthocybium solandri",
    category: "pelagic",
    description: "The fastest fish in the sea. Prolific around the outer reefs in summer. High-speed trolling with skirted lures in deep blue water.",
    minLegalSizeMm: null,
    bagLimit: 10,
  },
  {
    slug: "mahi-mahi",
    commonName: "Mahi-Mahi (Dolphinfish)",
    scientificName: "Coryphaena hippurus",
    category: "pelagic",
    description: "Colourful, fast, and excellent eating. Attracted to floating debris and FADs. Light tackle jigging and casting. Found off the entire east coast in season.",
    minLegalSizeMm: null,
    bagLimit: 10,
  },
  // Kingfish & trevally
  {
    slug: "yellowtail-kingfish",
    commonName: "Yellowtail Kingfish",
    scientificName: "Seriola lalandi",
    category: "inshore",
    description: "The ultimate light-tackle sportfish of the NSW coast. Winter aggregations off Sydney, Jervis Bay, and Eden. Poppers, stickbaits, and livies over reefs.",
    minLegalSizeMm: 650,
    bagLimit: 5,
  },
  {
    slug: "giant-trevally",
    commonName: "Giant Trevally (GT)",
    scientificName: "Caranx ignobilis",
    category: "inshore",
    description: "The most powerful inshore fish in the tropics. Topwater poppers over reef flats. Found across northern QLD year-round. Aggressive and hard-fighting.",
    minLegalSizeMm: 450,
    bagLimit: 5,
  },
  // Reef fish
  {
    slug: "coral-trout",
    commonName: "Coral Trout",
    scientificName: "Plectropomus leopardus",
    category: "reef",
    description: "The iconic eating fish of the Great Barrier Reef. Best on soft plastics, hard bodies, and live bait over coral structure. QLD reef fishing icon.",
    minLegalSizeMm: 380,
    bagLimit: 8,
  },
  {
    slug: "red-emperor",
    commonName: "Red Emperor",
    scientificName: "Lutjanus sebae",
    category: "reef",
    description: "Premium eating fish from the Barrier Reef. Bottom fishing with whole pilchards, squid, and cut bait over deep reef structure in 40-120m.",
    minLegalSizeMm: 550,
    bagLimit: 5,
  },
  {
    slug: "nannygai",
    commonName: "Nannygai (Red Snapper)",
    scientificName: "Centroberyx affinis",
    category: "reef",
    description: "Schooling deep-reef fish highly valued for the table. Bottom fishing with pilchards and squid in 60-200m. Found across QLD and NSW offshore reefs.",
    minLegalSizeMm: 300,
    bagLimit: 20,
  },
  {
    slug: "snapper",
    commonName: "Snapper",
    scientificName: "Pagrus auratus",
    category: "reef",
    description: "Australia's most popular reef fish. Found across the east coast from shallow inshore reefs to 100m+. Bait and soft plastic fishing year-round.",
    minLegalSizeMm: 300,
    bagLimit: 20,
  },
  {
    slug: "cobia",
    commonName: "Cobia",
    scientificName: "Rachycentron canadum",
    category: "inshore",
    description: "Highly prized sportfish found over inshore reefs and structure. Excellent on live bait and large soft plastics. Strong QLD presence summer–spring.",
    minLegalSizeMm: 750,
    bagLimit: 5,
  },
  // Estuary species
  {
    slug: "barramundi",
    commonName: "Barramundi",
    scientificName: "Lates calcarifer",
    category: "estuary",
    description: "Australia's most iconic estuary sportfish. Post-wet-season barra fishing across northern QLD rivers and estuaries. Lures, livies, and bait casting to structure.",
    minLegalSizeMm: 580,
    bagLimit: 5,
  },
  {
    slug: "mangrove-jack",
    commonName: "Mangrove Jack",
    scientificName: "Lutjanus argentimaculatus",
    category: "estuary",
    description: "Ferocious estuary ambush predator of tropical Australia. Tight-line casting to mangrove roots and rock bars with hard bodies and soft plastics.",
    minLegalSizeMm: 350,
    bagLimit: 5,
  },
  {
    slug: "flathead",
    commonName: "Dusky Flathead",
    scientificName: "Platycephalus fuscus",
    category: "estuary",
    description: "The most popular estuary sportfish in NSW and southeast QLD. Soft plastics worked over sand and weed beds. Excellent eating. Spring–autumn peak.",
    minLegalSizeMm: 360,
    bagLimit: 10,
  },
  {
    slug: "mulloway",
    commonName: "Mulloway (Jewfish)",
    scientificName: "Argyrosomus japonicus",
    category: "estuary",
    description: "The holy grail of NSW estuary fishing. Large specimens haunt deep holes, bridge pylons, and ocean beaches. Night fishing with live bait or large soft plastics.",
    minLegalSizeMm: 750,
    bagLimit: 2,
  },
  {
    slug: "bream",
    commonName: "Yellowfin Bream",
    scientificName: "Acanthopagrus australis",
    category: "estuary",
    description: "The most widely caught sportfish on the east coast. Structure-oriented light-tackle fishing with lures and bait. Year-round in NSW and QLD estuaries.",
    minLegalSizeMm: 250,
    bagLimit: 20,
  },
  {
    slug: "tailor",
    commonName: "Tailor",
    scientificName: "Pomatomus saltatrix",
    category: "inshore",
    description: "Fast-running school fish of beaches and ocean entrances. Metal slugs from the beach or lures cast into gutters. Autumn–winter migrations down the NSW coast.",
    minLegalSizeMm: 300,
    bagLimit: 20,
  },
  {
    slug: "whiting",
    commonName: "Sand Whiting",
    scientificName: "Sillago ciliata",
    category: "estuary",
    description: "Fine-eating estuary sportfish found in sandy estuaries and bays. Light-tackle bait fishing with beach worms and prawns over sand flats.",
    minLegalSizeMm: 270,
    bagLimit: 20,
  },
  {
    slug: "luderick",
    commonName: "Luderick (Blackfish)",
    scientificName: "Girella tricuspidata",
    category: "estuary",
    description: "Specialist rock and weed fishing with float rigs and green weed. Rock ledge fishing along the NSW coast. Winter–spring peak season.",
    minLegalSizeMm: 270,
    bagLimit: 20,
  },
  {
    slug: "jewfish",
    commonName: "Black Jewfish",
    scientificName: "Protonibea diacanthus",
    category: "estuary",
    description: "Prized tropical estuary fish. Large specimens caught on live bait over reef and sand bottom in northern QLD. Night fishing peak activity.",
    minLegalSizeMm: 600,
    bagLimit: 5,
  },
  {
    slug: "kingfish-qld",
    commonName: "Amberjack (Samson Fish)",
    scientificName: "Seriola hippos",
    category: "reef",
    description: "Powerful mid-water reef fish. Found over offshore reefs and seamounts. Excellent on slow-pitch jigs and livies. NSW and southern QLD.",
    minLegalSizeMm: 500,
    bagLimit: 5,
  },
];
